apiVersion: v1
items:
  - apiVersion: v1
    data:
      CEREBRAS_API_KEY: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: cerebras-api-key
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      GOOGLE_AI_KEY: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: google-ai-key
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      GROQ_API_KEY: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: groq-api-key
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      openai-api-key: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: k8sgpt-openai
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      url: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"mm-webhook","namespace":"k8sgpt"},"stringData":{"url":"https://mm.35.241.255.137.nip.io/hooks/jzjdqjnck7y6ubjdauce6gm5cr"},"type":"Opaque"}
      name: mm-webhook
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      OPENROUTER_API_KEY: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: openrouter-api-key
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      SAMBANOVA_API_KEY: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: sambanova-api-key
      namespace: k8sgpt
    type: Opaque
  - apiVersion: v1
    data:
      release: REDACTED
    kind: Secret
    metadata:
      labels:
        modifiedAt: "1776142546"
        name: k8sgpt-operator
        owner: helm
        status: deployed
        version: "1"
      name: sh.helm.release.v1.k8sgpt-operator.v1
      namespace: k8sgpt
    type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
