apiVersion: v1
kind: Service
metadata:
  name: k8sgpt
  namespace: k8sgpt
  ownerReferences:
  - apiVersion: core.k8sgpt.ai/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: K8sGPT
    name: k8sgpt
spec:
  clusterIP: 10.98.31.85
  clusterIPs:
  - 10.98.31.85
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8sgpt
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-llm-proxy
  namespace: k8sgpt
spec:
  clusterIP: 10.100.101.141
  clusterIPs:
  - 10.100.101.141
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8sgpt-llm-proxy
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: k8sgpt-operator
    meta.helm.sh/release-namespace: k8sgpt
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k8sgpt-operator
    app.kubernetes.io/instance: k8sgpt-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8sgpt-operator
    app.kubernetes.io/part-of: k8sgpt-operator
    app.kubernetes.io/version: 0.2.25
    control-plane: controller-manager
    helm.sh/chart: k8sgpt-operator-0.2.27
  name: k8sgpt-operator-controller-manager-metrics-service
  namespace: k8sgpt
spec:
  clusterIP: 10.106.239.107
  clusterIPs:
  - 10.106.239.107
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: k8sgpt-operator
    app.kubernetes.io/name: k8sgpt-operator
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-robusta-bridge
  namespace: k8sgpt
spec:
  clusterIP: 10.98.197.92
  clusterIPs:
  - 10.98.197.92
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: k8sgpt-robusta-bridge
  sessionAffinity: None
  type: ClusterIP
