apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      labels:
        app.kubernetes.io/component: jenkins-controller
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-5.9.18
      name: tls-jenkins
      namespace: jenkins
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Ingress
          name: jenkins
          uid: cafaa592-de03-4330-86fd-abe59220caeb
    spec:
      dnsNames:
        - jenkins.35.241.255.137.nip.io
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: tls-jenkins
      usages:
        - digital signature
        - key encipherment
kind: List
metadata:
  resourceVersion: ""
