apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: "2026-04-14T09:45:00Z"
    generation: 1
    labels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jenkins
      helm.sh/chart: jenkins-5.9.14
    name: tls-jenkins
    namespace: jenkins
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: jenkins
      uid: cafaa592-de03-4330-86fd-abe59220caeb
    resourceVersion: "270206"
    uid: 4e9d827f-4306-4d9d-9db8-ffb23ee8b100
  spec:
    dnsNames:
    - jenkins.35.241.255.137.nip.io
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: tls-jenkins
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T09:46:23Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T08:47:49Z"
    notBefore: "2026-04-14T08:47:50Z"
    renewalTime: "2026-06-13T08:47:49Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""
