apiVersion: v1
items:
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      annotations:
        clickhouse-operator-reconcile: force-2
        meta.helm.sh/release-name: signoz
        meta.helm.sh/release-namespace: signoz
      labels:
        app.kubernetes.io/component: clickhouse
        app.kubernetes.io/instance: signoz
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: clickhouse
        app.kubernetes.io/version: 24.1.2
        clickhouse.altinity.com/app: chop
        clickhouse.altinity.com/chi: signoz-clickhouse
        clickhouse.altinity.com/cluster: cluster
        clickhouse.altinity.com/namespace: signoz
        helm.sh/chart: clickhouse-24.1.18
      name: signoz-clickhouse-cluster
      namespace: signoz
      ownerReferences:
        - apiVersion: clickhouse.altinity.com/v1
          blockOwnerDeletion: true
          controller: true
          kind: ClickHouseInstallation
          name: signoz-clickhouse
          uid: 58deef7b-2779-48e7-b592-a6996e3c1434
    spec:
      maxUnavailable: 1
      selector:
        matchLabels:
          clickhouse.altinity.com/app: chop
          clickhouse.altinity.com/chi: signoz-clickhouse
          clickhouse.altinity.com/cluster: cluster
          clickhouse.altinity.com/namespace: signoz
kind: List
metadata:
  resourceVersion: ""
