apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776133854'
    name: k8s-infra
    owner: helm
    status: deployed
    version: '1'
  name: sh.helm.release.v1.k8s-infra.v1
  namespace: signoz
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776133853'
    name: signoz
    owner: helm
    status: superseded
    version: '1'
  name: sh.helm.release.v1.signoz.v1
  namespace: signoz
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776133853'
    name: signoz
    owner: helm
    status: deployed
    version: '2'
  name: sh.helm.release.v1.signoz.v2
  namespace: signoz
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: signoz
    meta.helm.sh/release-namespace: signoz
    aiot.platform/data-keys: password,username
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/chop: 0.21.2
    helm.sh/chart: clickhouse-24.1.18
  name: signoz-clickhouse-operator
  namespace: signoz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: signoz.35.241.255.137.nip.io
    cert-manager.io/certificate-name: tls-signoz
    cert-manager.io/common-name: signoz.35.241.255.137.nip.io
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/uri-sans: ''
    aiot.platform/data-keys: tls.crt,tls.key
  labels:
    controller.cert-manager.io/fao: 'true'
  name: tls-signoz
  namespace: signoz
type: kubernetes.io/tls
