apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      annotations:
        meta.helm.sh/release-name: opentelemetry-operator
        meta.helm.sh/release-namespace: opentelemetry-operator-system
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/part-of: opentelemetry-operator
        app.kubernetes.io/version: 0.148.0
        helm.sh/chart: opentelemetry-operator-0.109.2
      name: opentelemetry-operator-serving-cert
      namespace: opentelemetry-operator-system
    spec:
      dnsNames:
        - opentelemetry-operator-webhook.opentelemetry-operator-system.svc
        - opentelemetry-operator-webhook.opentelemetry-operator-system.svc.cluster.local
      issuerRef:
        kind: Issuer
        name: opentelemetry-operator-selfsigned-issuer
      secretName: opentelemetry-operator-controller-manager-service-cert
      subject:
        organizationalUnits:
          - opentelemetry-operator
kind: List
metadata:
  resourceVersion: ""
