apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: opentelemetry-operator-webhook.opentelemetry-operator-system.svc,opentelemetry-operator-webhook.opentelemetry-operator-system.svc.cluster.local
    cert-manager.io/certificate-name: opentelemetry-operator-serving-cert
    cert-manager.io/common-name: ''
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: ''
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-name: opentelemetry-operator-selfsigned-issuer
    cert-manager.io/subject-organizationalunits: opentelemetry-operator
    cert-manager.io/uri-sans: ''
    aiot.platform/data-keys: ca.crt,tls.crt,tls.key
  labels:
    controller.cert-manager.io/fao: 'true'
  name: opentelemetry-operator-controller-manager-service-cert
  namespace: opentelemetry-operator-system
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776283298'
    name: opentelemetry-operator
    owner: helm
    status: deployed
    version: '1'
  name: sh.helm.release.v1.opentelemetry-operator.v1
  namespace: opentelemetry-operator-system
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
