apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: opentelemetry-operator-system
  - apiVersion: v1
    automountServiceAccountToken: true
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: opentelemetry-operator
        meta.helm.sh/release-namespace: opentelemetry-operator-system
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/part-of: opentelemetry-operator
        app.kubernetes.io/version: 0.148.0
        helm.sh/chart: opentelemetry-operator-0.109.2
      name: opentelemetry-operator
      namespace: opentelemetry-operator-system
kind: List
metadata:
  resourceVersion: ""
