apiVersion: v1
kind: Secret
metadata:
  name: aiot-emqx-oidc
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/component: emqx
    {{- include "aiot.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: "3afd892193e6349ca066cff50ad6dd2a0353c24bb6485b1bffa1100bce8ebb56"
