apiVersion: v1
kind: Secret
metadata:
  name: aiot-pg-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aiot.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGHOST: {{ .Values.postgres.host | quote }}
  PGPORT: {{ .Values.postgres.port | quote }}
  PGDATABASE: {{ .Values.postgres.database | quote }}
  PGUSER: {{ .Values.postgres.user | quote }}
  PGPASSWORD: {{ .Values.postgres.password | quote }}
