apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: tls-mattermost
      namespace: mattermost
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Ingress
          name: mattermost
          uid: 0a41150a-02e1-43dc-8a80-c4cbb7d8d5c9
    spec:
      dnsNames:
        - mm.35.241.255.137.nip.io
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: tls-mattermost
      usages:
        - digital signature
        - key encipherment
kind: List
metadata:
  resourceVersion: ""
