headlamp:
  config:
    oidc:
      existingSecret: oidc
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: headlamp.46.4.123.8.nip.io
        paths:
          - path: /
            type: Prefix
    tls:
      - hosts: [headlamp.46.4.123.8.nip.io]
        secretName: headlamp-tls
