headlamp:
  config:
    oidc:
      secret:
        create: false
        name: oidc
      clientID: headlamp
      clientSecret: 3kGjhx3XYayGx56I7wLdcZK25zwqBOliwUcgeNrAql6EfN7yWJWbUjtNDckxgTJ3b7kL7Z1q1MhJphhKoPS4ACowoWQwpoOM2s1DUt5VFyHC0qZEIGLFDbkjDOEoq9mS
      issuerURL: https://authentik.46.4.123.8.nip.io/application/o/headlamp/
      scopes: openid profile email
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: headlamp.46.4.123.8.nip.io
        paths:
          - path: /
            type: Prefix
    tls:
      - hosts: [headlamp.46.4.123.8.nip.io]
        secretName: headlamp-tls
