apiVersion: v2
name: victoriametrics-overlay
description: aiot-platform overlay for victoria-metrics-k8s-stack
type: application
version: 1.0.0
appVersion: "0.40.0"
dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.40.0"
    repository: https://victoriametrics.github.io/helm-charts
