apiVersion: v2
name: cnpg-overlay
description: aiot-platform overlay for cloudnative-pg
type: application
version: 1.0.0
appVersion: "0.23.0"
dependencies:
  - name: cloudnative-pg
    version: "0.23.0"
    repository: https://cloudnative-pg.io/charts
