#!/bin/bash
# bootstrap/03-sealed-secrets.sh — install bitnami-labs sealed-secrets controller.
# Encryption key is auto-generated by the controller on first start; back it up:
#   kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > sealed-secrets-key.backup.yaml
set -euo pipefail
SS_VERSION="${SS_VERSION:-2.16.2}"

helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets >/dev/null 2>&1 || true
helm repo update sealed-secrets >/dev/null

helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
  --namespace kube-system \
  --version "$SS_VERSION" \
  --set fullnameOverride=sealed-secrets-controller

kubectl -n kube-system rollout status deploy/sealed-secrets-controller

echo "[03] Backup the key NOW:"
echo "  kubectl -n kube-system get secret -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > sealed-secrets-key.backup.yaml"
echo
echo "Install kubeseal CLI on your workstation:"
echo "  https://github.com/bitnami-labs/sealed-secrets/releases"
