apiVersion: v1
items:
  - apiVersion: v1
    data:
      release: REDACTED
    kind: Secret
    metadata:
      labels:
        catalog.cattle.io/cluster-repo-name: rancher-charts
        modifiedAt: "1776631875"
        name: fleet-crd
        owner: helm
        status: deployed
        version: "1"
      name: sh.helm.release.v1.fleet-crd.v1
      namespace: cattle-fleet-system
    type: helm.sh/release.v1
  - apiVersion: v1
    data:
      release: REDACTED
    kind: Secret
    metadata:
      labels:
        catalog.cattle.io/cluster-repo-name: rancher-charts
        modifiedAt: "1776631939"
        name: fleet
        owner: helm
        status: superseded
        version: "1"
      name: sh.helm.release.v1.fleet.v1
      namespace: cattle-fleet-system
    type: helm.sh/release.v1
  - apiVersion: v1
    data:
      release: REDACTED
    kind: Secret
    metadata:
      labels:
        catalog.cattle.io/cluster-repo-name: rancher-charts
        modifiedAt: "1776631939"
        name: fleet
        owner: helm
        status: deployed
        version: "2"
      name: sh.helm.release.v1.fleet.v2
      namespace: cattle-fleet-system
    type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
