apiVersion: v1
items:
  - apiVersion: v1
    automountServiceAccountToken: false
    kind: ServiceAccount
    metadata:
      name: default
      namespace: cattle-fleet-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: fleet
        meta.helm.sh/release-namespace: cattle-fleet-system
      labels:
        app.kubernetes.io/managed-by: Helm
      name: fleet-controller
      namespace: cattle-fleet-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: fleet
        meta.helm.sh/release-namespace: cattle-fleet-system
      labels:
        app.kubernetes.io/managed-by: Helm
      name: gitjob
      namespace: cattle-fleet-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: fleet
        meta.helm.sh/release-namespace: cattle-fleet-system
      labels:
        app.kubernetes.io/managed-by: Helm
      name: helmops
      namespace: cattle-fleet-system
kind: List
metadata:
  resourceVersion: ""
