domain: 46.4.123.8.nip.io
image: dbeaver/cloudbeaver:24.3.5 # {"$imagepolicy": "flux-system:cloudbeaver-stable"}
storageClass: local-path
storageSize: 2Gi
admin:
  username: cbadmin
  password: Cb@dmin2026
postgres:
  host: pg-cluster-rw.databases.svc.cluster.local
  port: 5432
  database: aiot
  user: appuser
  password: AiotPg2026!
