apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: "2026-04-14T09:51:20Z"
    generation: 1
    name: tls-n8n
    namespace: n8n
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: n8n
      uid: 70e4fb96-a0ab-437a-82fb-2efdd54d984c
    resourceVersion: "274800"
    uid: 54efe4af-df85-4c17-b5e9-b2208c398445
  spec:
    dnsNames:
    - n8n.35.241.255.137.nip.io
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: tls-n8n
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T09:52:14Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T08:53:42Z"
    notBefore: "2026-04-14T08:53:43Z"
    renewalTime: "2026-06-13T08:53:42Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""
