apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudbeaver-conf
  namespace: aiot
  labels:
    app.kubernetes.io/name: cloudbeaver
data:
  initial-data.conf: |
    {
      adminName: "{{ .Values.admin.username }}",
      adminPassword: "{{ .Values.admin.password }}",
      teams: [
        { subjectId: "admin", teamName: "Admin", description: "Admin access.", permissions: [ "admin" ] },
        { subjectId: "user", teamName: "User", description: "All users.", permissions: [ ] }
      ]
    }
  initial-data-sources.conf: |
    {
      "folders": {},
      "connections": {
        "postgresql-aiot": {
          "provider": "postgresql",
          "driver": "postgres-jdbc",
          "name": "AIOT PostgreSQL",
          "description": "CNPG pg-cluster AIOT database",
          "save-password": true,
          "configuration": {
            "host": "{{ .Values.postgres.host }}",
            "port": "{{ .Values.postgres.port }}",
            "database": "{{ .Values.postgres.database }}",
            "url": "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}",
            "configurationType": "MANUAL",
            "type": "dev",
            "auth-model": "native",
            "user": "{{ .Values.postgres.user }}",
            "password": "{{ .Values.postgres.password }}",
            "handlers": {}
          }
        }
      }
    }
