apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  namespace: aiot
  labels:
    app.kubernetes.io/name: cloudbeaver
spec:
  selector:
    app.kubernetes.io/name: cloudbeaver
  ports:
    - name: http
      port: 8978
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudbeaver
  namespace: aiot
  labels:
    app.kubernetes.io/name: cloudbeaver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.{{ .Values.domain }}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.{{ .Values.domain }}/oauth2/start?rd=$scheme://$host$request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Original-URL https://$http_host$request_uri;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cloudbeaver.{{ .Values.domain }}
      secretName: cloudbeaver-tls
  rules:
    - host: cloudbeaver.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudbeaver
                port:
                  name: http
