apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      konflux.konflux-ci.dev/component: integration
      konflux.konflux-ci.dev/owner: konflux-integration-service
    name: integration-service-leader-election-role
    namespace: integration-service
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxIntegrationService
      name: konflux-integration-service
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
kind: List
metadata:
