apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: mlflow
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pod-executor
    namespace: mlflow
kind: List
metadata:
