{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "Ingress",
  "metadata": {
    "annotations": {
      "cert-manager.io/cluster-issuer": "letsencrypt-prod",
      "meta.helm.sh/release-name": "aiot-chaos-theater",
      "meta.helm.sh/release-namespace": "chaos-theater",
      "nginx.ingress.kubernetes.io/proxy-read-timeout": "120",
      "nginx.ingress.kubernetes.io/proxy-send-timeout": "120",
      "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    },
    "labels": {
      "app.kubernetes.io/managed-by": "Helm",
      "app.kubernetes.io/name": "aiot-chaos-theater",
      "app.kubernetes.io/part-of": "aiot-platform",
      "helm.toolkit.fluxcd.io/name": "aiot-chaos-theater",
      "helm.toolkit.fluxcd.io/namespace": "chaos-theater",
      "kustomize.toolkit.fluxcd.io/name": "awx-authentik-sso",
      "kustomize.toolkit.fluxcd.io/namespace": "flux-system"
    },
    "name": "aiot-chaos-theater",
    "namespace": "chaos-theater"
  },
  "spec": {
    "ingressClassName": "nginx",
    "rules": [
      {
        "host": "chaos-theater.46.4.123.8.nip.io",
        "http": {
          "paths": [
            {
              "backend": {
                "service": {
                  "name": "aiot-chaos-theater",
                  "port": {
                    "name": "http"
                  }
                }
              },
              "path": "/",
              "pathType": "Prefix"
            }
          ]
        }
      }
    ],
    "tls": [
      {
        "hosts": [
          "chaos-theater.46.4.123.8.nip.io"
        ],
        "secretName": "chaos-theater-tls"
      }
    ]
  }
}
