apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: cluster-fleet-local-local-1a3d67d0a899
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        fleet.cattle.io/cluster: local
        fleet.cattle.io/cluster-registration: request-v522x
        fleet.cattle.io/cluster-registration-namespace: fleet-local
        objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SRTW7DIBCFr1LNOqTYxA621FWX3fUGA0wSWgIpTNJKUe5euaklL5z+bCxZ8L3HN3OGPTE6ZIT+DBhjYmSfYhl+N4GIlxaZAy19urfhWJgy9BCSxQCLWzdEpq0vnL+ioIdMb0cqLE5NXX/8ERMR91QOaAn6KyDG1mReyHIhXmafJjHeQQ+zT7jNpPdIWWxPr2PL5OxUYTjssFrcPfnoHh6vyc//CR4kZgbwOzRnfllAQENhdjl7jLilYQKcj/RDxw7LDnrAduOkkmQqScZYQ1K5usG2041y2ulWadusrBpa5yyEbhShpUasZU1i5eRK4MYa0TpVd52TSlkNV3aUGXczkfr+Vqhcu3YSddfB5fIZAAD//2OhTAiXAgAA
        objectset.rio.cattle.io/id: cluster-registration
        objectset.rio.cattle.io/owner-gvk: fleet.cattle.io/v1alpha1, Kind=ClusterRegistration
        objectset.rio.cattle.io/owner-name: request-v522x
        objectset.rio.cattle.io/owner-namespace: fleet-local
      labels:
        fleet.cattle.io/managed: "true"
        objectset.rio.cattle.io/hash: a6fd030eb10ebbcbe03d25a69853d8d8638c54c3
      name: request-v522x-853eace5-702e-4d04-afcb-6d3299d033c8
      namespace: cluster-fleet-local-local-1a3d67d0a899
kind: List
metadata:
  resourceVersion: ""
