apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"api-gateway","namespace":"aiot"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31179,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"api-gateway"},"sessionAffinity":"None","type":"NodePort"},"status":{}}
  creationTimestamp: "2026-03-05T19:06:17Z"
  name: api-gateway
  namespace: aiot
  resourceVersion: "807763"
  uid: e9824140-4485-4f58-9e17-0f2fd4579e1d
spec:
  clusterIP: 10.101.49.182
  clusterIPs:
  - 10.101.49.182
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31179
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
