apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"cloudbeaver","namespace":"aiot"},"spec":{"ports":[{"port":8978,"targetPort":8978}],"selector":{"app":"cloudbeaver"}}}
  creationTimestamp: "2026-03-11T09:20:56Z"
  name: cloudbeaver
  namespace: aiot
  resourceVersion: "1889047"
  uid: 9317fab1-7136-4576-9df2-985c7207e12e
spec:
  clusterIP: 10.108.9.68
  clusterIPs:
  - 10.108.9.68
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8978
    protocol: TCP
    targetPort: 8978
  selector:
    app: cloudbeaver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
