apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"digital-twin","namespace":"aiot"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31801,"port":8001,"protocol":"TCP","targetPort":8001}],"selector":{"app":"digital-twin"},"sessionAffinity":"None","type":"NodePort"},"status":{}}
  creationTimestamp: "2026-03-05T18:43:20Z"
  name: digital-twin
  namespace: aiot
  resourceVersion: "804715"
  uid: e45401de-6998-40bc-8f9f-2cdca44bedbf
spec:
  clusterIP: 10.96.179.248
  clusterIPs:
  - 10.96.179.248
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31801
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: digital-twin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
