apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongo-express-external","namespace":"aiot"},"spec":{"ports":[{"nodePort":30881,"port":8081,"targetPort":8081}],"selector":{"app":"mongo-express"},"type":"NodePort"}}
  creationTimestamp: "2026-03-15T06:39:33Z"
  name: mongo-express-external
  namespace: aiot
  resourceVersion: "3391649"
  uid: a7104cc7-202a-48ca-a01e-3ae33fa9c879
spec:
  clusterIP: 10.110.248.121
  clusterIPs:
  - 10.110.248.121
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30881
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongo-express
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
