apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongo-express","namespace":"aiot"},"spec":{"ports":[{"port":8081,"targetPort":8081}],"selector":{"app":"mongo-express"}}}
  creationTimestamp: "2026-03-15T06:09:55Z"
  name: mongo-express
  namespace: aiot
  resourceVersion: "3382292"
  uid: b42c046b-2a5f-4f27-b1d6-0e896fa97649
spec:
  clusterIP: 10.103.78.191
  clusterIPs:
  - 10.103.78.191
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mongo-express
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
