apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ngrok-proxy","namespace":"aiot"},"spec":{"ports":[{"port":8090,"targetPort":8090}],"selector":{"app":"ngrok-proxy"}}}
  creationTimestamp: "2026-03-08T07:35:32Z"
  name: ngrok-proxy
  namespace: aiot
  resourceVersion: "3409614"
  uid: 0faeb8f2-0f44-453a-8538-eb2744280ef4
spec:
  clusterIP: 10.110.61.46
  clusterIPs:
  - 10.110.61.46
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31090
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: ngrok-proxy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
