apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"pgadmin","namespace":"aiot"},"spec":{"ports":[{"nodePort":31080,"port":80,"targetPort":80}],"selector":{"app":"pgadmin"},"type":"NodePort"}}
  creationTimestamp: "2026-03-05T16:23:58Z"
  name: pgadmin
  namespace: aiot
  resourceVersion: "785428"
  uid: d07375a0-d906-4ba4-844d-52f89791c4f5
spec:
  clusterIP: 10.96.238.188
  clusterIPs:
  - 10.96.238.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
