apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-master","namespace":"aiot"},"spec":{"ports":[{"name":"redis","nodePort":31379,"port":6379,"targetPort":6379}],"selector":{"app":"redis-ha","role":"master"},"type":"NodePort"}}
  creationTimestamp: "2026-03-05T18:25:45Z"
  name: redis-master
  namespace: aiot
  resourceVersion: "3297152"
  uid: d84f6d7d-789c-4edd-9234-4d4152eb0f94
spec:
  clusterIP: 10.98.4.56
  clusterIPs:
  - 10.98.4.56
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    nodePort: 31379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-ha
    role: master
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
