apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-headless","namespace":"aiot"},"spec":{"clusterIP":"None","ports":[{"name":"redis","port":6379}],"selector":{"app":"redis-ha"}}}
  creationTimestamp: "2026-03-15T01:35:31Z"
  name: redis-headless
  namespace: aiot
  resourceVersion: "3297142"
  uid: e01ba647-591c-4b1f-a170-7ccb655991f3
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-ha
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
