apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"aiot-pipeline-shared","namespace":"kubeflow-user-example-com"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"local-path"}}
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      velero.io/exclude-from-backup: "true"
    name: aiot-pipeline-shared
    namespace: kubeflow-user-example-com
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: local-path
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"kubeflow-config","namespace":"kubeflow-user-example-com"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: kubeflow-config
    namespace: kubeflow-user-example-com
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-e92a34ee-8c01-407e-94d1-1bfb9edcd1ec
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"ml-workshop-workspace","namespace":"kubeflow-user-example-com"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      velero.io/exclude-from-backup: "true"
    name: ml-workshop-workspace
    namespace: kubeflow-user-example-com
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ec2123aa-db3b-4dc3-9e9e-110d040ead63
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mlflow-artifacts-lp","namespace":"kubeflow-user-example-com"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-test-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      velero.io/exclude-from-backup: "true"
    name: mlflow-artifacts-lp
    namespace: kubeflow-user-example-com
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-971fe666-8b79-4474-891a-f881ddf05eb3
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
