apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-editor
    namespace: kubeflow-user-example-com
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: kubeflow-user-example-com
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-edit
  subjects:
  - kind: ServiceAccount
    name: default-editor
    namespace: kubeflow-user-example-com
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-viewer
    namespace: kubeflow-user-example-com
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: kubeflow-user-example-com
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-view
  subjects:
  - kind: ServiceAccount
    name: default-viewer
    namespace: kubeflow-user-example-com
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      role: admin
      user: user@example.com
    name: namespaceAdmin
    namespace: kubeflow-user-example-com
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: kubeflow-user-example-com
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kubeflow-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user@example.com
kind: List
metadata:
