apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: kubeflow-user-example-com
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default-editor
    namespace: kubeflow-user-example-com
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: kubeflow-user-example-com
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default-viewer
    namespace: kubeflow-user-example-com
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Profile
      name: kubeflow-user-example-com
kind: List
metadata:
