{{- $existing := lookup "v1" "Secret" .Release.Namespace "signoz-jwt-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: signoz-jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  secret: {{- if and $existing (index $existing.data "secret") }} {{ index $existing.data "secret" }}{{- else }} {{ randAlphaNum 64 | b64enc }}{{- end }}
