{{- $existing := lookup "v1" "Secret" .Release.Namespace "signoz-oidc-client" -}}
apiVersion: v1
kind: Secret
metadata:
  name: signoz-oidc-client
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  clientSecret: {{- if and $existing (index $existing.data "clientSecret") }} {{ index $existing.data "clientSecret" }}{{- else }} {{ randAlphaNum 96 | b64enc }}{{- end }}
