apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      batch.kubernetes.io/cronjob-scheduled-timestamp: "2026-04-25T01:00:00Z"
    labels:
      batch.kubernetes.io/job-name: zabbix-nodesclean-29617980
      job-name: zabbix-nodesclean-29617980
    name: zabbix-nodesclean-29617980
    namespace: zabbix
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: zabbix-nodesclean
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
    suspend: false
    template:
      metadata:
        labels:
          batch.kubernetes.io/job-name: zabbix-nodesclean-29617980
          job-name: zabbix-nodesclean-29617980
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - echo "deleting all stopped and unavailable HANodes older than 3600 seconds..."
            && psql -c "delete from ha_node where status in (1,2) and extract(epoch
            from now())-lastaccess>3600"
          env:
          - name: PGHOST
            value: postgres.aiot.svc
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: user
                name: zabbix-db-access
                optional: true
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: zabbix-db-access
          - name: PGDATABASE
            value: zabbix
          image: postgres:16
          imagePullPolicy: IfNotPresent
          name: hanodes-autoclean
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: zabbix
        serviceAccountName: zabbix
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
    ttlSecondsAfterFinished: 86400
  status:
    completionTime: "2026-04-25T01:00:03Z"
    conditions:
    - lastProbeTime: "2026-04-25T01:00:03Z"
      lastTransitionTime: "2026-04-25T01:00:03Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
    - lastProbeTime: "2026-04-25T01:00:03Z"
      lastTransitionTime: "2026-04-25T01:00:03Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: Complete
    ready: 0
    startTime: "2026-04-25T01:00:00Z"
    succeeded: 1
    terminating: 0
    uncountedTerminatedPods: {}
kind: List
metadata:
