apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: zabbix
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: zabbix
      meta.helm.sh/release-namespace: zabbix
    labels:
      app.kubernetes.io/instance: zabbix
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: zabbix
      app.kubernetes.io/version: 7.0.16
      argocd.argoproj.io/instance: zabbix
      helm.sh/chart: zabbix-7.0.12
    name: zabbix
    namespace: zabbix
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"zabbix-monitoring","namespace":"zabbix"}}
    name: zabbix-monitoring
    namespace: zabbix
kind: List
metadata:
