apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      annotations: {}
      labels:
        konflux.konflux-ci.dev/component: info
        konflux.konflux-ci.dev/owner: konflux-info
      name: konflux-public-info-view-role
      namespace: konflux-info
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxInfo
          name: konflux-info
          uid: 2c49a071-b16e-41b3-acac-b84a516af1fd
    rules:
      - apiGroups:
          - ""
        resourceNames:
          - konflux-public-info
          - konflux-banner-configmap
          - cluster-config
        resources:
          - configmaps
        verbs:
          - get
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      labels:
        konflux.konflux-ci.dev/component: info
        konflux.konflux-ci.dev/owner: konflux-info
      name: konflux-public-info-view-rb
      namespace: konflux-info
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxInfo
          name: konflux-info
          uid: 2c49a071-b16e-41b3-acac-b84a516af1fd
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: konflux-public-info-view-role
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: system:authenticated
kind: List
metadata:
  resourceVersion: ""
