apiVersion: v1
items:
  - apiVersion: v1
    data:
      release: REDACTED
    kind: Secret
    metadata:
      labels:
        modifiedAt: "1776837646"
        name: k8up
        owner: helm
        status: deployed
        version: "1"
      name: sh.helm.release.v1.k8up.v1
      namespace: k8up-system
    type: helm.sh/release.v1
kind: List
metadata:
  resourceVersion: ""
