apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: qdrant-indexer-code
    namespace: aiot
    files:
      - indexer.py

generatorOptions:
  disableNameSuffixHash: true
