apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rbac","app.kubernetes.io/created-by":"rancher-turtles","app.kubernetes.io/instance":"leader-election-rolebinding","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"rolebinding","app.kubernetes.io/part-of":"rancher-turtles"},"name":"rancher-turtles-leader-election-rolebinding","namespace":"cattle-turtles-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"rancher-turtles-leader-election-role"},"subjects":[{"kind":"ServiceAccount","name":"rancher-turtles-manager","namespace":"cattle-turtles-system"}]}
      meta.helm.sh/release-name: rancher-turtles
      meta.helm.sh/release-namespace: cattle-turtles-system
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: rancher-turtles
      app.kubernetes.io/instance: leader-election-rolebinding
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: rolebinding
      app.kubernetes.io/part-of: rancher-turtles
    name: rancher-turtles-leader-election-rolebinding
    namespace: cattle-turtles-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rancher-turtles-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: rancher-turtles-manager
    namespace: cattle-turtles-system
kind: List
metadata:
