apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"deployer","namespace":"aiot-demo"},"rules":[{"apiGroups":["apps"],"resources":["deployments","deployments/scale"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["apps"],"resources":["deployments/status"],"verbs":["get"]},{"apiGroups":[""],"resources":["services","pods","pods/log","events","configmaps"],"verbs":["get","list","watch","create","update","patch","delete"]}]}
    name: deployer
    namespace: aiot-demo
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    - deployments/scale
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments/status
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - services
    - pods
    - pods/log
    - events
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
kind: List
metadata:
