apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"aiot-pipeline-demo","namespace":"aiot-demo"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"aiot-pipeline-demo"},"type":"ClusterIP"}}
    name: aiot-pipeline-demo
    namespace: aiot-demo
  spec:
    clusterIP: 10.101.50.48
    clusterIPs:
    - 10.101.50.48
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: aiot-pipeline-demo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
