apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.12.4","serving.knative.dev/controller":"true"},"name":"knative-serving-activator","namespace":"knative-serving"},"rules":[{"apiGroups":[""],"resources":["configmaps","secrets"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resourceNames":["routing-serving-certs","knative-serving-certs"],"resources":["secrets"],"verbs":["get","list","watch"]}]}
    labels:
      app.kubernetes.io/name: knative-serving
      app.kubernetes.io/version: 1.12.4
      serving.knative.dev/controller: "true"
    name: knative-serving-activator
    namespace: knative-serving
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - routing-serving-certs
    - knative-serving-certs
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
kind: List
metadata:
