apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/server-type: jupyter
  labels:
    app: ml-workshop
  name: ml-workshop
  namespace: kubeflow-user-example-com
spec:
  template:
    spec:
      containers:
      - image: kubeflownotebookswg/jupyter-scipy:v1.9.2
        name: ml-workshop
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace
        - mountPath: /home/jovyan/shared-config
          name: config
      serviceAccountName: default-editor
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: ml-workshop-workspace
      - name: config
        persistentVolumeClaim:
          claimName: kubeflow-config
