apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: aiot-tb
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: tensorboard.kubeflow.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tensorboard
    name: aiot-tb
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /tensorboard/kubeflow-user-example-com/aiot-tb/
    rewrite:
      uri: /
    route:
    - destination:
        host: aiot-tb.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
    timeout: 300s
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    reconcile-trigger: '1776337432'
    sidecar.istio.io/inject: 'false'
  name: maintenance-predictor
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: serving.kserve.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: InferenceService
    name: maintenance-predictor
spec:
  gateways:
  - knative-serving/knative-local-gateway
  - kubeflow/kubeflow-gateway
  hosts:
  - maintenance-predictor.kubeflow-user-example-com.svc.cluster.local
  - maintenance-predictor.kubeflow-user-example-com.35.241.255.137.nip.io
  http:
  - headers:
      request:
        set:
          Host: maintenance-predictor-predictor.kubeflow-user-example-com.svc.cluster.local
    match:
    - authority:
        regex: ^maintenance-predictor\.kubeflow-user-example-com(\.svc(\.cluster\.local)?)?(?::\d{1,5})?$
      gateways:
      - knative-serving/knative-local-gateway
    - authority:
        regex: ^maintenance-predictor\.kubeflow-user-example-com\.35\.241\.255\.137\.nip\.io(?::\d{1,5})?$
      gateways:
      - kubeflow/kubeflow-gateway
    route:
    - destination:
        host: knative-local-gateway.istio-system.svc.cluster.local
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"maintenance-predictor-predictor","percent":100,"revisions":[{"revisionName":"maintenance-predictor-predictor-00002","percent":100}],"stepParams":{}}]}'
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev
    serving.knative.dev/creator: system:serviceaccount:kubeflow:kserve-controller-manager
    serving.knative.dev/lastModifier: system:serviceaccount:kubeflow:kserve-controller-manager
  labels:
    networking.internal.knative.dev/ingress: maintenance-predictor-predictor
    serving.knative.dev/route: maintenance-predictor-predictor
    serving.knative.dev/routeNamespace: kubeflow-user-example-com
  name: maintenance-predictor-predictor-ingress
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: networking.internal.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
    name: maintenance-predictor-predictor
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  - knative-serving/knative-local-gateway
  hosts:
  - maintenance-predictor-predictor.kubeflow-user-example-com
  - maintenance-predictor-predictor.kubeflow-user-example-com.35.241.255.137.nip.io
  - maintenance-predictor-predictor.kubeflow-user-example-com.svc
  - maintenance-predictor-predictor.kubeflow-user-example-com.svc.cluster.local
  http:
  - headers:
      request:
        set:
          K-Network-Hash: 372b05140878f24c76d8d58ff6f3d1de056fe608fe973f4149cbd3d24e4ec051
    match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com
      gateways:
      - knative-serving/knative-local-gateway
      headers:
        K-Network-Hash:
          exact: override
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
  - match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com
      gateways:
      - knative-serving/knative-local-gateway
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
  - headers:
      request:
        set:
          K-Network-Hash: 372b05140878f24c76d8d58ff6f3d1de056fe608fe973f4149cbd3d24e4ec051
    match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com.35.241.255.137.nip.io
      gateways:
      - knative-serving/knative-ingress-gateway
      headers:
        K-Network-Hash:
          exact: override
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
  - match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com.35.241.255.137.nip.io
      gateways:
      - knative-serving/knative-ingress-gateway
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  annotations:
    networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"maintenance-predictor-predictor","percent":100,"revisions":[{"revisionName":"maintenance-predictor-predictor-00002","percent":100}],"stepParams":{}}]}'
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev
    serving.knative.dev/creator: system:serviceaccount:kubeflow:kserve-controller-manager
    serving.knative.dev/lastModifier: system:serviceaccount:kubeflow:kserve-controller-manager
  labels:
    networking.internal.knative.dev/ingress: maintenance-predictor-predictor
    serving.knative.dev/route: maintenance-predictor-predictor
    serving.knative.dev/routeNamespace: kubeflow-user-example-com
  name: maintenance-predictor-predictor-mesh
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: networking.internal.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Ingress
    name: maintenance-predictor-predictor
spec:
  gateways:
  - mesh
  hosts:
  - maintenance-predictor-predictor.kubeflow-user-example-com
  - maintenance-predictor-predictor.kubeflow-user-example-com.svc
  - maintenance-predictor-predictor.kubeflow-user-example-com.svc.cluster.local
  http:
  - headers:
      request:
        set:
          K-Network-Hash: 372b05140878f24c76d8d58ff6f3d1de056fe608fe973f4149cbd3d24e4ec051
    match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com
      gateways:
      - mesh
      headers:
        K-Network-Hash:
          exact: override
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
  - match:
    - authority:
        prefix: maintenance-predictor-predictor.kubeflow-user-example-com
      gateways:
      - mesh
    retries: {}
    route:
    - destination:
        host: maintenance-predictor-predictor-00002.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: kubeflow-user-example-com
            Knative-Serving-Revision: maintenance-predictor-predictor-00002
      weight: 100
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: notebook-kubeflow-user-example-com-ml-workshop
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: kubeflow.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: ml-workshop
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        set: {}
    match:
    - uri:
        prefix: /notebook/kubeflow-user-example-com/ml-workshop/
    rewrite:
      uri: /notebook/kubeflow-user-example-com/ml-workshop/
    route:
    - destination:
        host: ml-workshop.kubeflow-user-example-com.svc.cluster.local
        port:
          number: 80
