apiVersion: v1
kind: Secret
metadata:
  annotations:
    metacontroller.k8s.io/last-applied-configuration: '{"apiVersion":"v1","data":{"accesskey":"bWluaW8=","secretkey":"bWluaW8xMjM="},"kind":"Secret","metadata":{"labels":{"controller-uid":"741b1f16-a29c-453d-9b51-db56a7ee96ad"},"name":"mlpipeline-minio-artifact","namespace":"kubeflow-user-example-com"}}'
    aiot.platform/data-keys: accesskey,secretkey
  labels:
    controller-uid: 741b1f16-a29c-453d-9b51-db56a7ee96ad
  name: mlpipeline-minio-artifact
  namespace: kubeflow-user-example-com
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: kubeflow-user-example-com
    uid: 741b1f16-a29c-453d-9b51-db56a7ee96ad
type: Opaque
