apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: konflux-ui
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: dex
      konflux.konflux-ci.dev/component: ui
      konflux.konflux-ci.dev/owner: konflux-ui
    name: dex
    namespace: konflux-ui
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxUI
      name: konflux-ui
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      konflux.konflux-ci.dev/component: ui
      konflux.konflux-ci.dev/owner: konflux-ui
    name: proxy
    namespace: konflux-ui
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxUI
      name: konflux-ui
kind: List
metadata:
