apiVersion: v1
items:
  - apiVersion: v1
    data:
      token: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: cloudflare-api-token
      namespace: dr-ops
    type: Opaque
  - apiVersion: v1
    data:
      email: REDACTED
      token: REDACTED
      username: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: github-pat
      namespace: dr-ops
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
