# Live helm values from cluster (snapshot 2026-04-27T05:54:07Z)
# Upstream chart key: k8s-infra
k8s-infra:
  global:
    clusterName: aiot-cluster
  otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
  otelDeployment:
    enabled: true
  presets:
    logsCollection:
      enabled: true
      startAt: end
      blacklist:
        enabled: false
        signozLogs: false
        namespaces: []
        pods: []
        containers: []
        additionalExclude: []
      whitelist:
        enabled: false
