alertmanager:
  fullnameOverride: am
  replicaCount: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
  config:
    route:
      receiver: "null"
      group_by: ["alertname","namespace","severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes: []
    receivers:
      - name: "null"
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 256Mi
  persistence:
    enabled: false
