apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: release-service
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        konflux.konflux-ci.dev/component: release
        konflux.konflux-ci.dev/owner: konflux-release-service
      name: release-service-controller-manager
      namespace: release-service
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxReleaseService
          name: konflux-release-service
          uid: 4b064250-17e5-46bc-b604-28beb73fb209
kind: List
metadata:
  resourceVersion: ""
