apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        konflux.konflux-ci.dev/component: integration
        konflux.konflux-ci.dev/owner: konflux-integration-service
      name: integration-service-leader-election-role
      namespace: integration-service
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxIntegrationService
          name: konflux-integration-service
          uid: 9d9ad16b-1e8b-4d51-bef5-3253a210a783
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - coordination.k8s.io
        resources:
          - leases
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - ""
        resources:
          - events
        verbs:
          - create
          - patch
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        konflux.konflux-ci.dev/component: integration
        konflux.konflux-ci.dev/owner: konflux-integration-service
      name: integration-service-leader-election-rolebinding
      namespace: integration-service
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxIntegrationService
          name: konflux-integration-service
          uid: 9d9ad16b-1e8b-4d51-bef5-3253a210a783
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: integration-service-leader-election-role
    subjects:
      - kind: ServiceAccount
        name: integration-service-controller-manager
        namespace: integration-service
kind: List
metadata:
  resourceVersion: ""
