apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    name: default
    namespace: cattle-fleet-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"fleet-controller","namespace":"cattle-fleet-system"}}
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    labels:
      app.kubernetes.io/managed-by: Helm
    name: fleet-controller
    namespace: cattle-fleet-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"gitjob","namespace":"cattle-fleet-system"}}
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    labels:
      app.kubernetes.io/managed-by: Helm
    name: gitjob
    namespace: cattle-fleet-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"helmops","namespace":"cattle-fleet-system"}}
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    labels:
      app.kubernetes.io/managed-by: Helm
    name: helmops
    namespace: cattle-fleet-system
kind: List
metadata:
