apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: fleet-default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yNwU7DMBAF/2XPOEQpTt38zfPumhgcu6q3pyj/jiJOcOhxpNHMTpsaBAZadkKtzWC51X5ii1/K1tWGR24Dw6zokNt7Flro8a2T28Brruq41ZQ/HRdFfd7peKOCqOVlZUVfaSGRm0ROcuVLCMHLZdRrAMfZwwf1t3maP8YwTme0YtN/679n10G/Wr+DTzcVVXOiCc9idBw/AQAA//9tfb6+8QAAAA
      objectset.rio.cattle.io/id: rke2-machine-config-cleanup
    labels:
      objectset.rio.cattle.io/hash: dd9dbcfd7c38885d30e78acb65a58e5962640802
    name: rke2-machineconfig-cleanup-sa
    namespace: fleet-default
kind: List
metadata:
