 apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profiles-crd.yaml
  - profiles.yaml
  - default-profile.yaml
configMapGenerator:
  - name: namespace-labels-data
    files:
      - namespace-labels.yaml
generatorOptions:
  disableNameSuffixHash: true
 