apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: profiles-system
resources:
  - https://github.com/kubeflow/manifests//applications/profiles/upstream/default?ref=v1.11.0
patchesStrategicMerge:
  - patch-serviceaccount.yaml
configMapGenerator:
  - name: namespace-labels-data
    files:
      - namespace-labels.yaml
generatorOptions:
  disableNameSuffixHash: true

