apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-deployment
  namespace: profiles-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: namespace-labels
              mountPath: /etc/profile-controller/namespace-labels.yaml
              subPath: namespace-labels.yaml
      volumes:
        - name: namespace-labels
          configMap:
            name: namespace-labels-data
      serviceAccountName: profiles-controller-service-account
      serviceAccount: profiles-controller-service-account

