apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        ignore-check.kube-linter.io/liveness-port: Keeping upstream configs
        ignore-check.kube-linter.io/readiness-port: Keeping upstream configs
      labels:
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: build-service
        control-plane: controller-manager
        konflux.konflux-ci.dev/component: build-service
        konflux.konflux-ci.dev/owner: konflux-build-service
      name: build-service-controller-manager
      namespace: build-service
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxBuildService
          name: konflux-build-service
          uid: f524d843-75d3-4a10-9995-7a03025865f7
    spec:
      progressDeadlineSeconds: 2147483647
      replicas: 0
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          control-plane: controller-manager
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/default-container: manager
          creationTimestamp: null
          labels:
            control-plane: controller-manager
        spec:
          containers:
            - args:
                - --metrics-bind-address=:8443
                - --leader-elect=false
                - --health-probe-bind-address=:8081
                - -webhook-config-path=/mnt/webhook-config.json
              command:
                - /manager
              env:
                - name: PAC_WEBHOOK_URL
                  value: http://pipelines-as-code-controller.pipelines-as-code.svc.cluster.local:8180
              image: quay.io/konflux-ci/build-service:ca44d2b8386e0af3ce29d2dc2d639a4e8fae3199
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: manager
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /readyz
                  port: 8081
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 30m
                  memory: 128Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/ssl/certs/ca-custom-bundle.crt
                  name: trusted-ca
                  readOnly: true
                  subPath: ca-bundle.crt
                - mountPath: /mnt
                  name: webhook-config
                  readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          serviceAccount: build-service-controller-manager
          serviceAccountName: build-service-controller-manager
          terminationGracePeriodSeconds: 10
          volumes:
            - configMap:
                defaultMode: 420
                items:
                  - key: ca-bundle.crt
                    path: ca-bundle.crt
                name: trusted-ca
                optional: true
              name: trusted-ca
            - configMap:
                defaultMode: 420
                items:
                  - key: webhook-config.json
                    path: webhook-config.json
                name: webhook-config-44136fa355
                optional: true
              name: webhook-config
kind: List
metadata:
  resourceVersion: ""
