apiVersion: v1
items:
  - apiVersion: v1
    data:
      url: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: mm-webhook
      namespace: robusta
    type: Opaque
  - apiVersion: v1
    data:
      active_playbooks.yaml: REDACTED
    kind: Secret
    metadata:
      annotations:
        meta.helm.sh/release-name: robusta
        meta.helm.sh/release-namespace: robusta
      labels:
        app.kubernetes.io/managed-by: Helm
        argocd.argoproj.io/instance: robusta
      name: robusta-playbooks-config-secret
      namespace: robusta
    type: Opaque
  - apiVersion: v1
    data:
      SENTRY_DSN: REDACTED
    kind: Secret
    metadata:
      annotations:
        meta.helm.sh/release-name: robusta
        meta.helm.sh/release-namespace: robusta
      labels:
        app.kubernetes.io/managed-by: Helm
        argocd.argoproj.io/instance: robusta
      name: robusta-runner-secret
      namespace: robusta
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
