apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: robusta
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: holmes
      namespace: robusta
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: robusta
        meta.helm.sh/release-namespace: robusta
      labels:
        app.kubernetes.io/managed-by: Helm
        argocd.argoproj.io/instance: robusta
      name: robusta-forwarder-service-account
      namespace: robusta
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: robusta
        meta.helm.sh/release-namespace: robusta
      labels:
        app.kubernetes.io/managed-by: Helm
        argocd.argoproj.io/instance: robusta
      name: robusta-runner-service-account
      namespace: robusta
kind: List
metadata:
  resourceVersion: ""
