apiVersion: v1
items:
  - apiVersion: v1
    data:
      CLUSTER_TOPOLOGY: REDACTED
      EXP_CLUSTER_RESOURCE_SET: REDACTED
      EXP_MACHINE_POOL: REDACTED
    kind: Secret
    metadata:
      finalizers:
        - foregroundDeletion
      name: capi-env-variables
      namespace: cattle-capi-system
      ownerReferences:
        - apiVersion: turtles-capi.cattle.io/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: CAPIProvider
          name: cluster-api
          uid: 1fa4147a-e321-47ad-9b04-c720426244d0
    type: Opaque
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      name: capi-webhook-service-cert
      namespace: cattle-capi-system
      ownerReferences:
        - apiVersion: v1
          kind: Service
          name: capi-webhook-service
          uid: 8df5a585-82ab-49a3-810f-2cfcb8c78bf3
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      cache: REDACTED
    kind: Secret
    metadata:
      annotations:
        operator.cluster.x-k8s.io/applied-spec-hash: REDACTED
      name: core-cluster-api-v1.10.6-cache
      namespace: cattle-capi-system
      ownerReferences:
        - apiVersion: turtles-capi.cattle.io/v1alpha1
          kind: CAPIProvider
          name: cluster-api
          uid: 1fa4147a-e321-47ad-9b04-c720426244d0
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
