apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cloudbeaver-data-lp-piraeus","namespace":"aiot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"piraeus-r2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      volume.kubernetes.io/selected-node: aiot-worker-02
      volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
    finalizers:
    - kubernetes.io/pvc-protection
    name: cloudbeaver-data-lp-piraeus
    namespace: aiot
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: piraeus-r2
    volumeMode: Filesystem
    volumeName: pvc-61a22797-a355-4f74-a517-bfe2c6257d14
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"open-webui-data-lp-piraeus","namespace":"aiot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"piraeus-r2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      volume.kubernetes.io/selected-node: aiot-worker-01
      volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
    finalizers:
    - kubernetes.io/pvc-protection
    name: open-webui-data-lp-piraeus
    namespace: aiot
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: piraeus-r2
    volumeMode: Filesystem
    volumeName: pvc-fc2d6ee5-7b9e-4673-a88e-7079b254bb40
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      cnpg.io/nodeSerial: "2"
      cnpg.io/operatorVersion: 1.25.1
      cnpg.io/pvcStatus: ready
      k8up.io/backup: "false"
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: aiot-worker-02
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      cnpg.io/cluster: pg-ha
      cnpg.io/instanceName: pg-ha-2
      cnpg.io/instanceRole: replica
      cnpg.io/pvcRole: PG_DATA
      role: replica
    name: pg-ha-2
    namespace: aiot
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: pg-ha
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-82882042-6e5b-4e14-b308-ee4c42242f52
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      cnpg.io/nodeSerial: "3"
      cnpg.io/operatorVersion: 1.25.1
      cnpg.io/pvcStatus: ready
      k8up.io/backup: "false"
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      cnpg.io/cluster: pg-ha
      cnpg.io/instanceName: pg-ha-3
      cnpg.io/instanceRole: primary
      cnpg.io/pvcRole: PG_DATA
      role: primary
      velero.io/exclude-from-backup: "true"
    name: pg-ha-3
    namespace: aiot
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: pg-ha
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-c9d136eb-b0b3-48f7-97d0-8a5663c926bf
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pgadmin-data-piraeus","namespace":"aiot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"piraeus-r2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      volume.kubernetes.io/selected-node: aiot-worker-02
      volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
    finalizers:
    - kubernetes.io/pvc-protection
    name: pgadmin-data-piraeus
    namespace: aiot
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: piraeus-r2
    volumeMode: Filesystem
    volumeName: pvc-13780103-955c-4b47-9417-e7c91ada2649
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"postgres-backup-data-piraeus","namespace":"aiot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"piraeus-r2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      volume.kubernetes.io/selected-node: aiot-worker-01
      volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
    finalizers:
    - kubernetes.io/pvc-protection
    name: postgres-backup-data-piraeus
    namespace: aiot
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: piraeus-r2
    volumeMode: Filesystem
    volumeName: pvc-17d30d0e-224f-42ef-bc00-70349e931e33
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"qdrant-pvc-piraeus","namespace":"aiot"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}},"storageClassName":"piraeus-r2"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      volume.kubernetes.io/selected-node: aiot-worker-01
      volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
    finalizers:
    - kubernetes.io/pvc-protection
    name: qdrant-pvc-piraeus
    namespace: aiot
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: piraeus-r2
    volumeMode: Filesystem
    volumeName: pvc-3ffcf658-4dfc-4976-8b3c-8d1329648895
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
kind: List
metadata:
