apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: aiot
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      cnpg.io/managedSecrets: '[]'
      cnpg.io/operatorVersion: 1.25.1
    labels:
      cnpg.io/cluster: pg-ha
    name: pg-ha
    namespace: aiot
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: pg-ha
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pod-executor
    namespace: aiot
kind: List
metadata:
