apiVersion: v1
items:
- apiVersion: appstudio.redhat.com/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"hello-aiot","namespace":"default-tenant"},"spec":{"description":"Simple FastAPI hello-world for Konflux PoC","displayName":"hello-aiot"}}
    name: hello-aiot
    namespace: default-tenant
  spec:
    description: Simple FastAPI hello-world for Konflux PoC
    displayName: hello-aiot
kind: List
metadata:
