apiVersion: v1
items:
- apiVersion: dex.coreos.com/v1
  claims:
    email: ""
    emailVerified: false
    preferredUsername: ""
    userID: ""
    username: ""
  clientID: oauth2-proxy
  code_challenge_method: plain
  connectorID: local
  expiry: "2026-04-23T14:53:06.634787062Z"
  hmac_key: Ym53enV2aXJmYWtpajJ2ZDI1cW43dnd6djd6aWJ0a3FsbTdzYnZmNm1tYm82anMzdGY0
  kind: AuthRequest
  loggedIn: false
  metadata:
    name: fedwca3ibp76px3fjvnetrdx7
    namespace: konflux-ui
  redirectURI: https://konflux.35.241.255.137.nip.io/oauth2/callback
  responseTypes:
  - code
  scopes:
  - openid
  - email
  - profile
  state: 58KYdK2XrSUw_l4ExSdVO1mA5O8MvQKpCpIg_eS1Qlc:/?logged_in=1
- apiVersion: dex.coreos.com/v1
  claims:
    email: ""
    emailVerified: false
    preferredUsername: ""
    userID: ""
    username: ""
  clientID: oauth2-proxy
  code_challenge_method: plain
  connectorID: local
  expiry: "2026-04-23T15:27:27.098155557Z"
  hmac_key: aWZvdWk1ZGN3b3ppazRlbm9tM200cXdpb3kyb295Z2lxbnNncHBoazRkZGx3aWd0anRp
  kind: AuthRequest
  loggedIn: false
  metadata:
    name: fv5z6p433zvackdjuieq33yjf
    namespace: konflux-ui
  redirectURI: https://konflux.35.241.255.137.nip.io/oauth2/callback
  responseTypes:
  - code
  scopes:
  - openid
  - email
  - profile
  state: KrOZ_syyIYeYvNnF1aWa94qFtQQOsIaVlUnvX67lHmg:/?logged_in=1
- apiVersion: dex.coreos.com/v1
  claims:
    email: ""
    emailVerified: false
    preferredUsername: ""
    userID: ""
    username: ""
  clientID: oauth2-proxy
  code_challenge_method: plain
  connectorID: local
  expiry: "2026-04-23T15:27:43.825199579Z"
  hmac_key: dnlhcWRjNXNobmNhMmxjYjVtZzN6aHVjNGZlcGdlZ2Q3ZHpuemJodjd6N2w2a2N6cnlx
  kind: AuthRequest
  loggedIn: false
  metadata:
    name: wnu2ob5paigjduxqkctckbxgw
    namespace: konflux-ui
  redirectURI: https://konflux.35.241.255.137.nip.io/oauth2/callback
  responseTypes:
  - code
  scopes:
  - openid
  - email
  - profile
  state: AEPWGYCBgnYBszlhCt6a0QE89E6yMbYuE82YnbbWQdU:/?logged_in=1
kind: List
metadata:
