apiVersion: v1
items:
- apiVersion: fleet.cattle.io/v1alpha1
  kind: Bundle
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xTTW/bMAz9KwXPcup8OamAndZihwHZ0GG7tD3QEp1okSVDorNmgf/7IDttvWLddrMlkY/v8b0T1MSokRHkCdA5z8jGu5h+ffmdFEfiSTB+opDZ0sT4S6NBQmWJOKvR4ZYy3JJjEG9W+B+OQrY97EHC5WEqLj4ap99tsKbYoKJ/Vjqs6RnTeoX2v0qG5hKgE2CxJPtXWjuMO5AwU6t8rYqr1UJVea7XCnO9VHk1XeUFlsV8uViXy6Wepaa/zdWL8DzdGP/V3Gm+W6ookFMUQd6dABvzjUI03oGEwxQElNar/af09JoscX9ToY0kQHnHwVtL4flob1xayljRP2rW9rsriBazua6yGa11trjCMrsqilWmUC1xjvNiuqige+gExIZU0kxTha3lzYjUIFw26p/FY2SqQcCObJ3KGPfUc4g704Dk0FInIFD0bXiintgk98iRCPIilKgm2PLOB/Ozt+Rkv45pTYfpvUt05cV720amcOst3bvexy+0+2VMjlhb6B4EMIYt8RlwKNsMD5+UOZ9+IUuKfUjT18hqd/PYBIpxyMTdCfZ0fFJ15B3n3TkL+iUMDQXsW8G1p7jxfPNoIidhB20Zue0dqU1sLB5BnjoBNT5+dXhAY7G0BDJ/ffQZA5tzSPMUg0jhQPoDuYTXGyUXENu6xnAclhdNIH1LqI/9XTh/dQLaV1DtGzhd9ysAAP//AZDp3SsEAAA
      objectset.rio.cattle.io/id: fleet-manage-agent
      objectset.rio.cattle.io/owner-gvk: /v1, Kind=Namespace
      objectset.rio.cattle.io/owner-name: fleet-local
      objectset.rio.cattle.io/owner-namespace: ""
    finalizers:
    - fleet.cattle.io/bundle-finalizer
    labels:
      objectset.rio.cattle.io/hash: 2c708c6974cf00d8ca0d5c0f1706ab63548b55d2
    name: fleet-agent-local
    namespace: fleet-local
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: false
      controller: false
      kind: Namespace
      name: fleet-local
  spec:
    defaultNamespace: cattle-fleet-local-system
    helm:
      takeOwnership: true
    resources:
    - content: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: cattle-fleet-local-system-fleet-agent-role
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'

        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: cattle-fleet-local-system-fleet-agent-role-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cattle-fleet-local-system-fleet-agent-role
        subjects:
        - kind: ServiceAccount
          name: fleet-agent
          namespace: cattle-fleet-local-system

        ---
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: fleet-agent
          namespace: cattle-fleet-local-system

        ---
        apiVersion: v1
        automountServiceAccountToken: false
        kind: ServiceAccount
        metadata:
          name: default
          namespace: cattle-fleet-local-system

        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: fleet-agent
          namespace: cattle-fleet-local-system
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: fleet-agent
          strategy: {}
          template:
            metadata:
              labels:
                app: fleet-agent
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                      - key: fleet.cattle.io/agent
                        operator: In
                        values:
                        - "true"
                    weight: 1
              containers:
              - command:
                - fleetagent
                env:
                - name: BUNDLEDEPLOYMENT_RECONCILER_WORKERS
                  value: "50"
                - name: DRIFT_RECONCILER_WORKERS
                  value: "50"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: AGENT_SCOPE
                  value: cattle-fleet-local-system
                - name: CHECKIN_INTERVAL
                  value: 15m0s
                - name: CATTLE_ELECTION_LEASE_DURATION
                  value: 30s
                - name: CATTLE_ELECTION_RETRY_PERIOD
                  value: 10s
                - name: CATTLE_ELECTION_RENEW_DEADLINE
                  value: 25s
                - name: EXPERIMENTAL_COPY_RESOURCES_DOWNSTREAM
                  value: "false"
                image: rancher/fleet-agent:v0.14.3
                imagePullPolicy: IfNotPresent
                name: fleet-agent
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  privileged: false
                  readOnlyRootFilesystem: true
                volumeMounts:
                - mountPath: /.kube
                  name: kube
                - mountPath: /tmp
                  name: tmp
              nodeSelector:
                kubernetes.io/os: linux
              securityContext:
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              serviceAccountName: fleet-agent
              tolerations:
              - effect: NoSchedule
                key: node.cloudprovider.kubernetes.io/uninitialized
                operator: Equal
                value: "true"
              - effect: NoSchedule
                key: cattle.io/os
                operator: Equal
                value: linux
              volumes:
              - emptyDir: {}
                name: kube
              - emptyDir: {}
                name: tmp

        ---
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: default-allow-all
          namespace: cattle-fleet-local-system
        spec:
          egress:
          - {}
          ingress:
          - {}
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
      name: agent.yaml
    targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
        - key: fleet.cattle.io/non-managed-agent
          operator: DoesNotExist
  status:
    conditions:
    - lastUpdateTime: "2026-04-19T21:46:57Z"
      message: WaitApplied(1) [Cluster fleet-local/local]
      status: "False"
      type: Ready
    display:
      readyClusters: 0/1
      state: WaitApplied
    maxNew: 50
    maxUnavailable: 1
    observedGeneration: 1
    partitions:
    - count: 1
      maxUnavailable: 1
      name: All
      summary:
        desiredReady: 1
        nonReadyResources:
        - bundleState: WaitApplied
          name: fleet-local/local
        ready: 0
        waitApplied: 1
      unavailable: 1
    resourcesSha256Sum: 3a2cfd886b3786c332dbd664879bc469a4f9d62d8e279435d21450476c6e4de9
    summary:
      desiredReady: 1
      nonReadyResources:
      - bundleState: WaitApplied
        name: fleet-local/local
      waitApplied: 1
    unavailable: 1
kind: List
metadata:
