apiVersion: v1
items:
- apiVersion: turtles-capi.cattle.io/v1alpha1
  kind: CAPIProvider
  metadata:
    annotations:
      helm.sh/hook: post-install, post-upgrade
      helm.sh/hook-weight: "2"
      operator.cluster.x-k8s.io/applied-spec-hash: b9e452a6800195a64a0d7113d6c809d057c75c7532cbca04445683efc73a7c70
    finalizers:
    - provider.cluster.x-k8s.io
    name: cluster-api
    namespace: cattle-capi-system
  spec:
    additionalManifests:
      name: capi-additional-rbac-roles
      namespace: cattle-capi-system
    configSecret:
      name: capi-env-variables
    enableAutomaticUpdate: false
    fetchConfig:
      selector:
        matchLabels:
          managed-by.turtles.cattle.io: "true"
          provider.cluster.x-k8s.io/name: cluster-api
          provider.cluster.x-k8s.io/type: core
    name: cluster-api
    type: core
    version: v1.10.6
  status:
    conditions:
    - lastTransitionTime: "2026-04-19T21:40:53Z"
      reason: MinimumReplicasAvailable
      status: "True"
      type: Ready
    - lastTransitionTime: "2026-04-19T20:52:20Z"
      status: "True"
      type: CheckLatestVersionTime
    - lastTransitionTime: "2026-04-19T20:52:15Z"
      status: "True"
      type: PreflightCheckPassed
    - lastTransitionTime: "2026-04-19T20:52:17Z"
      status: "True"
      type: ProviderInstalled
    - lastTransitionTime: "2026-04-19T20:52:15Z"
      status: "True"
      type: WranglerManagedCertificates
    contract: v1beta1
    installedVersion: v1.10.6
    name: cluster-api
    observedGeneration: 2
    phase: Ready
    variables:
      CLUSTER_TOPOLOGY: "true"
      EXP_CLUSTER_RESOURCE_SET: "true"
      EXP_MACHINE_POOL: "true"
kind: List
metadata:
