apiVersion: v1
items:
- apiVersion: appstudio.redhat.com/v1alpha1
  kind: Component
  metadata:
    annotations:
      build.appstudio.openshift.io/pipeline: '{"name":"docker-build-oci-ta-min","bundle":"latest"}'
      build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot","configuration-time":"2026-04-22T17:00:00Z"},"message":"done"}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"Component","metadata":{"annotations":{"build.appstudio.openshift.io/request":"configure-pac","skip-initial-checks":"true"},"name":"hello-aiot","namespace":"default-tenant"},"spec":{"application":"hello-aiot","componentName":"hello-aiot","containerImage":"internal-registry.registry.svc.cluster.local:5000/aiot/hello-aiot:latest","source":{"git":{"dockerfileUrl":"Dockerfile","revision":"main","url":"http://gitea.gitea.svc.cluster.local:3000/aiot/hello-aiot"}}}}
      test.appstudio.openshift.io/lastbuilttime: "1777039672"
    finalizers:
    - test.appstudio.openshift.io/component
    name: hello-aiot
    namespace: default-tenant
  spec:
    application: hello-aiot
    componentName: hello-aiot
    containerImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot:latest
    resources: {}
    source:
      git:
        dockerfileUrl: Dockerfile
        revision: main
        url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot
  status:
    lastBuiltCommit: 047105e6800d5bd3ab93e913068b89ee1bb10d56
    lastPromotedImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot@sha256:67eb960d0b37eb57f6a1e9277f703c1d963f793ff347e601dded21dbfa6e72f0
- apiVersion: appstudio.redhat.com/v1alpha1
  kind: Component
  metadata:
    annotations:
      build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend","configuration-time":"2026-04-23T00:00:00Z"},"message":"done"}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"Component","metadata":{"annotations":{"build.appstudio.openshift.io/status":"{\"pac\":{\"state\":\"enabled\",\"merge-url\":\"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend\",\"configuration-time\":\"2026-04-23T00:00:00Z\"},\"message\":\"done\"}"},"name":"hello-aiot-backend","namespace":"default-tenant"},"spec":{"application":"hello-aiot","componentName":"hello-aiot-backend","containerImage":"internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-backend:latest","source":{"git":{"dockerfileUrl":"Dockerfile","revision":"main","url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend"}}}}
      test.appstudio.openshift.io/lastbuilttime: "1776937343"
    finalizers:
    - test.appstudio.openshift.io/component
    name: hello-aiot-backend
    namespace: default-tenant
  spec:
    application: hello-aiot
    componentName: hello-aiot-backend
    containerImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-backend:latest
    source:
      git:
        dockerfileUrl: Dockerfile
        revision: main
        url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend
  status:
    lastBuiltCommit: 1b379d5682904b065dce66fcac339a5d7601683b
    lastPromotedImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-backend@sha256:8bea0c2559137621961d5f93fef69d49f4d574f165c02a0e6ba8d4ce9e6334dc
- apiVersion: appstudio.redhat.com/v1alpha1
  kind: Component
  metadata:
    annotations:
      build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend","configuration-time":"2026-04-23T00:00:00Z"},"message":"done"}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"Component","metadata":{"annotations":{"build.appstudio.openshift.io/status":"{\"pac\":{\"state\":\"enabled\",\"merge-url\":\"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend\",\"configuration-time\":\"2026-04-23T00:00:00Z\"},\"message\":\"done\"}"},"name":"hello-aiot-frontend","namespace":"default-tenant"},"spec":{"application":"hello-aiot","componentName":"hello-aiot-frontend","containerImage":"internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-frontend:latest","source":{"git":{"dockerfileUrl":"Dockerfile","revision":"main","url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend"}}}}
      test.appstudio.openshift.io/lastbuilttime: "1777008312"
    finalizers:
    - test.appstudio.openshift.io/component
    name: hello-aiot-frontend
    namespace: default-tenant
  spec:
    application: hello-aiot
    componentName: hello-aiot-frontend
    containerImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-frontend:latest
    source:
      git:
        dockerfileUrl: Dockerfile
        revision: main
        url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend
  status:
    lastBuiltCommit: 06274a33272a899952c3597102471ad66e01729a
    lastPromotedImage: internal-registry-http.registry.svc.cluster.local/aiot/hello-aiot-frontend@sha256:afe6190d07b5d6976c226da6a803434409e3363bf41483947322a0b4721fd2b9
kind: List
metadata:
