apiVersion: v1
items:
- apiVersion: appstudio.redhat.com/v1beta2
  kind: IntegrationTestScenario
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1beta2","kind":"IntegrationTestScenario","metadata":{"annotations":{},"name":"hello-aiot-smoke","namespace":"default-tenant"},"spec":{"application":"hello-aiot","resolverRef":{"params":[{"name":"kind","value":"pipeline"},{"name":"name","value":"integration-smoke-test"},{"name":"namespace","value":"default-tenant"}],"resolver":"cluster"}}}
    name: hello-aiot-smoke
    namespace: default-tenant
    ownerReferences:
    - apiVersion: appstudio.redhat.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: Application
      name: hello-aiot
  spec:
    application: hello-aiot
    resolverRef:
      params:
      - name: kind
        value: pipeline
      - name: name
        value: integration-smoke-test
      - name: namespace
        value: default-tenant
      resolver: cluster
      resourceKind: pipeline
kind: List
metadata:
