apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"labels":{"app":"poddefaults","app.kubernetes.io/component":"poddefaults","app.kubernetes.io/name":"poddefaults","kustomize.component":"poddefaults"},"name":"admission-webhook-selfsigned-issuer","namespace":"kubeflow"},"spec":{"selfSigned":{}}}
    labels:
      app: poddefaults
      app.kubernetes.io/component: poddefaults
      app.kubernetes.io/name: poddefaults
      kustomize.component: poddefaults
    name: admission-webhook-selfsigned-issuer
    namespace: kubeflow
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:30:29Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"name":"katib-selfsigned-issuer","namespace":"kubeflow"},"spec":{"selfSigned":{}}}
    name: katib-selfsigned-issuer
    namespace: kubeflow
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:30:28Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"labels":{"app":"cache-server-cert-manager"},"name":"kfp-cache-selfsigned-issuer","namespace":"kubeflow"},"spec":{"selfSigned":{}}}
    labels:
      app: cache-server-cert-manager
    name: kfp-cache-selfsigned-issuer
    namespace: kubeflow
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:26:43Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"labels":{"app":"kserve","app.kubernetes.io/name":"kserve"},"name":"selfsigned-issuer","namespace":"kubeflow"},"spec":{"selfSigned":{}}}
    labels:
      app: kserve
      app.kubernetes.io/name: kserve
    name: selfsigned-issuer
    namespace: kubeflow
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:27:24Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"opentelemetry-operator","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"opentelemetry-operator","app.kubernetes.io/part-of":"opentelemetry-operator","app.kubernetes.io/version":"0.148.0","helm.sh/chart":"opentelemetry-operator-0.109.2"},"name":"opentelemetry-operator-selfsigned-issuer","namespace":"opentelemetry-operator-system"},"spec":{"selfSigned":{}}}
      meta.helm.sh/release-name: opentelemetry-operator
      meta.helm.sh/release-namespace: opentelemetry-operator-system
    labels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: opentelemetry-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry-operator
      app.kubernetes.io/version: 0.148.0
      helm.sh/chart: opentelemetry-operator-0.109.2
    name: opentelemetry-operator-selfsigned-issuer
    namespace: opentelemetry-operator-system
  spec:
    selfSigned: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-15T20:01:38Z"
      observedGeneration: 1
      reason: IsReady
      status: "True"
      type: Ready
kind: List
metadata:
