apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 0c7aad42dceb6cf1ed06c83103c1d89033d5d7eaa91b18aa15d1693c5bbd8233
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-61A22797-A355-4F74-A517-BFE2C6257D14
    resource_name_suffix: ""
    secret: OneJd1UbgYikChAFvqYK
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 2b53a955e953b3a2648c0ed20a2a9497edc61abf0527ce5217eacfc3f5f0fb97
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-734704A4-89F1-4F12-B3A1-2C178791C993
    resource_name_suffix: ""
    secret: iZ+KBCswgnPBs57NE44C
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 31bfcae97d6610d7a8ca50384fedc59720b2e53434bfa28f03965f1010b36b3d
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-0C6AD1C4-EA10-4B24-95C5-12F0F48EF8AB
    resource_name_suffix: ""
    secret: O6ZShkqRWYaXxTcPEov8
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 5e963e6f65c42d127fd901f83ddd4f486270460ae940472cc5ded5404d361555
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-27976678-7D15-4989-99F4-0B94C9EC069C
    resource_name_suffix: ""
    secret: rZQ5Idyqv08cTAfgFL1h
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 65ff89673c9f708c4dd316479712400a5a781a089661a69bdb5c0562dc68f5dc
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-13780103-955C-4B47-9417-E7C91ADA2649
    resource_name_suffix: ""
    secret: Cib7LZAVToBnTitpMWN7
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 78667bec81d60286a3e846f211672aff30bced2cfec969822f82d63b9dfd90f2
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-FC2D6EE5-7B9E-4673-A88E-7079B254BB40
    resource_name_suffix: ""
    secret: TO5kQ6HCLg5yb9ISUnIx
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: 9a410bce186380dd751192aaa7f1faf3f70fba69c5befad3060e8800575f1176
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-3FFCF658-4DFC-4976-8B3C-8D1329648895
    resource_name_suffix: ""
    secret: WAXwEEToKxdNkb86/WFP
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: a785198ff59c7728254c8db70512eea03e773c8fd49fa5cdae94f1917b3a9896
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-15ABFC60-E493-48AD-A2C8-C7F7BE5A6607
    resource_name_suffix: ""
    secret: NTnd5ze+KFEs1CW0l7WM
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: ac91cbd998238f500089305fd5cc214c254f76e98230029c26895e667613a589
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-7496D803-A21D-484B-9756-4327047B07BD
    resource_name_suffix: ""
    secret: UjimnYrxFOCDb26gKMgW
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: c8c1392d0a80617870608fbd1ebaca8b8e86eb648d8b9c07575b6e27301935e5
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-72715972-98C4-4F7C-B8EB-79D33F741D9F
    resource_name_suffix: ""
    secret: yB+DhPfUjvUmCV7SAt1q
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: cc2b283d832554098d1c9dff1e9db6e8c7c8d6974e404b8c7d609c53eb9f796b
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-17D30D0E-224F-42EF-BC00-70349E931E33
    resource_name_suffix: ""
    secret: OVVKW919Vpssa2SgkSWa
    snapshot_name: ""
    transport_type: IP
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResourceDefinitions
  metadata:
    name: da7a8cade082017000c3d624029fb522a73073cdae87d5dc6726a78f92bdeb70
  spec:
    al_stripe_size: 32
    al_stripes: 1
    peer_slots: 7
    resource_name: PVC-33099827-4B54-4D13-8588-122F969DEA72
    resource_name_suffix: ""
    secret: puTq/oSyQ2kgHCw3v/cr
    snapshot_name: ""
    transport_type: IP
kind: List
metadata:
