apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 1a6562590ef19d1045d06c4055742d38288e9e6dcd71ccde5cee80f1d5a774eb
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 50
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 25fc0e7096fc653718202dc30b0c580b8ab87eac11a700cba03a7c021bc35b0c
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 46
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 2c624232cdd221771294dfbb310aca000a0df6ac8b66b696d90ef06fdefb64a3
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 8
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 2fca346db656187102ce806ac732e06a62df0dbb2829e511a770556d398e1a6e
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 54
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 41cfc0d1f2d127b04555b7246d84019b4d27710a3f3aff6e7764375b1e06e05d
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 52
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 4a44dc15364204a80fe80e9039455cc1608281820fe2b24f1e5233ade6af1dd5
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 10
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 4
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 4ec9599fc203d176a301536c2e091a19bc852759b255bd6818810a42c5fed14a
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 18
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 5f9c4ab08cac7457e9111a30e4664920607ea2c115a1433d7be98e97e64244ca
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 26
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 0
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 6b51d431df5d7f141cbececcf79edf3dd861c3b4069f0b11661a3eefacbba918
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 12
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 71ee45a3c0db9a9865f7313dd3372cf60dca6479d46261f3542eb9346e4a04d6
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 44
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 73475cb40a568e8da8a045ced110137e159f890ac4da883b6b17dc651b3a8049
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 42
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 76a50887d8f1c2e9301755428990ad81479ee21c25b43215cf524541e0503269
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 36
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 785f3ec7eb32f30b90cd0fcf3657d388b5ff4297f2f9716ff66e9b69c05ddd09
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 22
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 8527a891e224136950ff32ca212b45bc93f69fbb801c3b1ebedac52775f99e61
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 14
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: 98010bd9270f9b100b6214a21754fd33bdc8d41b2bc9f9dd16ff54d3c34ffd71
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 48
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: aea92132c4cbeb263e6ac2bf6c183b5d81737f179f21efdc5863739672f0f470
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 38
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: b17ef6d19c7a5b1ee83b907c595526dcb1eb06db8227d650d5dda0a9f4ce8cd9
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 16
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: c2356069e9d1e79ca924378153cfbbfb4d4416b1f99d41a2940bfdb66c5319db
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 24
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 2
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: d59eced1ded07f84c145592f65bdf854358e009c5cd705f5215bf18697fed103
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 40
    node_id: 0
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 6
    node_id: 1
    peer_slots: 7
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdResources
  metadata:
    name: f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a8143301782de13da2d9202b
  spec:
    al_stripe_size: 32
    al_stripes: 1
    flags: 128
    layer_resource_id: 20
    node_id: 0
    peer_slots: 7
kind: List
metadata:
