apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 364925cc50b66be431c39ea531b2fb3a5a7aa463ee265dcdbcae04142af1d5be
  spec:
    layer_resource_id: 24
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 444485ff09fb70cef393c98f2c8381610fd72bde1fb0f67f0460e2de2470bcb2
  spec:
    layer_resource_id: 10
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 451bf10a4ca050776382f3774abf650bceeef74c1ce2ed9241170bd6cb979f19
  spec:
    layer_resource_id: 52
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 48ac5daa668ab3d5b0a67c9728840c6514846fed1055aea7f7e3edf1ef66aeb3
  spec:
    layer_resource_id: 36
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 4d57629aecb5b79c479e0d4b23136307bbbe86000d84e1b97ff773bae2d6712b
  spec:
    layer_resource_id: 16
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 4ee991989e0670d53d8593e9e61765ca4c07bc42cfe5db027eb0a78e9ea63f6f
  spec:
    layer_resource_id: 48
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 524a2e56ed498174370ed6e8052e1318c774894f2b7098a91863018450fbbc46
  spec:
    layer_resource_id: 12
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 53b8c199e6f8c475f980a05a39ef46f5c084aad61f20429108732d1d0fee7934
  spec:
    layer_resource_id: 14
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 547345cae1cef37239ddbf234790d2b19d97b10adc0c306e224492a566e734b0
  spec:
    layer_resource_id: 42
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 592506cf9dae29d0e663bd7d908d8b44438ee417fa151b25d22c079b61f29630
  spec:
    layer_resource_id: 4
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 5a7a585dcd1faf15c40ad04263411d4d13f4e211eed668d428bffdbac4471552
  spec:
    layer_resource_id: 22
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 6b6b7e8fce2e52f1878245a0e1c6c7bd8a868b8693b995c84d02c63a82994ad3
  spec:
    layer_resource_id: 20
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 7c428a7f0c66dbbee4157b86be95ed45e073dae7266ecc3f01b8777c48fd4fc0
  spec:
    layer_resource_id: 26
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: 994829f87e0399cb4c1844da56596410a07adde0e74dde438f3f6675916b62ce
  spec:
    layer_resource_id: 40
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: a5aa572538a9d354fe688c5253266c5a8d921833446b6f2af8bb4ffe9563751a
  spec:
    layer_resource_id: 50
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: a7c7f375a22acedf1635e840e3cd69d02ceeb2a825d47518e2eaf6e713fdadbc
  spec:
    layer_resource_id: 44
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: ac72368a586a18c19088393573ce03074b8e8a4d8c21add8729af1890a407e52
  spec:
    layer_resource_id: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: af99f63d3ffef5cca0cd764b25d9a5c9858452fa8480bc1640449add2e3fb1a4
  spec:
    layer_resource_id: 54
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: b2a978ec73b64d61a412cd6386f600996fde92224330a5cb179dc6dfee595489
  spec:
    layer_resource_id: 46
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: bf7799df6eb226435eb8621513da7eb4231af7a77e1fc8eb761413a36104391c
  spec:
    layer_resource_id: 8
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: c10f2613d75c999ef8139f2251088aa7c485510f2acad2a076616e5aa5fb28f9
  spec:
    layer_resource_id: 18
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: e21c9380778aa3974f12310a5ee1b635c09107e786e727cd5a7cabde037e7693
  spec:
    layer_resource_id: 6
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: e6b190f6cd6fa4b87b2a657937257a5712116f79f8a07baeeb24c25bba8aef81
  spec:
    layer_resource_id: 2
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LayerDrbdVolumes
  metadata:
    name: f881cb98cb6fc5bbc04948e504b08b0209d4cb71bf07aa03e8421e4dca974a33
  spec:
    layer_resource_id: 38
    vlm_nr: 0
kind: List
metadata:
