apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: LinstorRemotes
  metadata:
    name: 226d965513660f86f9b83f71bb41f875353b836e63e376fd5b3d07da66a1994c
  spec:
    cluster_id: 8e8027c6-a761-48f5-9203-957e1fbb57a2
    dsp_name: local-remote-generated-by-linstor
    flags: 0
    name: LOCAL-REMOTE-GENERATED-BY-LINSTOR
    url: http://localhost:3370
kind: List
metadata:
