apiVersion: v1
items:
- apiVersion: piraeus.io/v1
  kind: LinstorCluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"piraeus.io/v1","kind":"LinstorCluster","metadata":{"annotations":{},"name":"linstorcluster"},"spec":{"nodeSelector":{"piraeus.io/storage":"yes"}}}
    name: linstorcluster
  spec:
    nodeSelector:
      piraeus.io/storage: "yes"
    patches:
    - patch: |-
        - op: replace
          path: /spec/template/spec/containers/1/livenessProbe/timeoutSeconds
          value: 5
        - op: replace
          path: /spec/template/spec/containers/1/livenessProbe/periodSeconds
          value: 20
        - op: replace
          path: /spec/template/spec/containers/3/livenessProbe/timeoutSeconds
          value: 5
        - op: replace
          path: /spec/template/spec/containers/3/livenessProbe/periodSeconds
          value: 20
        - op: replace
          path: /spec/template/spec/containers/4/livenessProbe/timeoutSeconds
          value: 5
        - op: replace
          path: /spec/template/spec/containers/4/livenessProbe/periodSeconds
          value: 20
        - op: replace
          path: /spec/template/spec/containers/5/livenessProbe/timeoutSeconds
          value: 5
        - op: replace
          path: /spec/template/spec/containers/5/livenessProbe/periodSeconds
          value: 20
        - op: replace
          path: /spec/template/spec/containers/6/livenessProbe/timeoutSeconds
          value: 5
        - op: replace
          path: /spec/template/spec/containers/6/livenessProbe/periodSeconds
          value: 20
      target:
        kind: Deployment
        name: linstor-csi-controller
  status:
    availableCapacityBytes: 103079215104
    capacity: 63/104GiB
    conditions:
    - lastTransitionTime: "2026-04-26T18:52:04Z"
      message: Resources applied
      observedGeneration: 2
      reason: AsExpected
      status: "True"
      type: Applied
    - lastTransitionTime: "2026-04-26T19:06:29Z"
      message: 'Controller 1.33.1 (API: 1.27.0, Git: 95da7940d6efb6a39ea303c5f37b03478a6fab0b)
        reachable at ''http://linstor-controller.piraeus-datastore.svc:3370'''
      observedGeneration: 2
      reason: AsExpected
      status: "True"
      type: Available
    - lastTransitionTime: "2026-04-26T19:52:41Z"
      message: Properties applied
      observedGeneration: 2
      reason: AsExpected
      status: "True"
      type: Configured
    freeCapacityBytes: 40370971648
    numberOfSnapshots: 0
    numberOfVolumes: 13
    runningSatellites: 2
    satellites: 2/2
    scheduledSatellites: 2
    version: 1.33.1
kind: List
metadata:
