apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: NodeNetInterfaces
  metadata:
    name: 0463a21ec6a857ddc4c77f2c08d5f3348d1c192a5028cd13e9e54d1545c0985d
  spec:
    inet_address: 10.132.0.3
    node_name: AIOT-WORKER-01
    node_net_dsp_name: default-ipv4
    node_net_name: DEFAULT-IPV4
    stlt_conn_encr_type: PLAIN
    stlt_conn_port: 3366
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: NodeNetInterfaces
  metadata:
    name: f3dbfe3855e16df03e15124acafab090692858f006beb1a59a06f40eac389940
  spec:
    inet_address: 10.132.0.4
    node_name: AIOT-WORKER-02
    node_net_dsp_name: default-ipv4
    node_net_name: DEFAULT-IPV4
    stlt_conn_encr_type: PLAIN
    stlt_conn_port: 3366
kind: List
metadata:
