apiVersion: v1
items:
- apiVersion: management.cattle.io/v3
  kind: Node
  metadata:
    annotations:
      cleanup.cattle.io/user-node-remove: "true"
      management.cattle.io/nodesyncer: "true"
    generateName: machine-
    labels:
      cattle.io/creator: norman
      management.cattle.io/nodename: aiot-master
    name: machine-5kjs5
    namespace: local
  spec:
    controlPlane: true
    customConfig: null
    desiredNodeTaints: null
    displayName: ""
    etcd: false
    imported: false
    internalNodeSpec:
      podCIDR: 10.244.0.0/24
      podCIDRs:
      - 10.244.0.0/24
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
    metadataUpdate:
      annotations: {}
      labels: {}
    nodePoolName: ""
    requestedHostname: aiot-master
    worker: false
  status:
    conditions:
    - lastTransitionTime: 2026-04-14 01:18:12 +0000 UTC
      lastUpdateTime: 2026-04-27 01:13:12 +0000 UTC
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastUpdateTime: "2026-04-19T20:51:53Z"
      message: registered with kubernetes
      status: "True"
      type: Registered
    internalNodeStatus:
      addresses:
      - address: 10.132.0.2
        type: InternalIP
      - address: aiot-master
        type: Hostname
      allocatable:
        cpu: "4"
        ephemeral-storage: "96385779143"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 16005000Ki
        pods: "110"
      capacity:
        cpu: "4"
        ephemeral-storage: 104585264Ki
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 16107400Ki
        pods: "110"
      conditions:
      - lastHeartbeatTime: "2026-04-27T01:13:12Z"
        lastTransitionTime: "2026-04-14T01:18:12Z"
        message: kubelet is posting ready status
        reason: KubeletReady
        status: "True"
        type: Ready
      daemonEndpoints:
        kubeletEndpoint:
          Port: 10250
      nodeInfo:
        architecture: amd64
        bootID: 0459e522-15a5-412b-bf78-045e057f9253
        containerRuntimeVersion: containerd://2.2.3
        kernelVersion: 5.14.0-691.el9.x86_64
        kubeProxyVersion: v1.32.13
        kubeletVersion: v1.32.13
        machineID: 048311148df146e994ed26a093959ea8
        operatingSystem: linux
        osImage: CentOS Stream 9
        systemUUID: 32b1e44f-62d4-4298-eac5-c2b8db897f41
      runtimeHandlers:
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: ""
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: runc
    limits:
      cpu: "7"
      memory: 5206Mi
    nodeAnnotations:
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"2a:4a:65:62:7e:2d"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.132.0.2
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    nodeLabels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: aiot-master
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
      node.kubernetes.io/exclude-from-external-load-balancers: ""
      workload-zone: control
    nodeName: aiot-master
    requested:
      cpu: 1785m
      memory: 2538Mi
      pods: "22"
- apiVersion: management.cattle.io/v3
  kind: Node
  metadata:
    annotations:
      cleanup.cattle.io/user-node-remove: "true"
      management.cattle.io/nodesyncer: "true"
    generateName: machine-
    labels:
      cattle.io/creator: norman
      management.cattle.io/nodename: oci-e5-node2
    name: machine-96d47
    namespace: local
  spec:
    controlPlane: false
    customConfig: null
    desiredNodeTaints: null
    displayName: ""
    etcd: false
    imported: false
    internalNodeSpec:
      podCIDR: 10.244.4.0/24
      podCIDRs:
      - 10.244.4.0/24
    metadataUpdate:
      annotations: {}
      labels: {}
    nodePoolName: ""
    requestedHostname: oci-e5-node2
    worker: true
  status:
    conditions:
    - lastTransitionTime: 2026-04-26 15:34:49 +0000 UTC
      lastUpdateTime: 2026-04-27 01:15:14 +0000 UTC
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastUpdateTime: "2026-04-19T20:51:53Z"
      message: registered with kubernetes
      status: "True"
      type: Registered
    internalNodeStatus:
      addresses:
      - address: 172.16.200.11
        type: InternalIP
      - address: oci-e5-node2
        type: Hostname
      allocatable:
        cpu: 7600m
        ephemeral-storage: "75755002134"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 10233108Ki
        pods: "110"
      capacity:
        cpu: "8"
        ephemeral-storage: 84824Mi
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 11769108Ki
        pods: "110"
      conditions:
      - lastHeartbeatTime: "2026-04-27T01:15:14Z"
        lastTransitionTime: "2026-04-26T15:34:49Z"
        message: kubelet is posting ready status
        reason: KubeletReady
        status: "True"
        type: Ready
      daemonEndpoints:
        kubeletEndpoint:
          Port: 10250
      nodeInfo:
        architecture: amd64
        bootID: 1e94e63c-c318-43b7-bd35-91b04086a91f
        containerRuntimeVersion: containerd://2.2.3
        kernelVersion: 6.12.0-201.74.2.1.el9uek.x86_64
        kubeProxyVersion: v1.32.13
        kubeletVersion: v1.32.13
        machineID: 18e71302b64b4451b5e153beadcc1b77
        operatingSystem: linux
        osImage: Oracle Linux Server 9.7
        systemUUID: 18e71302-b64b-4451-b5e1-53beadcc1b77
      runtimeHandlers:
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: ""
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: runc
    limits:
      cpu: 10900m
      ephemeral-storage: 5Gi
      memory: 20828Mi
    nodeAnnotations:
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"16:54:0e:22:4b:41"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 172.16.200.11
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    nodeLabels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      cloud: oci
      io.cilium.migration/cilium-default: "true"
      konflux.ci/role: build
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: oci-e5-node2
      kubernetes.io/os: linux
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: oci-frankfurt
      workload-zone: build
    nodeName: oci-e5-node2
    requested:
      cpu: 2875m
      ephemeral-storage: 1Gi
      memory: 4188Mi
      pods: "47"
- apiVersion: management.cattle.io/v3
  kind: Node
  metadata:
    annotations:
      cleanup.cattle.io/user-node-remove: "true"
      management.cattle.io/nodesyncer: "true"
    generateName: machine-
    labels:
      cattle.io/creator: norman
      management.cattle.io/nodename: aiot-worker-01
    name: machine-jnb26
    namespace: local
  spec:
    controlPlane: false
    customConfig: null
    desiredNodeTaints: null
    displayName: ""
    etcd: false
    imported: false
    internalNodeSpec:
      podCIDR: 10.244.6.0/24
      podCIDRs:
      - 10.244.6.0/24
    metadataUpdate:
      annotations: {}
      labels: {}
    nodePoolName: ""
    requestedHostname: aiot-worker-01
    worker: true
  status:
    conditions:
    - lastTransitionTime: 2026-04-26 19:48:20 +0000 UTC
      lastUpdateTime: 2026-04-27 01:14:05 +0000 UTC
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastUpdateTime: "2026-04-22T15:12:34Z"
      message: registered with kubernetes
      status: "True"
      type: Registered
    internalNodeStatus:
      addresses:
      - address: 10.132.0.3
        type: InternalIP
      - address: aiot-worker-01
        type: Hostname
      allocatable:
        cpu: 3600m
        ephemeral-storage: "140409193847"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 14571392Ki
        pods: "110"
      capacity:
        cpu: "4"
        ephemeral-storage: 157014064Ki
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 16107392Ki
        pods: "110"
      conditions:
      - lastHeartbeatTime: "2026-04-27T01:14:05Z"
        lastTransitionTime: "2026-04-26T19:48:20Z"
        message: kubelet is posting ready status
        reason: KubeletReady
        status: "True"
        type: Ready
      daemonEndpoints:
        kubeletEndpoint:
          Port: 10250
      nodeInfo:
        architecture: amd64
        bootID: e4f78675-10ed-4752-a91f-937bb4f7eff3
        containerRuntimeVersion: containerd://2.2.3
        kernelVersion: 5.14.0-691.el9.x86_64
        kubeProxyVersion: v1.32.13
        kubeletVersion: v1.32.13
        machineID: 048311148df146e994ed26a093959ea8
        operatingSystem: linux
        osImage: CentOS Stream 9
        systemUUID: 31ac02f6-908d-2e11-4319-bbbc15cdb3b8
      runtimeHandlers:
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: ""
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: runc
    limits:
      cpu: 6660m
      ephemeral-storage: 5Gi
      memory: 7412Mi
    nodeAnnotations:
      csi.volume.kubernetes.io/nodeid: '{"linstor.csi.linbit.com":"aiot-worker-01"}'
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"c2:d5:10:6d:8d:c7"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.132.0.3
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    nodeLabels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      io.cilium.migration/cilium-default: "true"
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: aiot-worker-01
      kubernetes.io/os: linux
      linbit.com/hostname: aiot-worker-01
      node-role.kubernetes.io/worker: ""
      piraeus.io/storage: "yes"
      workload-zone: data
    nodeName: aiot-worker-01
    requested:
      cpu: 1446m
      ephemeral-storage: 1Gi
      memory: 2775Mi
      pods: "37"
- apiVersion: management.cattle.io/v3
  kind: Node
  metadata:
    annotations:
      cleanup.cattle.io/user-node-remove: "true"
      management.cattle.io/nodesyncer: "true"
    generateName: machine-
    labels:
      cattle.io/creator: norman
      management.cattle.io/nodename: oci-e5-node1
    name: machine-mr29s
    namespace: local
  spec:
    controlPlane: false
    customConfig: null
    desiredNodeTaints: null
    displayName: ""
    etcd: false
    imported: false
    internalNodeSpec:
      podCIDR: 10.244.3.0/24
      podCIDRs:
      - 10.244.3.0/24
    metadataUpdate:
      annotations: {}
      labels: {}
    nodePoolName: ""
    requestedHostname: oci-e5-node1
    worker: true
  status:
    conditions:
    - lastTransitionTime: 2026-04-26 18:26:03 +0000 UTC
      lastUpdateTime: 2026-04-27 01:16:41 +0000 UTC
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastUpdateTime: "2026-04-19T20:51:53Z"
      message: registered with kubernetes
      status: "True"
      type: Registered
    internalNodeStatus:
      addresses:
      - address: 172.16.200.10
        type: InternalIP
      - address: oci-e5-node1
        type: Hostname
      allocatable:
        cpu: 7600m
        ephemeral-storage: "75755002134"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 10233112Ki
        pods: "110"
      capacity:
        cpu: "8"
        ephemeral-storage: 84824Mi
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 11769112Ki
        pods: "110"
      conditions:
      - lastHeartbeatTime: "2026-04-27T01:16:41Z"
        lastTransitionTime: "2026-04-26T18:26:03Z"
        message: kubelet is posting ready status
        reason: KubeletReady
        status: "True"
        type: Ready
      daemonEndpoints:
        kubeletEndpoint:
          Port: 10250
      nodeInfo:
        architecture: amd64
        bootID: 686ccc61-99d1-4a78-b29b-df835d6d3a19
        containerRuntimeVersion: containerd://2.2.3
        kernelVersion: 6.12.0-201.74.2.1.el9uek.x86_64
        kubeProxyVersion: v1.32.13
        kubeletVersion: v1.32.13
        machineID: f6e50a67da6e4469bfc08c323eb4d064
        operatingSystem: linux
        osImage: Oracle Linux Server 9.7
        systemUUID: f6e50a67-da6e-4469-bfc0-8c323eb4d064
      runtimeHandlers:
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: ""
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: runc
    limits:
      cpu: 4100m
      ephemeral-storage: 20Gi
      memory: 6388Mi
    nodeAnnotations:
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"42:d6:1c:3f:58:78"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 172.16.200.10
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    nodeLabels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      cloud: oci
      io.cilium.migration/cilium-default: "true"
      konflux.ci/role: build
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: oci-e5-node1
      kubernetes.io/os: linux
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: oci-frankfurt
      workload-zone: build
    nodeName: oci-e5-node1
    requested:
      cpu: 1635m
      ephemeral-storage: 8Gi
      memory: 3210Mi
      pods: "26"
- apiVersion: management.cattle.io/v3
  kind: Node
  metadata:
    annotations:
      cleanup.cattle.io/user-node-remove: "true"
      management.cattle.io/nodesyncer: "true"
    generateName: machine-
    labels:
      cattle.io/creator: norman
      management.cattle.io/nodename: aiot-worker-02
    name: machine-x6nhn
    namespace: local
  spec:
    controlPlane: false
    customConfig: null
    desiredNodeTaints: null
    displayName: ""
    etcd: false
    imported: false
    internalNodeSpec:
      podCIDR: 10.244.2.0/24
      podCIDRs:
      - 10.244.2.0/24
    metadataUpdate:
      annotations: {}
      labels: {}
    nodePoolName: ""
    requestedHostname: aiot-worker-02
    worker: true
  status:
    conditions:
    - lastTransitionTime: 2026-04-26 14:39:53 +0000 UTC
      lastUpdateTime: 2026-04-27 01:14:29 +0000 UTC
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    - lastUpdateTime: "2026-04-22T13:44:17Z"
      message: registered with kubernetes
      status: "True"
      type: Registered
    internalNodeStatus:
      addresses:
      - address: 10.132.0.4
        type: InternalIP
      - address: aiot-worker-02
        type: Hostname
      allocatable:
        cpu: 3600m
        ephemeral-storage: "140409193847"
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 14571392Ki
        pods: "110"
      capacity:
        cpu: "4"
        ephemeral-storage: 157014064Ki
        hugepages-1Gi: "0"
        hugepages-2Mi: "0"
        memory: 16107392Ki
        pods: "110"
      conditions:
      - lastHeartbeatTime: "2026-04-27T01:14:29Z"
        lastTransitionTime: "2026-04-26T14:39:53Z"
        message: kubelet is posting ready status
        reason: KubeletReady
        status: "True"
        type: Ready
      daemonEndpoints:
        kubeletEndpoint:
          Port: 10250
      nodeInfo:
        architecture: amd64
        bootID: 1e27e676-75e0-4e9a-9ecc-235dcfceb0aa
        containerRuntimeVersion: containerd://2.2.3
        kernelVersion: 5.14.0-691.el9.x86_64
        kubeProxyVersion: v1.32.13
        kubeletVersion: v1.32.13
        machineID: 048311148df146e994ed26a093959ea8
        operatingSystem: linux
        osImage: CentOS Stream 9
        systemUUID: 3ab7e681-5399-bc88-e01c-b0f40fd7a93d
      runtimeHandlers:
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: ""
      - features:
          recursiveReadOnlyMounts: true
          userNamespaces: true
        name: runc
    limits:
      cpu: 14150m
      ephemeral-storage: 10Gi
      memory: 16108Mi
    nodeAnnotations:
      csi.volume.kubernetes.io/nodeid: '{"linstor.csi.linbit.com":"aiot-worker-02"}'
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"86:3b:9d:76:60:f8"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.132.0.4
      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    nodeLabels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      io.cilium.migration/cilium-default: "true"
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: aiot-worker-02
      kubernetes.io/os: linux
      linbit.com/hostname: aiot-worker-02
      node-role.kubernetes.io/worker: ""
      piraeus.io/storage: "yes"
      workload-zone: data
    nodeName: aiot-worker-02
    requested:
      cpu: 2705m
      ephemeral-storage: 2Gi
      memory: 5360Mi
      pods: "45"
kind: List
metadata:
