apiVersion: v1
items:
- apiVersion: kubeflow.org/v1
  kind: Notebook
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kubeflow.org/v1","kind":"Notebook","metadata":{"annotations":{"notebooks.kubeflow.org/server-type":"jupyter"},"labels":{"app":"ml-workshop"},"name":"ml-workshop","namespace":"kubeflow-user-example-com"},"spec":{"template":{"spec":{"containers":[{"image":"kubeflownotebookswg/jupyter-scipy:v1.9.2","name":"ml-workshop","ports":[{"containerPort":8888,"name":"notebook-port","protocol":"TCP"}],"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"1","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/home/jovyan","name":"workspace"},{"mountPath":"/home/jovyan/shared-config","name":"config"}]}],"serviceAccountName":"default-editor","volumes":[{"name":"workspace","persistentVolumeClaim":{"claimName":"ml-workshop-workspace"}},{"name":"config","persistentVolumeClaim":{"claimName":"kubeflow-config"}}]}}}}
      notebooks.kubeflow.org/server-type: jupyter
    labels:
      app: ml-workshop
    name: ml-workshop
    namespace: kubeflow-user-example-com
  spec:
    template:
      spec:
        containers:
        - image: kubeflownotebookswg/jupyter-scipy:v1.9.2
          name: ml-workshop
          ports:
          - containerPort: 8888
            name: notebook-port
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - mountPath: /home/jovyan
            name: workspace
          - mountPath: /home/jovyan/shared-config
            name: config
        serviceAccountName: default-editor
        volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: ml-workshop-workspace
        - name: config
          persistentVolumeClaim:
            claimName: kubeflow-config
  status:
    conditions:
    - lastProbeTime: "2026-04-22T08:07:25Z"
      lastTransitionTime: "2026-04-20T08:33:24Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: "2026-04-22T08:07:25Z"
      lastTransitionTime: "2026-04-20T08:33:24Z"
      status: "True"
      type: Initialized
    - lastProbeTime: "2026-04-22T08:07:25Z"
      lastTransitionTime: "2026-04-20T12:14:05Z"
      status: "True"
      type: Ready
    - lastProbeTime: "2026-04-22T08:07:25Z"
      lastTransitionTime: "2026-04-20T12:14:05Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: "2026-04-22T08:07:25Z"
      lastTransitionTime: "2026-04-20T08:33:23Z"
      status: "True"
      type: PodScheduled
    containerState:
      running:
        startedAt: "2026-04-20T08:35:51Z"
    readyReplicas: 1
kind: List
metadata:
