apiVersion: v1
items:
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 1a413a0b-39e7-489a-9a97-1542d175721a
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-frontend-push-jwfgk-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1776937442
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-frontend-push-jwfgk-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 239dcb24-153b-48ca-b22f-3b92e47805fb
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-frontend-push-b7swr-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1776937341
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-frontend-push-b7swr-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 3cd1a6a2-2fad-4db4-9ba5-7fe1dbed133b
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-frontend-push-gqwgr-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1776938342
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-frontend-push-gqwgr-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: a9513bb5-9fc5-472e-aa0e-db1d075c67ca
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-backend-push-xtmbr-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1776937343
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-backend-push-xtmbr-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
kind: List
metadata:
