apiVersion: v1
items:
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 2a6dd828-0a8d-487e-abfe-60c0af8a3561
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-frontend-push-hsfr9-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1777008312
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-frontend-push-hsfr9-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 3cd1a6a2-2fad-4db4-9ba5-7fe1dbed133b
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-frontend-push-gqwgr-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1776938342
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-frontend-push-gqwgr-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: a89d74ea-8ea8-40d6-a1c6-8b8d9f5ebf4b
    namespace: default-tenant
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: hello-aiot-push-vpddp-build-and-push-pod
  results:
  - message: 0 elements processed
    policy: reduce-tekton-pr-taskrun-resource-requests
    properties:
      process: admission review
    result: skip
    rule: reduce-tekton-pr-taskrun-resource-requests
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1777039673
  scope:
    apiVersion: v1
    kind: Pod
    name: hello-aiot-push-vpddp-build-and-push-pod
    namespace: default-tenant
  summary:
    error: 0
    fail: 0
    pass: 0
    skip: 1
    warn: 0
kind: List
metadata:
