apiVersion: v1
items:
- apiVersion: k8up.io/v1
  kind: PreBackupPod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"PreBackupPod","metadata":{"annotations":{},"name":"pg-ha-dump","namespace":"aiot"},"spec":{"backupCommand":"sh -c 'PGPASSWORD=\"$POSTGRES_PASSWORD\" pg_dumpall -h pg-ha-rw -U postgres --clean --if-exists'","fileExtension":".sql","pod":{"spec":{"containers":[{"env":[{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"pg-ha-superuser"}}}],"image":"postgres:16-alpine","name":"pg-ha-dump"}]}}}}
    name: pg-ha-dump
    namespace: aiot
  spec:
    backupCommand: sh -c 'PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall -h pg-ha-rw -U
      postgres --clean --if-exists'
    fileExtension: .sql
    pod:
      spec:
        containers:
        - env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pg-ha-superuser
          image: postgres:16-alpine
          name: pg-ha-dump
kind: List
metadata:
