apiVersion: v1
items:
- apiVersion: appstudio.redhat.com/v1alpha1
  kind: ReleasePlanAdmission
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"ReleasePlanAdmission","metadata":{"annotations":{},"labels":{"release.appstudio.openshift.io/auto-release":"true"},"name":"hello-aiot-dev-rpa","namespace":"default-tenant"},"spec":{"applications":["hello-aiot"],"origin":"default-tenant","pipeline":{"pipelineRef":{"params":[{"name":"kind","value":"pipeline"},{"name":"name","value":"release-with-ec"},{"name":"namespace","value":"default-tenant"}],"resolver":"cluster"},"serviceAccountName":"release-service-account"},"policy":"hello-aiot-policy"}}
    labels:
      release.appstudio.openshift.io/auto-release: "true"
      release.appstudio.openshift.io/block-releases: "false"
    name: hello-aiot-dev-rpa
    namespace: default-tenant
  spec:
    applications:
    - hello-aiot
    origin: default-tenant
    pipeline:
      pipelineRef:
        params:
        - name: kind
          value: pipeline
        - name: name
          value: release-with-ec
        - name: namespace
          value: default-tenant
        resolver: cluster
      serviceAccountName: release-service-account
      timeouts: {}
    policy: hello-aiot-policy
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T18:02:36Z"
      message: ""
      reason: Matched
      status: "True"
      type: Matched
    releasePlans:
    - active: true
      name: default-tenant/hello-aiot-dev
kind: List
metadata:
