apiVersion: v1
items:
- apiVersion: pipelinesascode.tekton.dev/v1alpha1
  kind: Repository
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"pipelinesascode.tekton.dev/v1alpha1","kind":"Repository","metadata":{"annotations":{},"name":"hello-aiot","namespace":"default-tenant"},"spec":{"git_provider":{"secret":{"key":"provider.token","name":"hello-aiot-git-provider"},"type":"gitea","url":"https://gitea.35.241.255.137.nip.io","webhook_secret":{"key":"webhook.secret","name":"hello-aiot-git-provider"}},"url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot"}}
    name: hello-aiot
    namespace: default-tenant
  pipelinerun_status:
  - completionTime: "2026-04-23T05:44:05Z"
    conditions:
    - lastTransitionTime: "2026-04-23T05:44:05Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://localhost:9443/ns/default-tenant/pipelinerun/hello-aiot-push-d9kld
    pipelineRunName: hello-aiot-push-d9kld
    sha: aa97baa3ee4a29c8fff8dbb3d91e526bf93696b3
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot/commit/aa97baa3ee4a29c8fff8dbb3d91e526bf93696b3
    startTime: "2026-04-23T05:42:34Z"
    target_branch: main
    title: |
      chore: cleanup trigger files
  - completionTime: "2026-04-23T05:52:18Z"
    conditions:
    - lastTransitionTime: "2026-04-23T05:52:18Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://localhost:9443/ns/default-tenant/pipelinerun/hello-aiot-push-pfs4p
    pipelineRunName: hello-aiot-push-pfs4p
    sha: cd6ee3ffd96b3542d398183fbbecd4b34b028cbc
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot/commit/cd6ee3ffd96b3542d398183fbbecd4b34b028cbc
    startTime: "2026-04-23T05:50:51Z"
    target_branch: main
    title: |
      chore: e2e auto-release test 1776923447
  - completionTime: "2026-04-23T07:21:21Z"
    conditions:
    - lastTransitionTime: "2026-04-23T07:21:21Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-push-w9b6d
    pipelineRunName: hello-aiot-push-w9b6d
    sha: 2ff6059f7196209f85d3232be2cb07b5acaee11d
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot/commit/2ff6059f7196209f85d3232be2cb07b5acaee11d
    startTime: "2026-04-23T07:19:53Z"
    target_branch: main
    title: |
      chore: e2e auto-release test 1776928787
  - completionTime: "2026-04-23T07:29:33Z"
    conditions:
    - lastTransitionTime: "2026-04-23T07:29:33Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-push-fxzbt
    pipelineRunName: hello-aiot-push-fxzbt
    sha: ff42065c6fc9bac5e1b28e3a807da34b856c5ba3
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot/commit/ff42065c6fc9bac5e1b28e3a807da34b856c5ba3
    startTime: "2026-04-23T07:28:04Z"
    target_branch: main
    title: |
      chore: e2e auto-release test 1776929279
  - completionTime: "2026-04-24T14:09:25Z"
    conditions:
    - lastTransitionTime: "2026-04-24T14:09:25Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-push-vpddp
    pipelineRunName: hello-aiot-push-vpddp
    sha: 047105e6800d5bd3ab93e913068b89ee1bb10d56
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot/commit/047105e6800d5bd3ab93e913068b89ee1bb10d56
    startTime: "2026-04-24T14:07:52Z"
    target_branch: main
    title: |
      fix: use port-less registry hostname so snapshot.containerImage parser is not confused by host:port
  spec:
    concurrency_limit: 2
    git_provider:
      secret:
        key: provider.token
        name: hello-aiot-git-provider
      type: gitea
      url: https://gitea.35.241.255.137.nip.io
      webhook_secret:
        key: webhook.secret
        name: hello-aiot-git-provider
    url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot
- apiVersion: pipelinesascode.tekton.dev/v1alpha1
  kind: Repository
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"pipelinesascode.tekton.dev/v1alpha1","kind":"Repository","metadata":{"annotations":{},"name":"hello-aiot-backend","namespace":"default-tenant"},"spec":{"concurrency_limit":2,"git_provider":{"secret":{"key":"provider.token","name":"hello-aiot-backend-git-provider"},"type":"gitea","url":"https://gitea.35.241.255.137.nip.io","webhook_secret":{"key":"webhook.secret","name":"hello-aiot-backend-git-provider"}},"url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend"}}
    name: hello-aiot-backend
    namespace: default-tenant
  pipelinerun_status:
  - completionTime: "2026-04-23T09:44:17Z"
    conditions:
    - lastTransitionTime: "2026-04-23T09:44:17Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-backend-push-xtmbr
    pipelineRunName: hello-aiot-backend-push-xtmbr
    sha: 1b379d5682904b065dce66fcac339a5d7601683b
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend/commit/1b379d5682904b065dce66fcac339a5d7601683b
    startTime: "2026-04-23T09:42:23Z"
    target_branch: main
    title: |
      chore: first build trigger 1776937340
  spec:
    concurrency_limit: 2
    git_provider:
      secret:
        key: provider.token
        name: hello-aiot-backend-git-provider
      type: gitea
      url: https://gitea.35.241.255.137.nip.io
      webhook_secret:
        key: webhook.secret
        name: hello-aiot-backend-git-provider
    url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-backend
- apiVersion: pipelinesascode.tekton.dev/v1alpha1
  kind: Repository
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"pipelinesascode.tekton.dev/v1alpha1","kind":"Repository","metadata":{"annotations":{},"name":"hello-aiot-frontend","namespace":"default-tenant"},"spec":{"concurrency_limit":2,"git_provider":{"secret":{"key":"provider.token","name":"hello-aiot-frontend-git-provider"},"type":"gitea","url":"https://gitea.35.241.255.137.nip.io","webhook_secret":{"key":"webhook.secret","name":"hello-aiot-frontend-git-provider"}},"url":"https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend"}}
    name: hello-aiot-frontend
    namespace: default-tenant
  pipelinerun_status:
  - completionTime: "2026-04-23T09:42:33Z"
    conditions:
    - lastTransitionTime: "2026-04-23T09:42:33Z"
      message: 'Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0'
      reason: Failed
      status: "False"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-frontend-push-b7swr
    pipelineRunName: hello-aiot-frontend-push-b7swr
    sha: 99d52464ec791b4f984ea0c34a84cdc2ba863648
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend/commit/99d52464ec791b4f984ea0c34a84cdc2ba863648
    startTime: "2026-04-23T09:42:20Z"
    target_branch: main
    title: |
      chore: first build trigger 1776937338
  - completionTime: "2026-04-23T09:45:21Z"
    conditions:
    - lastTransitionTime: "2026-04-23T09:45:21Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-frontend-push-jwfgk
    pipelineRunName: hello-aiot-frontend-push-jwfgk
    sha: 6a60509a2ce71a66930ef8870eb704a5a829b99a
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend/commit/6a60509a2ce71a66930ef8870eb704a5a829b99a
    startTime: "2026-04-23T09:44:02Z"
    target_branch: main
    title: |
      fix: qualify nginx image FQN
  - completionTime: "2026-04-23T10:00:20Z"
    conditions:
    - lastTransitionTime: "2026-04-23T10:00:20Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-frontend-push-gqwgr
    pipelineRunName: hello-aiot-frontend-push-gqwgr
    sha: 546a482358e22e13a6857ae02f670c14103d1aea
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend/commit/546a482358e22e13a6857ae02f670c14103d1aea
    startTime: "2026-04-23T09:59:02Z"
    target_branch: main
    title: |
      test finalizer fix
  - completionTime: "2026-04-24T05:26:29Z"
    conditions:
    - lastTransitionTime: "2026-04-24T05:26:29Z"
      message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: "True"
      type: Succeeded
    event_type: push
    logurl: https://konflux.35.241.255.137.nip.io/ns/default-tenant/applications/hello-aiot/pipelineruns/hello-aiot-frontend-push-hsfr9
    pipelineRunName: hello-aiot-frontend-push-hsfr9
    sha: 06274a33272a899952c3597102471ad66e01729a
    sha_url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend/commit/06274a33272a899952c3597102471ad66e01729a
    startTime: "2026-04-24T05:25:12Z"
    target_branch: main
    title: |
      rollback demo: only frontend change
  spec:
    concurrency_limit: 2
    git_provider:
      secret:
        key: provider.token
        name: hello-aiot-frontend-git-provider
      type: gitea
      url: https://gitea.35.241.255.137.nip.io
      webhook_secret:
        key: webhook.secret
        name: hello-aiot-frontend-git-provider
    url: https://gitea.35.241.255.137.nip.io/aiot/hello-aiot-frontend
kind: List
metadata:
