apiVersion: v1
items:
- apiVersion: core.k8sgpt.ai/v1alpha1
  kind: Result
  metadata:
    labels:
      k8sgpts.k8sgpt.ai/backend: openai
      k8sgpts.k8sgpt.ai/name: k8sgpt
      k8sgpts.k8sgpt.ai/namespace: k8sgpt
    name: buildservicebuildservicecontrollermanagermetricsservice
    namespace: k8sgpt
    ownerReferences:
    - apiVersion: core.k8sgpt.ai/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K8sGPT
      name: k8sgpt
  spec:
    autoRemediationStatus: {}
    backend: openai
    details: |-
      Error: Service has no endpoints, missing label control-plane=controller-manager.
      Solution: 1. Check service & pod labels. 2. Add missing label.
    error:
    - sensitive:
      - masked: MTYlWVAsI11DcyV5QA==
        unmasked: control-plane
      - masked: ZmdfRnF3SHJdU3spMzhreFRv
        unmasked: controller-manager
      text: Service has no endpoints, expected label control-plane=controller-manager
    kind: Service
    name: build-service/build-service-controller-manager-metrics-service
    parentObject: ""
  status:
    contentHash: fbcb4e81e60fda4173bd3f013372ecfad22b5fd0a82f853519145a4d3a7d5233
    lifecycle: historical
- apiVersion: core.k8sgpt.ai/v1alpha1
  kind: Result
  metadata:
    labels:
      k8sgpts.k8sgpt.ai/backend: openai
      k8sgpts.k8sgpt.ai/name: k8sgpt
      k8sgpts.k8sgpt.ai/namespace: k8sgpt
    name: konfluxoperatorkonfluxoperatorcontrollermanagermetricsservice
    namespace: k8sgpt
    ownerReferences:
    - apiVersion: core.k8sgpt.ai/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K8sGPT
      name: k8sgpt
  spec:
    autoRemediationStatus: {}
    backend: openai
    details: |-
      Error: Service has no endpoints.
      Solution: 1. Check labels, 2. Verify pod status, 3. Update service config.
    error:
    - sensitive:
      - masked: dmsxX2NiVDJRUUE6eQ==
        unmasked: control-plane
      - masked: SE5JQGVITE5RMSw8XW1uKjRI
        unmasked: controller-manager
      text: Service has no endpoints, expected label control-plane=controller-manager
    - sensitive:
      - masked: Jm85OVJvNi48TUVfKU50Ykh3WWEzOA==
        unmasked: app.kubernetes.io/name
      - masked: YW0xbyl5XnIvOXMqSU5AdQ==
        unmasked: konflux-operator
      text: Service has no endpoints, expected label app.kubernetes.io/name=konflux-operator
    kind: Service
    name: konflux-operator/konflux-operator-controller-manager-metrics-service
    parentObject: ""
  status:
    contentHash: e9c347527ddbe92d63b80ef7c07bf91ec33bcbf4f23be298d7e18e791d03a2fe
    lifecycle: updated
- apiVersion: core.k8sgpt.ai/v1alpha1
  kind: Result
  metadata:
    labels:
      k8sgpts.k8sgpt.ai/backend: openai
      k8sgpts.k8sgpt.ai/name: k8sgpt
      k8sgpts.k8sgpt.ai/namespace: k8sgpt
    name: tektonpipelinestektonresultspostgres
    namespace: k8sgpt
    ownerReferences:
    - apiVersion: core.k8sgpt.ai/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K8sGPT
      name: k8sgpt
  spec:
    autoRemediationStatus: {}
    backend: openai
    details: |-
      Error: Service 'tekton-pipelines/postgres' doesn't exist.
      Solution: 1. Create service. 2. Apply config.
    error:
    - sensitive:
      - masked: VjBEbzpIVXBzVVd5c1pfMQ==
        unmasked: tekton-pipelines
      - masked: WGI4bzJfTTk=
        unmasked: postgres
      text: StatefulSet uses the service tekton-pipelines/postgres which does not
        exist.
    kind: StatefulSet
    name: tekton-pipelines/tekton-results-postgres
    parentObject: ""
  status:
    contentHash: b6f79b25a4e7abca56401ab1ed5728405285983e30557d5e2e26a22dfea085f3
    lifecycle: historical
kind: List
metadata:
