apiVersion: v1
items:
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"aiot"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"10 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"10 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: aiot
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 10 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 10 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T06:02:55Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"backrest"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: backrest
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:03Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"gitea"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: gitea
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:03Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"inference"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: inference
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:04Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"jenkins"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"0 3 * * *"},"check":{"schedule":"0 5 * * 0"},"prune":{"retention":{"keepDaily":2},"schedule":"0 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: jenkins
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 0 3 * * *
    check:
      resources: {}
      schedule: 0 5 * * 0
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 0 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T06:02:54Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"kubeflow-user-example-com"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: kubeflow-user-example-com
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:05Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"kubeflow"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: kubeflow
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T06:02:55Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"mlflow"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"15 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"15 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: mlflow
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 15 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 15 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T06:02:55Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"semaphore"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"5 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"5 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: semaphore
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 5 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 5 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T06:02:55Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"signoz"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: signoz
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:06Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
- apiVersion: k8up.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8up.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"aiot","namespace":"victoriametrics"},"spec":{"backend":{"repoPasswordSecretRef":{"key":"password","name":"k8up-repo"},"s3":{"accessKeyIDSecretRef":{"key":"access_key","name":"r2-creds"},"bucket":"aiot-velero","endpoint":"https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com","secretAccessKeySecretRef":{"key":"secret_key","name":"r2-creds"}}},"backup":{"keepJobs":2,"schedule":"20 3 * * *"},"prune":{"retention":{"keepDaily":2},"schedule":"20 4 * * *"}}}
    finalizers:
    - k8up.io/schedule
    name: aiot
    namespace: victoriametrics
  spec:
    backend:
      repoPasswordSecretRef:
        key: password
        name: k8up-repo
      s3:
        accessKeyIDSecretRef:
          key: access_key
          name: r2-creds
        bucket: aiot-velero
        endpoint: https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com
        secretAccessKeySecretRef:
          key: secret_key
          name: r2-creds
    backup:
      keepJobs: 2
      resources: {}
      schedule: 20 3 * * *
    prune:
      resources: {}
      retention:
        keepDaily: 2
      schedule: 20 4 * * *
    resourceRequirementsTemplate: {}
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T08:24:07Z"
      message: The resource is ready
      reason: Ready
      status: "True"
      type: Ready
kind: List
metadata:
