apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecIdentities
  metadata:
    name: d621c1a7169f2ca51bc8674da52e9572178a66a1dde88da24da78fe4951703f9
  spec:
    id_enabled: true
    id_locked: true
    identity_dsp_name: SYSTEM
    identity_name: SYSTEM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecIdentities
  metadata:
    name: d9262e7fb868c502061473089e5212378ac3935e2f96294266da6d7eec7d44e0
  spec:
    id_enabled: true
    id_locked: true
    identity_dsp_name: PUBLIC
    identity_name: PUBLIC
kind: List
metadata:
