apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 0f5443147fb6c7c0c50298f2af1d388c5d241e89e2287979d012c6c9396e31fb
  spec:
    access_type: 15
    domain_name: SYSADM
    type_name: SYSTEM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 117d75a33198f269e4581a9a36a6b0f34de77b3737640c29a54be0f16f1c80d6
  spec:
    access_type: 15
    domain_name: USER
    type_name: USER
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 17bfe1256a940559e9be741f7d61b920977d2c95746de0f597bed64dc895cf98
  spec:
    access_type: 15
    domain_name: SYSTEM
    type_name: SHARED
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 2d1fd80aa36cb68f64d86de9fb1e1c97a72b11a8fbc5a5cbe93d948a1d6aedd1
  spec:
    access_type: 3
    domain_name: PUBLIC
    type_name: SYSTEM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 45d720dcc68825de0e2dd009633696aa1126619d1b91bd2230b9eb3b4491899d
  spec:
    access_type: 15
    domain_name: SYSADM
    type_name: SYSADM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 4a2e1a2c9837d47a3f5e35e9d8138c80c71dce23ae5642c755305b97aa6637ce
  spec:
    access_type: 15
    domain_name: SYSTEM
    type_name: USER
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 58a9d4ceb8dc308622375aaa918fcb7fcd04107c8dedbc091b841965a8502ad3
  spec:
    access_type: 3
    domain_name: USER
    type_name: SYSTEM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 6317e017b63311649c2aff77a7e848d94c83e6c7eefccc72c01cac73c564ac4f
  spec:
    access_type: 7
    domain_name: USER
    type_name: SHARED
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 632301253e925ab2ce9cd68f8d87c8fad31e4aaf9eed67beb8bf8c58880615f6
  spec:
    access_type: 15
    domain_name: SYSADM
    type_name: SHARED
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 6af6ca4f988a53e70e6f978d967ec8b6953b80c14ff9dda0cf92459eeb9a8c8c
  spec:
    access_type: 3
    domain_name: USER
    type_name: SYSADM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 710630db15a3ac7ab529b2a76cf07d0b3837673afae87f7af50c0bb163635b8b
  spec:
    access_type: 15
    domain_name: SYSADM
    type_name: USER
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 748dd42b0d8c8107d9efd91473378304968c191088e6dae068fa3de143affaf6
  spec:
    access_type: 15
    domain_name: SYSADM
    type_name: PUBLIC
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 84855b10c7d0ec7e39ba976217682764f36f0710b5d23f368edfbc6908be3612
  spec:
    access_type: 7
    domain_name: USER
    type_name: PUBLIC
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 984ad0ab37275be5d2ec2d0b619f6e1ac0f8a2b8063810db62553a4b8f124d34
  spec:
    access_type: 3
    domain_name: PUBLIC
    type_name: USER
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: 9867e1b71d3a1251498107f3347c6c67275fbee2c9856c785034f1bed1d2d47e
  spec:
    access_type: 7
    domain_name: PUBLIC
    type_name: SHARED
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: d26038dc766da4dcd114dae95457a55ecb66e3af814c8b19974d048f67b26f0c
  spec:
    access_type: 15
    domain_name: SYSTEM
    type_name: PUBLIC
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: d45c0fcd05bfa6eeb06774806da3bdd85df1f837d9e81f1065d1acd6419e2c78
  spec:
    access_type: 15
    domain_name: SYSTEM
    type_name: SYSTEM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: e12a3ea196f55d06254b2acedc9a7d587ca4d1dd3f0fc16e13f5f83431d4bcf5
  spec:
    access_type: 15
    domain_name: SYSTEM
    type_name: SYSADM
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: e242db1bf68757cc159ba45d43c7dec786531c47f0d893f2047c0b8453e294ef
  spec:
    access_type: 15
    domain_name: PUBLIC
    type_name: PUBLIC
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SecTypeRules
  metadata:
    name: f82532cbed710629253dca93cf66f6e7aee0f4fff93b6e95bae795811f858126
  spec:
    access_type: 3
    domain_name: PUBLIC
    type_name: SYSADM
kind: List
metadata:
