apiVersion: v1
items:
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: auth
  nextRotation: "2026-04-22T14:33:56.71877584Z"
  signingKey:
    alg: RS256
    d: kTgykEusLT09KnbajtkWuBcFJKmlfX8TkuD-6iHOkOsw4MLhN8qLPXW2iuzYwnXUjGqOwBGNqHV1r3XYXMRtrl_7yKMOFaidXdD0WCd8aNQCECYAuIkfmq2Mu9UanqclHKvRbyTNw5-z9NmmnSItWKanBntV_Xdqkck-5LazHgByK4mPXVCzu_ECW4keIAGyZicBPDo1Xwio5kpSYMyc6f3ygFSliKQ0tI1KvcgplOivi_rqmZzT74RgPLJnHkNqNWn3SSmn45y8NPKdcYLYw1eH6bVcSvhmSfyQnF4miRpDsUWesTmZEuGBJWtEL7e16PPgu6F5OGxtqACqqP8lAQ
    dp: f8HxFakmeYjVRO4I5uY370cogTfxRp2Elu4CgzczDSmysogS6JoqFKiJGxZmFauLpbOaKLXdV_MFaZ2x5AZ9JHmlRk5TIaiCJ6KmlJV664TDAUwDHAG7DMDDKqIez8i1MsrdMV0j1kFEIiAReeDNsmKSUyC0tgX8U1yM00gU8JU
    dq: 4Q2GBXQAuaCQEtvjT_kE7LehwAIRSf2uo9FaB39quh7_UzYFI04Gjaf9vSI3FO06iWIn50BbBSdqMzihozheGKmkvbFu5PHrLMmFElX8ZHd7bDUQmajp42CGVM2pnun3zA1mCFvniM0Q5Hj9HhGApwGdCiL1Abxl6UpIpfQbdkE
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    p: znocslHOIZ5uRk9qvYy6rGDKRakvrFt1UWkQenvWlrjh-6LhEGbX_KH6euLvlImBm7TSzpNLz-Wevs_vi-Sb2YiHzkam52vLP8kkHK_T3ZRNiX-ByjSh1NsC60uIMMi8TVkFIknIIDQVw3WQsCxj_k9PEaOJyWJNcbjnW_FHhk0
    q: _8DRv9sYMzbvtMRN7mw-6vzuJQDLwK1EjfFpoGOoXLsDw-a3ew49ZkczHcAUIbhsIQwf00qBl2i23XM7kAC3Uc9_DTGRrGzYlZlcEvopVF42wjy60zd6LD3MlX1KJMDlyryZDGlLNaKgrsPN_o49Pk7ERqJXU_vzNIzi48el6mE
    qi: MWC91pRflqg6MhqOEGYx6yyioP8RgK8ip9xSnPxggdmC6UaOC9gIzYxd4YTtXZdQ8huQYj-raHiePg7VNXjZbfUf11hZ720hw6Df2a9K_SJjzkOXKK956-2OzFdQyshbsOy0DoiocZoO_S1huDU2mRCbrLRsYKbtIgj74AUNbbM
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    use: sig
  verificationKeys:
  - expiry: "2026-04-22T14:33:53.436142451Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 2daf9e9f8f6c5ca54c39dfa708b05cfa2c82c590
      kty: RSA
      "n": wUyzyuMIvtt_SdTEPFxvLYL75MbL1u3QkS_J0yThV0IrrwgUuoqmRMrCEj8Hbn485mA_WDY9UV3kZbAwfDwbG4920QmnymsWF1uvXzj2wJy9OjA5CLeHwk363Nv8J2JRfcS6kEMJwMxgC2_U4eaUNMioJCWVxbNohBkSWFakPbQ3Zi9B55DcKl7xbechX1wrUkakGlKM_T8uPRlF9cbjyBW2_EftcvpA_NM-qV1jrJ8mrFac3-iVIk2Ak3gaVlvjm1fEVg3RQ65njoYd6HJLfOIS46ODTDMGXTsJInuL6kbH8oc-KdXaxyJwleYyxNlgp90q22Resn5CBmU6PkpBzw
      use: sig
  - expiry: "2026-04-22T20:33:55.641873055Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 8846ee1a696063c208bddb570aaf5c3aed010a10
      kty: RSA
      "n": qz_woWQax5YS9GQQvSX_GcaU2XmLdDqQrhMwHAleJYrrrhmIe9Fib3XPLaFAbeJxS-dlQVS-lkURisYSMTD18Mu17eqIinpkVgEB6rALa4OazrzSg_F-zwMCIHiYYk90zXLzwbawLN_IlW98vKqMqzVIoAkm5ddE2qKlQjPcPT8qYscokmo7TrmIROFtpgV-BBfC31x8h_uOs3PuJJ-UIFtzwOT6Crr8KNFY8fkeLRSdlMGuaOkw4QLCGlZfEWniN3Wa4zYsZkLjqca1XIn-ztP4esp89Xyi5N2wYLCV12DmZYYxHpqPLVyTLqpBr0TMejRhPpXHVAdfHW0Dm7adDQ
      use: sig
  - expiry: "2026-04-23T02:33:56.203319721Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: e0ec805243b2a2e8e483ef77c1743cac7803cc91
      kty: RSA
      "n": tea2ogpKQ1QxhoogBsoZYVZJ8efHHMAHcAh2ohnMl5DZmCGZl2eqolHBOnPDlC8ibo59Bri1TCXu0E1V90aHQ0RA7txBj0mMxh3jOqyfdkA8tV31xdmpOYobV9LjaeXDUYlB_x1mEaDPtNz66NReW77gLoPF6oHKc5bRqc3wO1D5Q98qBFtdjPm1aY6I4VTlt9R_tTGqFwYBZ_UxwqDPVPd6Zba06kc41FW-oGFl0h9Jz-A6Vimabklf2h5v0ZvI1C4EqBzsAWF2Z6UZqELF6zlEM4qmGgcBppygrVpzzqEqiAxGa97x966DI9Oh8CLeMTwaaC-IndkRsI_8kQd1IQ
      use: sig
  - expiry: "2026-04-23T08:33:56.718775209Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 5b7c73f58a70e3ba11e00bb62ce361e47230a733
      kty: RSA
      "n": v0jhHk_JIexoU_qeG4XZUPqkKd8_vuV5gGibHGfo0hPy4IfBSZvD5gCnBDSlLqdqxpYSz3pCzG9Shh7RZUzvQUcotlGKYHr3nmRqHtrzVT4tF9Bgtigi10jRQstZO8LS7yDaMKvv-qdsPTFZF0Y5D2LmGSRgz4zOI2jtqNTxGUlb3uRrYxgg64qYuAWx4pyZgFe5azQzPRcEbqqhoT_7vDI28aC0YVy6-qSUtBxfL2kjGXVMPsjIAnGagPpj6EJ9I-Z0R8dz4-p7fx3pyK12SFnH9-7ZDLIMpVVUVCsNn6o4YG4gtOEHKx54GZ7527704b_AKmZjVKPPI4BlGmwCGw
      use: sig
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: konflux-ui
  nextRotation: "2026-04-26T06:06:40.811629958Z"
  signingKey:
    alg: RS256
    d: D-4xhTsLsHyNeKegumA92kL1QpjphZEep28PfPlN-4YKI3xMJx9DmM8PzmuqY6kRmB-Zg8FzYCZdNxeEUK1lrwzvy6vg9q-rWEszkO4eoc_lzaj6Ae84mWRMQL_XSRPQoV-rQuB5Kzj6Tq6X17wVbeskvNl3AqRayRhLrBhzWeKKDEVC9DpVLX5KkehIEw5kusmcoV0-P51xdeDKHvecz6jSfLsi7box-Z2BrNic6fonw0R59M6eOumlQiLQ1pGLl8u6KQ1nHDxw8U1wAFzWL7pb88WOB8A6BY6_uOpshits9m64d1kb4jdv6s6bF7weniOFZLIxXGmuW0N2emZK2w
    dp: ah3VZojwz0acoU0CcKvjf-3GIt8HPSx84mtEK5RDtpljcyR4tPXPG1hWw81hOKuusjspKnAvWrYsGSgV1jzTEx9WdVBkOcBjtMiVI0gPe9IbECY5QyedQadRKrv_-XYnNUz0b0NOkydh5oPi_8vq7EQiCajAbNyQdRIxF0mfADc
    dq: KkgZWMRio8q9UpP7zWUOIzA40DkC56e9qJhec3_4Vr0CbaZByVfHr9Q5TdyLowGjf6zZ02GvcsuLtTeyTVOP7hkjH5iSAsWI_tIbcvCsi5abYoyYK7opqtZ5yqx7K4LxdYLTefqPtde216Y9EyRXALtDitXdADii8KQG6C-5eC8
    e: AQAB
    kid: e070733ad822aba2f7959fb6cbb0fa6e95ca8c83
    kty: RSA
    "n": xqm3tiPeP57xVTzMKjuCRIoRSnTAL3A_8CUMDt3k40tvR9QkE92pz64JZVSyglGxo-xDcgooevUt4CD6lnWoqRA6fCImOmECDwo1TtEGRBjTI22Drkfqjqox2Fy2NfqFK5kNXnck0R8DESMdA8COBuV6iVm8k7l5nR37KFNUjC1iv8exzOY8gODWgFgH-XV3zy4M2wybKo93sho-xUTCvA04eJPEpoFW4r6V6bYGpWjUJwZhudowUacstgQPSOW-x1NnRoqK5PPqb5PtR4LWlM2u2dIJNUm8yhjsmWMqn0YRTwcQB52fyJw2GEhjklLRQVEQ1loEGXEKjJTTkoqmUQ
    p: 4xZwvCsHELjN1feOGFg9sHKr_Luhk4uw2Jq7wRvwV5R8DgJjtB6g7IbeNHrsB8PO_2wJk4abL_gqdYPTA3l-t2dob82F_ZS6_O9BgoFW9agAfKm0BsuEIKOYmOp7JJseXUXsH6mU1tBerN27TTRo5H-uQx03Tzpu8KZMiEcBXHc
    q: 3_TR0RGtiFCh0yEXbdyxXI4EhQjREVTA7CidqB3fkokI48WkVYY9HF1LgBcJ3CZJj2k9pBV-XXUjQFBEoUG3qPUptLkA9XWT4Vwjm9ymhS-g2VReb9Eae8WVeBzBk9V7IwjQU2HhA7EPcUKItUaJMsI0OWHhy0YaDgGv7uxGbXc
    qi: CyQ4yrBQ0RZROy8dNTCDJRjAv21p-84O1SvzgwqgqUKt3O5637eIDs3WavVbss6e2UMePDXSZgp_7zJ3WyXaATjHo_6-Awd8D8wgq8VF8oMx1OQ-kfbQbbgw4v3D_tZkUeYEjpjHGgGSAl26PFa9cjC-VESMoxXOcd2qjDlZHqM
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: e070733ad822aba2f7959fb6cbb0fa6e95ca8c83
    kty: RSA
    "n": xqm3tiPeP57xVTzMKjuCRIoRSnTAL3A_8CUMDt3k40tvR9QkE92pz64JZVSyglGxo-xDcgooevUt4CD6lnWoqRA6fCImOmECDwo1TtEGRBjTI22Drkfqjqox2Fy2NfqFK5kNXnck0R8DESMdA8COBuV6iVm8k7l5nR37KFNUjC1iv8exzOY8gODWgFgH-XV3zy4M2wybKo93sho-xUTCvA04eJPEpoFW4r6V6bYGpWjUJwZhudowUacstgQPSOW-x1NnRoqK5PPqb5PtR4LWlM2u2dIJNUm8yhjsmWMqn0YRTwcQB52fyJw2GEhjklLRQVEQ1loEGXEKjJTTkoqmUQ
    use: sig
  verificationKeys:
  - expiry: "2026-04-26T06:05:48.014905658Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 1e64706ecdfc6a52267389486ff63d2db8bdfaa1
      kty: RSA
      "n": 1_94IOb_ZzezlxT7E7aVuF3y5VwycUNUQqKPqAeA1-0Zf83FtfRHrJ4Ixtgkn2tq-q04TVJofzA8c7Z0kxzQ9WqxMHdtY9vNn93zlAotgt51FE-i2qxt4FFL5OgPPC5dMX6ruRvQNL3sIj5MdI-w5FdgPsvxplit7ZOvLsvsaOOVPjAjRKyCMMZBjEnwftX-yk_lVtkiDVIXA2M4gzaZ-MpofDGvpec4ZY9F8d680Vt4_0vY_gAtXz8zx06xSOnMW8Fnyjm0ghW42NzO-tIRuCTkR5mfoMAjhwa7czcS0-1KhR36sEEVcK0fpd1UvqFkB_Tu92iqOMtybDGYTzQEyw
      use: sig
  - expiry: "2026-04-26T12:05:59.912241489Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 17c6783c108af89ef26f02fa73bd31ec29bd9c7f
      kty: RSA
      "n": mJysECXbEQXEuzvx3xQvdYZV0nS3NtXOJzIznG3iPaMyjrZyGtwy0k7hsu2MXuaPL9OhiZ9sEQnvEiibxS4mAjikRIYpDBHgaF7aCQzDnElEGGCcQOCXCQevoLez-ewczglZlm8e9jBjlOjs0WkgOri_b6O1obtasW_XEg2RbNyI9btYltC5Cs9ys1OdXF2Bwx_4OO0RuUU0g6jQzaYHHiThGnobsq0wuyG9CUGimSgu_7l7iDwj7pnsSashivUxlu_z_kh6WSLEy-lx92H3AkamgKLLn3jP574nm23G3Y9eiAZ9oRpP0UOHJoSKgmgDv_Hhrs-FBvr2gHRITUWr5w
      use: sig
  - expiry: "2026-04-26T18:06:11.612237193Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: df5b94384e3711590367079ba6f66b06c6b4a79f
      kty: RSA
      "n": r_nDzlTrldkJPzZ-OZvWypBNjFlxEy4SKxYCXTK1YB0ee6o7BwlVNbgK06wBU6rAhd-3cQP6hxQz7YUOd5-AFY1abzM27t5WHutqBA-S8ZTJNHnqE5I4jc1qDRsnXhNo8rP_fwkzLdArKf38iEQMnQG6__s-GxXFQB4HWvy2vd_Wnl4a1L4-cv5iavHzeHsoOwRTcYsR8QrDh0IimTQxqO7tXE_YTH6XvSptNxXH2vih0mCCACQ8ZjbbdPFrpU5Wm_dnSk5iRK4fW5mKkjo57mfze7LHCQMDrGCvc9VEIz4fWTNgM8MMcBAH_4EO01KBu0t7qs7ug61VvtFRTvWtrw
      use: sig
  - expiry: "2026-04-27T00:06:40.811628933Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 789ce6c2b0d836c07cd40188afff164615819b62
      kty: RSA
      "n": 2IKdRfadk1tCZOd4Yhensx6AfKKmp9t3YCC9TXymXutZ8MdgmES76Fi8SWdsQTNHR3LercDq5CkXa3L7CHpu3MLnJuEkv3t5XVYjBhCG1hTM-oFLcH_s2VCadt2Yoe4h_gkI3cWHRXedEY76_t8LrAZyvq7uS42p0N_lQCFf23c-gd1bs_iElnil1S7WSuzGAGnNIzJZXi2dfTruEBvlxGe4Rz5mR2xlPj2rVlHEAaA4pcyQ7PBsDOgN9bpnYBHS1SYLFgDUc6B9Ld4HPWkTvdtqsA_YNPgf3iIxyLAhpwGemkPeVBvLhX1H_Oc-g27ZOo3YgLfodAVSnmCON1Eckw
      use: sig
kind: List
metadata:
