apiVersion: v1
items:
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: auth
  nextRotation: "2026-04-22T14:33:56.71877584Z"
  signingKey:
    alg: RS256
    d: kTgykEusLT09KnbajtkWuBcFJKmlfX8TkuD-6iHOkOsw4MLhN8qLPXW2iuzYwnXUjGqOwBGNqHV1r3XYXMRtrl_7yKMOFaidXdD0WCd8aNQCECYAuIkfmq2Mu9UanqclHKvRbyTNw5-z9NmmnSItWKanBntV_Xdqkck-5LazHgByK4mPXVCzu_ECW4keIAGyZicBPDo1Xwio5kpSYMyc6f3ygFSliKQ0tI1KvcgplOivi_rqmZzT74RgPLJnHkNqNWn3SSmn45y8NPKdcYLYw1eH6bVcSvhmSfyQnF4miRpDsUWesTmZEuGBJWtEL7e16PPgu6F5OGxtqACqqP8lAQ
    dp: f8HxFakmeYjVRO4I5uY370cogTfxRp2Elu4CgzczDSmysogS6JoqFKiJGxZmFauLpbOaKLXdV_MFaZ2x5AZ9JHmlRk5TIaiCJ6KmlJV664TDAUwDHAG7DMDDKqIez8i1MsrdMV0j1kFEIiAReeDNsmKSUyC0tgX8U1yM00gU8JU
    dq: 4Q2GBXQAuaCQEtvjT_kE7LehwAIRSf2uo9FaB39quh7_UzYFI04Gjaf9vSI3FO06iWIn50BbBSdqMzihozheGKmkvbFu5PHrLMmFElX8ZHd7bDUQmajp42CGVM2pnun3zA1mCFvniM0Q5Hj9HhGApwGdCiL1Abxl6UpIpfQbdkE
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    p: znocslHOIZ5uRk9qvYy6rGDKRakvrFt1UWkQenvWlrjh-6LhEGbX_KH6euLvlImBm7TSzpNLz-Wevs_vi-Sb2YiHzkam52vLP8kkHK_T3ZRNiX-ByjSh1NsC60uIMMi8TVkFIknIIDQVw3WQsCxj_k9PEaOJyWJNcbjnW_FHhk0
    q: _8DRv9sYMzbvtMRN7mw-6vzuJQDLwK1EjfFpoGOoXLsDw-a3ew49ZkczHcAUIbhsIQwf00qBl2i23XM7kAC3Uc9_DTGRrGzYlZlcEvopVF42wjy60zd6LD3MlX1KJMDlyryZDGlLNaKgrsPN_o49Pk7ERqJXU_vzNIzi48el6mE
    qi: MWC91pRflqg6MhqOEGYx6yyioP8RgK8ip9xSnPxggdmC6UaOC9gIzYxd4YTtXZdQ8huQYj-raHiePg7VNXjZbfUf11hZ720hw6Df2a9K_SJjzkOXKK956-2OzFdQyshbsOy0DoiocZoO_S1huDU2mRCbrLRsYKbtIgj74AUNbbM
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    use: sig
  verificationKeys:
  - expiry: "2026-04-22T14:33:53.436142451Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 2daf9e9f8f6c5ca54c39dfa708b05cfa2c82c590
      kty: RSA
      "n": wUyzyuMIvtt_SdTEPFxvLYL75MbL1u3QkS_J0yThV0IrrwgUuoqmRMrCEj8Hbn485mA_WDY9UV3kZbAwfDwbG4920QmnymsWF1uvXzj2wJy9OjA5CLeHwk363Nv8J2JRfcS6kEMJwMxgC2_U4eaUNMioJCWVxbNohBkSWFakPbQ3Zi9B55DcKl7xbechX1wrUkakGlKM_T8uPRlF9cbjyBW2_EftcvpA_NM-qV1jrJ8mrFac3-iVIk2Ak3gaVlvjm1fEVg3RQ65njoYd6HJLfOIS46ODTDMGXTsJInuL6kbH8oc-KdXaxyJwleYyxNlgp90q22Resn5CBmU6PkpBzw
      use: sig
  - expiry: "2026-04-22T20:33:55.641873055Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 8846ee1a696063c208bddb570aaf5c3aed010a10
      kty: RSA
      "n": qz_woWQax5YS9GQQvSX_GcaU2XmLdDqQrhMwHAleJYrrrhmIe9Fib3XPLaFAbeJxS-dlQVS-lkURisYSMTD18Mu17eqIinpkVgEB6rALa4OazrzSg_F-zwMCIHiYYk90zXLzwbawLN_IlW98vKqMqzVIoAkm5ddE2qKlQjPcPT8qYscokmo7TrmIROFtpgV-BBfC31x8h_uOs3PuJJ-UIFtzwOT6Crr8KNFY8fkeLRSdlMGuaOkw4QLCGlZfEWniN3Wa4zYsZkLjqca1XIn-ztP4esp89Xyi5N2wYLCV12DmZYYxHpqPLVyTLqpBr0TMejRhPpXHVAdfHW0Dm7adDQ
      use: sig
  - expiry: "2026-04-23T02:33:56.203319721Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: e0ec805243b2a2e8e483ef77c1743cac7803cc91
      kty: RSA
      "n": tea2ogpKQ1QxhoogBsoZYVZJ8efHHMAHcAh2ohnMl5DZmCGZl2eqolHBOnPDlC8ibo59Bri1TCXu0E1V90aHQ0RA7txBj0mMxh3jOqyfdkA8tV31xdmpOYobV9LjaeXDUYlB_x1mEaDPtNz66NReW77gLoPF6oHKc5bRqc3wO1D5Q98qBFtdjPm1aY6I4VTlt9R_tTGqFwYBZ_UxwqDPVPd6Zba06kc41FW-oGFl0h9Jz-A6Vimabklf2h5v0ZvI1C4EqBzsAWF2Z6UZqELF6zlEM4qmGgcBppygrVpzzqEqiAxGa97x966DI9Oh8CLeMTwaaC-IndkRsI_8kQd1IQ
      use: sig
  - expiry: "2026-04-23T08:33:56.718775209Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 5b7c73f58a70e3ba11e00bb62ce361e47230a733
      kty: RSA
      "n": v0jhHk_JIexoU_qeG4XZUPqkKd8_vuV5gGibHGfo0hPy4IfBSZvD5gCnBDSlLqdqxpYSz3pCzG9Shh7RZUzvQUcotlGKYHr3nmRqHtrzVT4tF9Bgtigi10jRQstZO8LS7yDaMKvv-qdsPTFZF0Y5D2LmGSRgz4zOI2jtqNTxGUlb3uRrYxgg64qYuAWx4pyZgFe5azQzPRcEbqqhoT_7vDI28aC0YVy6-qSUtBxfL2kjGXVMPsjIAnGagPpj6EJ9I-Z0R8dz4-p7fx3pyK12SFnH9-7ZDLIMpVVUVCsNn6o4YG4gtOEHKx54GZ7527704b_AKmZjVKPPI4BlGmwCGw
      use: sig
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: konflux-ui
  nextRotation: "2026-04-23T06:03:44.09692333Z"
  signingKey:
    alg: RS256
    d: B9tqa586l30V8EeHz7C3kI3BKi2bfrTcw_SLTPAAFMOqSeBMhh7waDNbaxv30v_D3-ZPk61DVf8uh8iICI32HvkjdSg1Xx1xhX43HD4fngka9baDluo8SAbv6ok11NggC6ueUw_nMSPmnl8lJtweM6IOccoXtwoW6krkNGH8Bg6zsQSspo386bemFQOMQEg28ZoSm-WAj1MDVSfj1XiziOVOWBkHjINdF0BlHeRaTgLssNLKRWr9zdZrr_EZjpiAZGg72y60qkhPpxqsinvOt8fSNqFUjPTcZ_AH09U0-6LM55qJyf64HpPa7v39wbOk1CdnXVtv5td1ivq0asULcQ
    dp: C6i9z9CPWhlt6HCtHfmO5cw6rUCqSU1hF5DnADYTTZS1XeIQDzpHorj71-Jz7ziSW9mek_UaBaBQRlSqqGmSPyHn4nK5DLCGmaMDnso_LFmqR0tHLwXpDSLCX5wNcI7zUhnmQpb47WGsrJnWy0tvxZWBRXTQaaL15I6z2h1Kz8k
    dq: tePFj2QkojOonSUOW1G1mKJmuZZnkIOtvCSUrpHBF29PrHydSrrWP5mZGYZPYnKk355n51E5euycGAl8NJFfeApTuutkculiCOoP3_CqQBU-x5fNfTwnMWblH1M1TbEhhqFQBVHnUscMpHwdqKTHRtb6Cci9atFWoa3Pa3RBQKE
    e: AQAB
    kid: aa14ac3802a80443fb86b07528b114ad7c978901
    kty: RSA
    "n": vQ1NSQTuU8KSa7UZm-fGaSfZFSY-9FsGWb2fGLlAkji6DaLxQoQ-a9RCfk8tvt_qKcuNbWkadWSL2di-JVwZ7z9dba0a7zqvVCpB4bX4owsRELQ0HBYC_DzOEPoK9GlxutcXWXl63rakpU2E1EAbC4-xCRjKLkVP2vNVuCn09dqPXIcwC37LFTGVYnVYolYOxwglJrZ2SOBU0C4iKhyQq-BNKE8zRUoN4iszyw8MxXoTPqe0fUkmr5Yc21TzaXN3XcnG-NJxfp9vYkPPv0egWI8gvkSvlR6vyCs4p9OZsm6eHLWxtwlKzEABh1IiaOFNAb4gJh8NTSuuyRx3EiUrcQ
    p: 9j9RJOiVYX9233XbbGEXyiMvOu8MnrQ228gceN62TGWN3iCqY1vlBb5gRIAGvPf2dvbgsoFcDGceKnuq8rx8eCI9PqsQsv3g_jxUTLb713qQyRmyeV3PPu63gyEBH3cJ54Py1xlJs9Gjny-30qTCdMLv_dytyKw5DQByP565tzk
    q: xIoV3Db9GyHuJBYhu_YCTlaKZD2G-gUoq77m38wQ2r2Pkus5asDGywloKmh6IuOmdgcFejjmVpGqBD6NpFBhjp630AxJzmNT76P9aI9Y_pi4fH2h6g8LdBBe16I3ahq0t3-l8HEacST0cy4vQmDO1aH22j526BI9bw9ACxdEnfk
    qi: ZM0fORo0Lt1pCfvAs_OSszSoR5fb6KAHXYkhhdMoFaxkl303d2YXEkNmcFO6xRFAS4KHg-4ppJZt7eNw0HDufdmx-lOyex7nwJey7_VIc1tVTk7GzpqDgUrTPgxrqgLrpAwhMigtbxhlbgOPw6JC1Wt0reMvS_ovDSHUSKxfUbk
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: aa14ac3802a80443fb86b07528b114ad7c978901
    kty: RSA
    "n": vQ1NSQTuU8KSa7UZm-fGaSfZFSY-9FsGWb2fGLlAkji6DaLxQoQ-a9RCfk8tvt_qKcuNbWkadWSL2di-JVwZ7z9dba0a7zqvVCpB4bX4owsRELQ0HBYC_DzOEPoK9GlxutcXWXl63rakpU2E1EAbC4-xCRjKLkVP2vNVuCn09dqPXIcwC37LFTGVYnVYolYOxwglJrZ2SOBU0C4iKhyQq-BNKE8zRUoN4iszyw8MxXoTPqe0fUkmr5Yc21TzaXN3XcnG-NJxfp9vYkPPv0egWI8gvkSvlR6vyCs4p9OZsm6eHLWxtwlKzEABh1IiaOFNAb4gJh8NTSuuyRx3EiUrcQ
    use: sig
  verificationKeys:
  - expiry: "2026-04-23T18:03:32.00581147Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 4b5da7c6223ec148db99d9eada66a005790dd3ab
      kty: RSA
      "n": sw9dGMKaeQOZqMxUhY_gyEmxMTh0VPG3WQeVUy7eom947mkmS629LIEbroQ_dQ6hp7Ht6cs1VWuyAu1T0LHsjq0m-4DzL3YV8xx117cARPsb6Yl_35Tgav3kwxdRqkvvD_1mZDkfcNRT4cIzDPk8JYgAYeaYLpz97cj8DmqDQhrukov_1O3Ok3jets9jr1mwMm4XMxKVACOY5ANGw_43YGvA7VGcDqpCFGD9DgBRINSZ8z8EEaaf9vKeZ-RbrPTZrI1Et0vfzVvN6gwcvsOgQba2rGHYtSrM_rhWTl3p83ehJb12X9Zqj31l6MCoTfAJzbwpS3x0AKYevS3sVKgPWw
      use: sig
  - expiry: "2026-04-24T00:03:44.096921919Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: c5e40dab122239e984dd22ddb548c0c2409e2fa5
      kty: RSA
      "n": toAddOFQxgih6_7-CIv4V5EJnWNbVB9jdaMTkzuo_4ODCVjZYbXullUjclq0oD3h_q39WW0IjdUF6BQ7t0QTeqtLk9R1PhbruPr3emMFHLd2tTGeSTB0r3fmLrIH6q1-uwzBqlu-1RtJTUU1aMuMiUJVMHXgaoTKhD_pt-oPCVftEDJWGA-tOgqt_KkmR9BrDJBiSq41o-1pVvz0jBgkTlVq2z-MGO2VWodFBJDAXGpZ9vqNg71W18NXJs7tYL8EyDveREjVaxJd4XxQ9RwEBMKFIU4IiKnMdEMKusPXNVtUFNwksti1cWnuqgvfzc1hdod7cCOJd1dgy1Hs1v4E8w
      use: sig
kind: List
metadata:
