apiVersion: v1
items:
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: auth
  nextRotation: "2026-04-22T14:33:56.71877584Z"
  signingKey:
    alg: RS256
    d: kTgykEusLT09KnbajtkWuBcFJKmlfX8TkuD-6iHOkOsw4MLhN8qLPXW2iuzYwnXUjGqOwBGNqHV1r3XYXMRtrl_7yKMOFaidXdD0WCd8aNQCECYAuIkfmq2Mu9UanqclHKvRbyTNw5-z9NmmnSItWKanBntV_Xdqkck-5LazHgByK4mPXVCzu_ECW4keIAGyZicBPDo1Xwio5kpSYMyc6f3ygFSliKQ0tI1KvcgplOivi_rqmZzT74RgPLJnHkNqNWn3SSmn45y8NPKdcYLYw1eH6bVcSvhmSfyQnF4miRpDsUWesTmZEuGBJWtEL7e16PPgu6F5OGxtqACqqP8lAQ
    dp: f8HxFakmeYjVRO4I5uY370cogTfxRp2Elu4CgzczDSmysogS6JoqFKiJGxZmFauLpbOaKLXdV_MFaZ2x5AZ9JHmlRk5TIaiCJ6KmlJV664TDAUwDHAG7DMDDKqIez8i1MsrdMV0j1kFEIiAReeDNsmKSUyC0tgX8U1yM00gU8JU
    dq: 4Q2GBXQAuaCQEtvjT_kE7LehwAIRSf2uo9FaB39quh7_UzYFI04Gjaf9vSI3FO06iWIn50BbBSdqMzihozheGKmkvbFu5PHrLMmFElX8ZHd7bDUQmajp42CGVM2pnun3zA1mCFvniM0Q5Hj9HhGApwGdCiL1Abxl6UpIpfQbdkE
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    p: znocslHOIZ5uRk9qvYy6rGDKRakvrFt1UWkQenvWlrjh-6LhEGbX_KH6euLvlImBm7TSzpNLz-Wevs_vi-Sb2YiHzkam52vLP8kkHK_T3ZRNiX-ByjSh1NsC60uIMMi8TVkFIknIIDQVw3WQsCxj_k9PEaOJyWJNcbjnW_FHhk0
    q: _8DRv9sYMzbvtMRN7mw-6vzuJQDLwK1EjfFpoGOoXLsDw-a3ew49ZkczHcAUIbhsIQwf00qBl2i23XM7kAC3Uc9_DTGRrGzYlZlcEvopVF42wjy60zd6LD3MlX1KJMDlyryZDGlLNaKgrsPN_o49Pk7ERqJXU_vzNIzi48el6mE
    qi: MWC91pRflqg6MhqOEGYx6yyioP8RgK8ip9xSnPxggdmC6UaOC9gIzYxd4YTtXZdQ8huQYj-raHiePg7VNXjZbfUf11hZ720hw6Df2a9K_SJjzkOXKK956-2OzFdQyshbsOy0DoiocZoO_S1huDU2mRCbrLRsYKbtIgj74AUNbbM
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: 10800422de086812feebc207c13492b930fe4314
    kty: RSA
    "n": zkcnV5R4pzg4ao4MkkfUVAPYsTFFrJjV9rnXvBboi28riKj0MkTMAokSaehiLwWZOxCspEimx27WzSlQTWVXcy-9pHyMGCPh_A_yjnEmTEi5eoBxcvcttUGMLPnPcANk-M2Y7Il0ShIKqAUI_je-XXAc1jAerU0A1sXpBIDQkEoo8CshU5LaeAWmL9mHTYA8M8UWEPMOcu0HqdyS2bhEId9FK7tEV8kfiH_xuDFfhziAVV0RdlRUyWogrfAEAeF7UID_EH15dAO5Ev6HgnwdWiHniPPtu_IyfhDNTe-ittBoKKr6K5psKGE4ZBLuZhdaS4Ajs_yB11TecuEoN31FLQ
    use: sig
  verificationKeys:
  - expiry: "2026-04-22T14:33:53.436142451Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 2daf9e9f8f6c5ca54c39dfa708b05cfa2c82c590
      kty: RSA
      "n": wUyzyuMIvtt_SdTEPFxvLYL75MbL1u3QkS_J0yThV0IrrwgUuoqmRMrCEj8Hbn485mA_WDY9UV3kZbAwfDwbG4920QmnymsWF1uvXzj2wJy9OjA5CLeHwk363Nv8J2JRfcS6kEMJwMxgC2_U4eaUNMioJCWVxbNohBkSWFakPbQ3Zi9B55DcKl7xbechX1wrUkakGlKM_T8uPRlF9cbjyBW2_EftcvpA_NM-qV1jrJ8mrFac3-iVIk2Ak3gaVlvjm1fEVg3RQ65njoYd6HJLfOIS46ODTDMGXTsJInuL6kbH8oc-KdXaxyJwleYyxNlgp90q22Resn5CBmU6PkpBzw
      use: sig
  - expiry: "2026-04-22T20:33:55.641873055Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 8846ee1a696063c208bddb570aaf5c3aed010a10
      kty: RSA
      "n": qz_woWQax5YS9GQQvSX_GcaU2XmLdDqQrhMwHAleJYrrrhmIe9Fib3XPLaFAbeJxS-dlQVS-lkURisYSMTD18Mu17eqIinpkVgEB6rALa4OazrzSg_F-zwMCIHiYYk90zXLzwbawLN_IlW98vKqMqzVIoAkm5ddE2qKlQjPcPT8qYscokmo7TrmIROFtpgV-BBfC31x8h_uOs3PuJJ-UIFtzwOT6Crr8KNFY8fkeLRSdlMGuaOkw4QLCGlZfEWniN3Wa4zYsZkLjqca1XIn-ztP4esp89Xyi5N2wYLCV12DmZYYxHpqPLVyTLqpBr0TMejRhPpXHVAdfHW0Dm7adDQ
      use: sig
  - expiry: "2026-04-23T02:33:56.203319721Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: e0ec805243b2a2e8e483ef77c1743cac7803cc91
      kty: RSA
      "n": tea2ogpKQ1QxhoogBsoZYVZJ8efHHMAHcAh2ohnMl5DZmCGZl2eqolHBOnPDlC8ibo59Bri1TCXu0E1V90aHQ0RA7txBj0mMxh3jOqyfdkA8tV31xdmpOYobV9LjaeXDUYlB_x1mEaDPtNz66NReW77gLoPF6oHKc5bRqc3wO1D5Q98qBFtdjPm1aY6I4VTlt9R_tTGqFwYBZ_UxwqDPVPd6Zba06kc41FW-oGFl0h9Jz-A6Vimabklf2h5v0ZvI1C4EqBzsAWF2Z6UZqELF6zlEM4qmGgcBppygrVpzzqEqiAxGa97x966DI9Oh8CLeMTwaaC-IndkRsI_8kQd1IQ
      use: sig
  - expiry: "2026-04-23T08:33:56.718775209Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 5b7c73f58a70e3ba11e00bb62ce361e47230a733
      kty: RSA
      "n": v0jhHk_JIexoU_qeG4XZUPqkKd8_vuV5gGibHGfo0hPy4IfBSZvD5gCnBDSlLqdqxpYSz3pCzG9Shh7RZUzvQUcotlGKYHr3nmRqHtrzVT4tF9Bgtigi10jRQstZO8LS7yDaMKvv-qdsPTFZF0Y5D2LmGSRgz4zOI2jtqNTxGUlb3uRrYxgg64qYuAWx4pyZgFe5azQzPRcEbqqhoT_7vDI28aC0YVy6-qSUtBxfL2kjGXVMPsjIAnGagPpj6EJ9I-Z0R8dz4-p7fx3pyK12SFnH9-7ZDLIMpVVUVCsNn6o4YG4gtOEHKx54GZ7527704b_AKmZjVKPPI4BlGmwCGw
      use: sig
- apiVersion: dex.coreos.com/v1
  kind: SigningKey
  metadata:
    name: openid-connect-keys
    namespace: konflux-ui
  nextRotation: "2026-04-25T06:05:36.810840533Z"
  signingKey:
    alg: RS256
    d: CQz5QYiTfSIPJ6BHUs0j5ZMHjC5ae6GZm7RL3dDqq_bmn9n-Pr0Fin6uEltf_JaNIK5TARJtedfDQLSp79UHKyMxrqBUP25hLMxF9rOAsrIiDDibXnDJNPeaNfVhHu-p91qhjeLiIjVn-ifLrXOQXZ9F4bSgceIQRP7FxPfiS7-o7mgtVQkXt71pKMDu1e4ILzk7wK0H4VyxsjNzZkENPAkHiiYiTMn3KJziTFG8g_pZINeBeVrwSIXwDHV1nqgggcwlCDa3TBVbVklBnQ4b5CMQFKqzK-SJUxwGwRKopB2ATfzzGodulczxswMr_t3Fe96-8oO9ZYhA-PJJEmuauQ
    dp: HB39SnpbznvCA8LLf2fPWOgrumMHOyJf02Z7uS-eLeg0VFrs3azoxvbFGmWeUUNQZeeh0jnry8YfzNCNauoAskeGeRh7sGSpj23mHPUKFs32bpKZgaECq7Kw4FG4w704IcRJrkOmn8sjQgyzfKZw80obr6fgtnvllM_QKNYxbBE
    dq: HY1oweqDoxsmY79iOTsrfH8FLcUERrjdi79sj4w2VHXqVMt7cYfiv2LlxjxR3nXSaW8R0w6Vh4uK93a7AwTC7sSuoiomlIcEsUDEir6Qf_TbLqv26X2uXzYKWE-0T92PDO3msGA8OeH99M1xlpfd7nbuG_heRbah_Iv858eYfQ
    e: AQAB
    kid: 1e64706ecdfc6a52267389486ff63d2db8bdfaa1
    kty: RSA
    "n": 1_94IOb_ZzezlxT7E7aVuF3y5VwycUNUQqKPqAeA1-0Zf83FtfRHrJ4Ixtgkn2tq-q04TVJofzA8c7Z0kxzQ9WqxMHdtY9vNn93zlAotgt51FE-i2qxt4FFL5OgPPC5dMX6ruRvQNL3sIj5MdI-w5FdgPsvxplit7ZOvLsvsaOOVPjAjRKyCMMZBjEnwftX-yk_lVtkiDVIXA2M4gzaZ-MpofDGvpec4ZY9F8d680Vt4_0vY_gAtXz8zx06xSOnMW8Fnyjm0ghW42NzO-tIRuCTkR5mfoMAjhwa7czcS0-1KhR36sEEVcK0fpd1UvqFkB_Tu92iqOMtybDGYTzQEyw
    p: 8TFe6O9Sl3DfAxwfK0TZsOfC96X8L4A7tBThKWTFNhgzWk_sc5g1NMsPUZURHliEMiD2aXldvqgx9UoPZU7uc4rhus4IVt03oEiQC6Hgw_SmFTYmviQQgnVL9m_RikC7nCkhDqdvXIpsNAC4vZXER6zdvz-LEdi7IbBIqrNo42c
    q: 5UIhbyEjUmMyZA3BtzGY9abWsMs2qKQCFEWVyXpcJD_2oKk4JuOGCd43jKtlqPXYOEmNo-QjlGVo0YGHkXKaxgyG_s_Ht69PR-xL_Dcg7MSzgDdxIpA8_yn8jl15Mvc9aKKIrNDd4eKpawMaTdy-QKHV5_QwbT1TAWSmas2VeP0
    qi: QWZIfMsv5rrk2RaY7JhY9eDYzRuxS3EkNgw8sqBjwXKvdIJ_TxOS4jxES1NSaedf8M2f80Psud-z8yfFjG5RXnhmNc8W1819_m-DcGGXsFrzSTT7WdFtiCLQIvc0mvlMgfAYi1YOo5tRQVYc9HNbwzHUDJNq5IBf3LV1qgjwSlk
    use: sig
  signingKeyPub:
    alg: RS256
    e: AQAB
    kid: 1e64706ecdfc6a52267389486ff63d2db8bdfaa1
    kty: RSA
    "n": 1_94IOb_ZzezlxT7E7aVuF3y5VwycUNUQqKPqAeA1-0Zf83FtfRHrJ4Ixtgkn2tq-q04TVJofzA8c7Z0kxzQ9WqxMHdtY9vNn93zlAotgt51FE-i2qxt4FFL5OgPPC5dMX6ruRvQNL3sIj5MdI-w5FdgPsvxplit7ZOvLsvsaOOVPjAjRKyCMMZBjEnwftX-yk_lVtkiDVIXA2M4gzaZ-MpofDGvpec4ZY9F8d680Vt4_0vY_gAtXz8zx06xSOnMW8Fnyjm0ghW42NzO-tIRuCTkR5mfoMAjhwa7czcS0-1KhR36sEEVcK0fpd1UvqFkB_Tu92iqOMtybDGYTzQEyw
    use: sig
  verificationKeys:
  - expiry: "2026-04-25T06:04:54.00540487Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: fc2493ee28754911d15836e9cd209558f8111edd
      kty: RSA
      "n": 1gR31-8GymAO_S1XeWzcV4AKYK-cf2L-90DHaZafarvfK3HP4OAXfbJV5_f-4rL4P8Am_yI8NzC08xR4SvaI6dYXR7JAKKXIxJ0GkTtnFa5dph1sMZZSwApsJQk9Ams34Qemz4FArLz027YHLzZSADIHV1HtHNrrrROetFc5eVGqOGxY9BtZf1L9cjLRrS3QAcI2FVbxzEOq4UfVYucGY9TXrjXhdD1K0UORvidoA-0NL3lqjL-9tWWwhBuFAVG1KIsZhiXeSTkMRdUt5mQGkZvErNzskH6UXoh-BMXxL7C3REX_eoghR77ULhtEFUqsec8v5KWKqSN9g77sqZCuKQ
      use: sig
  - expiry: "2026-04-25T12:05:12.13571029Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: d89c419b1e9423c96cc78d1c1d3dceaad111b8f9
      kty: RSA
      "n": rEsDYx34YnRmpi_NTPDHEVbdRjutuJFGfSI-5H8RzH0sbsQalHPF7j3XjYCTIsKBtd3SDw7Rc1SPvd89g6ZDFFAmuP8cynEKRQVkWut0I99aAVskReuAk8fSCBpUL3EXqdaBGsyIQUMvHZagkXPc73OT3BjSRW1Q4VC3gtLR67FGFKIlxyizAQQaRIniGfST7kUJFy7TRn2dAVjUrFFKC7PRUX5h72bb3y5zcgBnoc13oLQG5UKB3hkedN2PzdP1LC4GUwlxZ-QBYlojGHSUr4p4TcAq6bONs_bQbbHq-ednZ_PcOcvQpJOVfDS20YIeoFyip42VjSXVcxYAWHtmGw
      use: sig
  - expiry: "2026-04-25T18:05:24.909879872Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 8311dc6f011e26408154fc4a9d8f13364a6ce878
      kty: RSA
      "n": rbsSlDKbCgXRVhXpiF0P6t87RHtwaRK1fDf2ojZWhJ9xGr4YSMVV0A_E9lMBDTwb4DC32hopK0NCOMz6bSHc8FYrhVQq_gTzBN46Ukcag_6DVUE42YvjKs_AKQs39EuqZBgOpDYFQnDASC0hTVY2n30jMseD3-Do5RvAWlzw8EXGEH8ZvY2GOEkYsy7eyfid6zTX6CKxL0gCuROGLRxzk_CRMOoqwKVBtr-HrGf7OZJlT_hiCCT3utY_U05Kio9p-MJSAh44iFoihZXtAmIhuDoIcVozoQq1wvjghIs87fpFkrMOHIYyDzdbq39puuzsL11irtwutgK6VgtNdI3ZSw
      use: sig
  - expiry: "2026-04-26T00:05:36.810839716Z"
    publicKey:
      alg: RS256
      e: AQAB
      kid: 8817be070afc5e21554fa572e9b9b52c14dc1ed2
      kty: RSA
      "n": v5nfvVHpdoidkt_hk0XDWEMFixu9fX6zZtSbm9GMO-QzwNsHbW86TnLuMsuvvYPRBef0tcFLTXez_wJ_O5zJcnJ2DAeG9OnfbQWkNuLd-hydE2QzOPm88kErdQZOxa_ua8muh8pfBU2mDbWQSGZcLBevQeflLqCZyjWlha5_enI-4fSUpe7DKtOIYcWZabYPpU6tbNQ8oPseoOq-6or8aWSv0bqGX4jQ91ath1HywGSJ-m67lsUTFpQIAgl5ozfdA7VeNwLcewSz4Clg5yMY6-vm9tJ3umMRK9oXEJQYjPZ4qc3mZLGATngK4tkdKYzlyG5rbDkPu8alqEWy7mMkLw
      use: sig
kind: List
metadata:
