apiVersion: v1
items:
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: 0476540f
    namespace: aiot
  spec:
    date: "2026-04-22T07:01:29Z"
    id: 0476540f042e9f8b1621f2e770b7aa32bbaf274b094c89ced1db58f9be9b7a4e
    paths:
    - /data/qdrant-pvc
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: 17c42d47
    namespace: aiot
  spec:
    date: "2026-04-22T07:01:26Z"
    id: 17c42d479f92ee1c4ef86dc7f1969f86d739ba0b915c2c19ace0ddce0eb4f999
    paths:
    - /data/pgadmin-data
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: 5c072bff
    namespace: aiot
  spec:
    date: "2026-04-22T07:01:39Z"
    id: 5c072bff69723c1ecb795c0d5e9c1309393e22708e44a3169843e93765a281f5
    paths:
    - /aiot-pg-ha-dump.sql
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: d28991df
    namespace: aiot
  spec:
    date: "2026-04-23T03:10:35Z"
    id: d28991df620745dfb3ec919d7668b76cb882e4b3ee70c6cea3d1b386b36bd911
    paths:
    - /aiot-pg-ha-dump.sql
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: f5426abb
    namespace: aiot
  spec:
    date: "2026-04-22T07:01:19Z"
    id: f5426abb1fbcac4c1e93388f4500637fbef68664fbd0af54eb9bcf1e70d532b0
    paths:
    - /data/cloudbeaver-data-lp
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: 440b29a9
    namespace: jenkins
  spec:
    date: "2026-04-22T07:00:59Z"
    id: 440b29a92cac442fad7d815b73962a0589ac316a9a2ad1c199a272aca8fb720a
    paths:
    - /data/jenkins-lp
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: 2d09f3cd
    namespace: semaphore
  spec:
    date: "2026-04-23T03:05:07Z"
    id: 2d09f3cdfed102f5ced9d7fcfde18cd696c9f3feac39b36d9ae5cc9a88617c3f
    paths:
    - /data/semaphore-data
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
- apiVersion: k8up.io/v1
  kind: Snapshot
  metadata:
    name: d7478611
    namespace: semaphore
  spec:
    date: "2026-04-22T07:00:50Z"
    id: d74786111dfc85d8c8497b086df60985b14e3b946726bc5f71fe40cb51ff7f40
    paths:
    - /data/semaphore-data
    repository: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
kind: List
metadata:
