apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SpaceHistory
  metadata:
    name: 055e4e416ad87e57bb23bb535e51a336777b9010d7d34f84c2e5030b96b77817
  spec:
    capacity: if1aNG6mVWQAAAAAAAAAYAAAAAAAAAAfAAAAAAAAAGE=
    entry_date: 1776988800000
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SpaceHistory
  metadata:
    name: 16d0d4d39f61ab2fd8cdca0bd81d291b84ee384740924035750b4fbf79537e74
  spec:
    capacity: spSwdM120sUAAAAAAAAAYAAAAAAAAAAWAAAAAAAAAE0=
    entry_date: 1776902400000
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SpaceHistory
  metadata:
    name: 60921c0f38f87ec20ca28ecc9d7e5a040ade908c5c3beae8abf2d2c40782994f
  spec:
    capacity: XU+7zLPFMrAAAAAAAAAAYAAAAAAAAAA2AAAAAAAAAHU=
    entry_date: 1777075200000
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SpaceHistory
  metadata:
    name: 9eeb13537dfc67efc875d1d087fd6f4ce70ac7b30126f8049e5fbe1578618738
  spec:
    capacity: zkJFizW1QwAAAAAAAAAAYAAAAAAAAAAVAAAAAAAAAE0=
    entry_date: 1776816000000
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: SpaceHistory
  metadata:
    name: df3ce33da5654f277423eec577b1fcbc3ea21626ed7c1ed301b20911a4e651a8
  spec:
    capacity: mI2ZQ1nd30IAAAAAAAAAYAAAAAAAAAAtAAAAAAAAAHU=
    entry_date: 1777161600000
kind: List
metadata:
