apiVersion: v1
items:
- apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonResult
  metadata:
    finalizers:
    - tektonresults.operator.tekton.dev
    labels:
      operator.tekton.dev/release-version: v0.79.0
    name: result
    ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TektonConfig
      name: config
  spec:
    config: {}
    disabled: false
    is_external_db: false
    options: {}
    performance:
      disable-ha: false
    route_enabled: false
    route_tls_termination: edge
    targetNamespace: tekton-pipelines
  status:
    conditions:
    - lastTransitionTime: "2026-04-22T14:21:52Z"
      status: "True"
      type: DependenciesInstalled
    - lastTransitionTime: "2026-04-22T11:41:28Z"
      status: "True"
      type: InstallerSetAvailable
    - lastTransitionTime: "2026-04-22T15:17:40Z"
      status: "True"
      type: InstallerSetReady
    - lastTransitionTime: "2026-04-22T11:42:10Z"
      status: "True"
      type: PostReconciler
    - lastTransitionTime: "2026-04-22T11:41:28Z"
      status: "True"
      type: PreReconciler
    - lastTransitionTime: "2026-04-22T15:17:40Z"
      status: "True"
      type: Ready
    observedGeneration: 1
    tektonInstallerSet: result-4d4wx
    version: v0.18.0
kind: List
metadata:
