apiVersion: v1
items:
- apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonChain
  metadata:
    finalizers:
    - tektonchains.operator.tekton.dev
    labels:
      operator.tekton.dev/release-version: v0.79.0
    name: chain
    ownerReferences:
    - apiVersion: operator.tekton.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TektonConfig
      name: config
  spec:
    artifacts.oci.format: simplesigning
    artifacts.oci.storage: oci
    artifacts.pipelinerun.enable-deep-inspection: "true"
    artifacts.pipelinerun.format: in-toto
    artifacts.pipelinerun.storage: oci
    artifacts.taskrun.format: in-toto
    artifacts.taskrun.signer: x509
    artifacts.taskrun.storage: ""
    builddefinition.buildtype: https://tekton.dev/chains/v2/slsa
    config: {}
    disabled: false
    options:
      deployments:
        tekton-chains-controller:
          metadata:
          spec:
            selector: null
            strategy: {}
            template:
              metadata:
              spec:
                containers:
                - args:
                  - --namespace=default-tenant
                  - -threads-per-controller=1
                  name: tekton-chains-controller
                  resources: {}
                volumes:
                - configMap:
                    items:
                    - key: ca-bundle.crt
                      path: ca-bundle.crt
                    name: trusted-ca
                    optional: true
                  name: trusted-ca
          status: {}
      disabled: false
    performance:
      disable-ha: false
    targetNamespace: tekton-pipelines
    transparency.enabled: "false"
  status:
    conditions:
    - lastTransitionTime: "2026-04-26T18:26:40Z"
      status: "True"
      type: DependenciesInstalled
    - lastTransitionTime: "2026-04-23T09:55:06Z"
      status: "True"
      type: InstallerSetAvailable
    - lastTransitionTime: "2026-04-26T17:22:44Z"
      status: "True"
      type: InstallerSetReady
    - lastTransitionTime: "2026-04-22T11:41:27Z"
      status: "True"
      type: PostReconciler
    - lastTransitionTime: "2026-04-22T11:41:18Z"
      status: "True"
      type: PreReconciler
    - lastTransitionTime: "2026-04-26T18:26:40Z"
      status: "True"
      type: Ready
    observedGeneration: 7
    tektonInstallerSet: chain-config-qgg98
    version: v0.26.2
kind: List
metadata:
