apiVersion: v1
items:
- ExtraByProvider:
    local:
      principalid:
      - local://user-b2zsr
      username:
      - admin
  GroupPrincipals:
    activedirectory:
      Items: null
    adfs:
      Items: null
    azuread:
      Items: null
    cognito:
      Items: null
    freeipa:
      Items: null
    genericoidc:
      Items: null
    github:
      Items: null
    githubapp:
      Items: null
    googleoauth:
      Items: null
    keycloak:
      Items: null
    keycloakoidc:
      Items: null
    local:
      Items: null
    oidc:
      Items: null
    okta:
      Items: null
    openldap:
      Items: null
    ping:
      Items: null
    shibboleth:
      Items: null
  LastRefresh: "2026-04-24T01:05:36Z"
  NeedsRefresh: false
  UserName: ""
  apiVersion: management.cattle.io/v3
  kind: UserAttribute
  lastLogin: "2026-04-22T04:06:07Z"
  metadata:
    name: user-b2zsr
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      kind: User
      name: user-b2zsr
kind: List
metadata:
