apiVersion: v1
items:
- apiVersion: management.cattle.io/v3
  description: ""
  displayName: System account for Cluster local
  kind: User
  metadata:
    annotations:
      authz.management.cattle.io/creator-role-bindings: '{"created":["user"],"required":["user"]}'
      lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
    finalizers:
    - controller.cattle.io/mgmt-auth-users-controller
    labels:
      EDSN6T35DKT2UBRCDTHM2R0: hashed-principal-name
    name: u-b4qkhsnliz
  principalIds:
  - system://local
  - local://u-b4qkhsnliz
  status:
    conditions:
    - lastUpdateTime: "2026-04-19T20:51:54Z"
      status: "True"
      type: InitialRolesPopulated
- apiVersion: management.cattle.io/v3
  description: ""
  kind: User
  metadata:
    annotations:
      lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
    finalizers:
    - controller.cattle.io/mgmt-auth-users-controller
    labels:
      EDSN6T35DKT2UBRGE9NNCQBJD5NMSQBECSNMCR35CLQ2QR3FCDGMOBRCDTHM2R0: hashed-principal-name
    name: u-mo773yttt4
  principalIds:
  - system://provisioning/fleet-local/local
  - local://u-mo773yttt4
  status: {}
- apiVersion: management.cattle.io/v3
  description: ""
  displayName: Default Admin
  kind: User
  metadata:
    annotations:
      lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
    finalizers:
    - controller.cattle.io/mgmt-auth-users-controller
    generateName: user-
    labels:
      authz.management.cattle.io/bootstrapping: admin-user
      cattle.io/last-login: "1776830767"
    name: user-b2zsr
  principalIds:
  - local://user-b2zsr
  status: {}
  username: admin
kind: List
metadata:
