apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 15c35d837c8b5917d15c8f87af918051a5b96a07aa8001350788dcf84f23161d
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-17D30D0E-224F-42EF-BC00-70349E931E33
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 2e37cf14e0843a0f95313783d9d9af28f30840290d947b90ac93c8789af63103
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-61A22797-A355-4F74-A517-BFE2C6257D14
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 4336a472d5da5f2a935d214301b78b478700675d2992e60867a4eeb417889c36
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-13780103-955C-4B47-9417-E7C91ADA2649
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 5a9baf4cff962dae194f23fbd149846563dae3dadfe473b2c74d62ee22c3fcd5
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-33099827-4B54-4D13-8588-122F969DEA72
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 6a887c3287ea9b6a038a566520674f9f107f23315735ea2761ab197123f8b1e3
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-3FFCF658-4DFC-4976-8B3C-8D1329648895
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 7095b830c376d5f76dedc58caf7ae67a150a4c054740e2b16c5ce4f985fbefb5
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-FC2D6EE5-7B9E-4673-A88E-7079B254BB40
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 716f7dd1bb2c9d5e7a16dca42364c8c36625e8988d45347e5aa40c20d72bb8cd
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-61A22797-A355-4F74-A517-BFE2C6257D14
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: 9a260ba8b5c597a5403a6882bd8e2b9c5fb475952a9344f8177e2b71bba944cb
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-17D30D0E-224F-42EF-BC00-70349E931E33
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: a144f0b64629df42bcfc19324ef0a2bf47d8ffd5b2fc6bbd936fbc204b273bca
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-15ABFC60-E493-48AD-A2C8-C7F7BE5A6607
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: ab8e767c40cf90a61496c07cdb99d268387c4d8c0542198a8f90da15b160c627
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-734704A4-89F1-4F12-B3A1-2C178791C993
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: c67fba22844e4519e426e6021236a1a16cd0c8b035f243b33aad3f040bd746b2
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-13780103-955C-4B47-9417-E7C91ADA2649
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: c855ecaa4fc8534d1cb23cf9ec3ed038cd1bbe7129fa9514abb1cfce56236987
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-27976678-7D15-4989-99F4-0B94C9EC069C
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: cd0a593fda560934eb0a04405a142813008ba9a9859ffcdd780f22062dd9d31c
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-33099827-4B54-4D13-8588-122F969DEA72
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: ce71b2b6db7dabcef9b8d0c7cd913955c83d1043a9c3e3ce152d3900e5b16e26
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-734704A4-89F1-4F12-B3A1-2C178791C993
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: d62a3f45f88f6658a44abb1b8240eed53e8c185ec699535f6659fc6449644c38
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-3FFCF658-4DFC-4976-8B3C-8D1329648895
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: df13fc8bd76ad1ce8c9870afb5dba31e0187b4a7f562ca91d3d275b992e2819b
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-27976678-7D15-4989-99F4-0B94C9EC069C
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: e05257a0149a3943206056d0b41f4da9207e6b09c5278373f484042d583fc201
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-7496D803-A21D-484B-9756-4327047B07BD
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: e8c5d33afaa0b10c7440c380b74a1d04d8e56b8e2c76ccac11ab4a66d1ea8a12
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-FC2D6EE5-7B9E-4673-A88E-7079B254BB40
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: f79849c19f853be52e08a0473d0e42ebb0b4343167ade6ea10f4532733d869a1
  spec:
    node_name: AIOT-WORKER-01
    resource_name: PVC-7496D803-A21D-484B-9756-4327047B07BD
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: Volumes
  metadata:
    name: fd6ba0af8db2d05f5bbfffa8ff419d838c17eb4d43318d2d3fb6978ea771c26c
  spec:
    node_name: AIOT-WORKER-02
    resource_name: PVC-15ABFC60-E493-48AD-A2C8-C7F7BE5A6607
    snapshot_name: ""
    vlm_flags: 0
    vlm_nr: 0
kind: List
metadata:
