apiVersion: v1
items:
- apiVersion: internal.linstor.linbit.com/v1-15-0
  kind: VolumeGroups
  metadata:
    name: 1ee54d5e8fdd6f769302eec3465a05d380b32f6cc1322c25e1f59be193e8d5f1
  spec:
    flags: 0
    resource_group_name: SC-3BA5B71F-7C6D-50FB-AB0A-19062E56B1A8
    vlm_nr: 0
kind: List
metadata:
