apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mqtt-bridge
  namespace: emqx
  labels:
    app: go-mqtt-bridge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-mqtt-bridge
  template:
    metadata:
      labels:
        app: go-mqtt-bridge
    spec:
      containers:
      - name: bridge
        image: go-mqtt-bridge:v1
        imagePullPolicy: Never
        env:
        - name: MQTT_HOST
          value: emqx.emqx.svc.cluster.local
        - name: MQTT_PORT
          value: "1883"
        - name: KAFKA_BOOTSTRAP
          value: redpanda.aiot.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: telemetry
        - name: BATCH_SIZE
          value: "500"
        - name: LINGER_MS
          value: "20"
        - name: BUFFER_SIZE
          value: "500000"
        - name: METRICS_PORT
          value: "9090"
        ports:
        - containerPort: 9090
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
