apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"pgadmin","namespace":"aiot"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"pgadmin"}},"template":{"metadata":{"labels":{"app":"pgadmin"}},"spec":{"containers":[{"env":[{"name":"PGADMIN_DEFAULT_EMAIL","value":"admin@aiot.com"},{"name":"PGADMIN_DEFAULT_PASSWORD","value":"admin123"},{"name":"PGADMIN_SERVER_JSON_FILE","value":"/pgadmin4/servers/servers.json"}],"image":"dpage/pgadmin4:latest","name":"pgadmin","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"400Mi"},"requests":{"cpu":"100m","memory":"200Mi"}},"volumeMounts":[{"mountPath":"/pgadmin4/servers","name":"servers","readOnly":true}]}],"volumes":[{"configMap":{"name":"pgadmin-servers"},"name":"servers"}]}}}}
  name: pgadmin
  namespace: aiot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-09T18:26:18Z"
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@aiot.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin123
        - name: PGADMIN_SERVER_JSON_FILE
          value: /pgadmin4/servers/servers.json
        - name: GUNICORN_TIMEOUT
          value: "86400"
        image: dpage/pgadmin4:8.14
        imagePullPolicy: Always
        name: pgadmin
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pgadmin4/servers
          name: servers
          readOnly: true
        - mountPath: /pgadmin4/config_system.py
          name: pgadmin-config
          readOnly: true
          subPath: config_system.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pgadmin-servers
        name: servers
      - configMap:
          defaultMode: 420
          name: pgadmin-config
        name: pgadmin-config
