apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"api-gateway","namespace":"aiot"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31179,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"api-gateway"},"sessionAffinity":"None","type":"NodePort"},"status":{}}
    name: api-gateway
    namespace: aiot
  spec:
    - 10.101.49.182
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31179
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: api-gateway
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"digital-twin","namespace":"aiot"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31801,"port":8001,"protocol":"TCP","targetPort":8001}],"selector":{"app":"digital-twin"},"sessionAffinity":"None","type":"NodePort"},"status":{}}
    name: digital-twin
    namespace: aiot
  spec:
    - 10.96.179.248
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31801
      port: 8001
      protocol: TCP
      targetPort: 8001
    selector:
      app: digital-twin
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: emqx
    name: emqx
    namespace: aiot
  spec:
    externalName: emqx.emqx.svc.cluster.local
    selector:
      app: emqx
    sessionAffinity: None
    type: ExternalName
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ngrok-proxy","namespace":"aiot"},"spec":{"ports":[{"port":8090,"targetPort":8090}],"selector":{"app":"ngrok-proxy"}}}
    name: ngrok-proxy
    namespace: aiot
  spec:
    - 10.110.61.46
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: ngrok-proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"pgadmin","namespace":"aiot"},"spec":{"ports":[{"nodePort":31080,"port":80,"targetPort":80}],"selector":{"app":"pgadmin"},"type":"NodePort"}}
    name: pgadmin
    namespace: aiot
  spec:
    - 10.96.238.188
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31080
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: pgadmin
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"aiot"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgres"},"type":"ClusterIP"}}
    name: postgres
    namespace: aiot
  spec:
    - 10.98.61.21
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"qdrant","namespace":"aiot"},"spec":{"ports":[{"name":"http","port":6333,"targetPort":6333},{"name":"grpc","port":6334,"targetPort":6334}],"selector":{"app":"qdrant"}}}
    name: qdrant
    namespace: aiot
  spec:
    - 10.96.99.149
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 6333
      protocol: TCP
      targetPort: 6333
    - name: grpc
      port: 6334
      protocol: TCP
      targetPort: 6334
    selector:
      app: qdrant
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"rag-api-svc","namespace":"aiot"},"spec":{"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31700,"port":7000,"protocol":"TCP","targetPort":7000}],"selector":{"app":"rag-worker"},"sessionAffinity":"None","type":"NodePort"},"status":{}}
    name: rag-api-svc
    namespace: aiot
  spec:
    - 10.105.168.31
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31700
      port: 7000
      protocol: TCP
      targetPort: 7000
    selector:
      app: rag-worker
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-master","namespace":"aiot"},"spec":{"ports":[{"port":6379,"targetPort":6379}],"selector":{"app":"redis-master"}}}
    name: redis-master
    namespace: aiot
  spec:
    - 10.98.4.56
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31379
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis-master
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"redpanda"},"name":"redpanda","namespace":"aiot"},"spec":{"ports":[{"name":"kafka","port":9092,"targetPort":9092},{"name":"admin","port":9644,"targetPort":9644},{"name":"pandaproxy","port":8082,"targetPort":8082}],"selector":{"app":"redpanda"},"type":"ClusterIP"}}
    labels:
      app: redpanda
    name: redpanda
    namespace: aiot
  spec:
    - 10.100.67.116
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: admin
      port: 9644
      protocol: TCP
      targetPort: 9644
    - name: pandaproxy
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: redpanda
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"redpanda"},"name":"redpanda-headless","namespace":"aiot"},"spec":{"clusterIP":"None","ports":[{"name":"kafka","port":9092,"targetPort":9092},{"name":"admin","port":9644,"targetPort":9644},{"name":"rpc","port":33145,"targetPort":33145},{"name":"pandaproxy","port":8082,"targetPort":8082}],"publishNotReadyAddresses":true,"selector":{"app":"redpanda"}}}
    labels:
      app: redpanda
    name: redpanda-headless
    namespace: aiot
  spec:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: kafka
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: admin
      port: 9644
      protocol: TCP
      targetPort: 9644
    - name: rpc
      port: 33145
      protocol: TCP
      targetPort: 33145
    - name: pandaproxy
      port: 8082
      protocol: TCP
      targetPort: 8082
    publishNotReadyAddresses: true
    selector:
      app: redpanda
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
