apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: OIDC_CLIENT_ID,OIDC_CLIENT_SECRET
  name: dex-oidc-client
  namespace: auth
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: DEX_USER_PASSWORD
  name: dex-passwords
  namespace: auth
type: Opaque
