apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: auth
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: dex
      namespace: auth
kind: List
metadata:
  resourceVersion: ""
