apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
        volume.kubernetes.io/selected-node: aiot-worker-01
        volume.kubernetes.io/storage-provisioner: linstor.csi.linbit.com
      finalizers:
        - kubernetes.io/pvc-protection
      name: gitea-data-piraeus
      namespace: gitea
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: piraeus-r2
      volumeMode: Filesystem
      volumeName: pvc-27976678-7d15-4989-99f4-0b94c9ec069c
kind: List
metadata:
  resourceVersion: ""
