apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: gitea.35.241.255.137.nip.io
    cert-manager.io/certificate-name: tls-gitea
    cert-manager.io/common-name: gitea.35.241.255.137.nip.io
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/uri-sans: ''
    aiot.platform/data-keys: tls.crt,tls.key
  labels:
    controller.cert-manager.io/fao: 'true'
  name: tls-gitea
  namespace: gitea
type: kubernetes.io/tls
