apiVersion: v1
kind: Secret
metadata:
  name: istio-ca-secret
  namespace: istio-system
  annotations:
    aiot.platform/data-keys: ca-cert.pem,ca-key.pem,cert-chain.pem,key.pem,root-cert.pem
type: istio.io/ca-root
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca-cert.pem,ca.crt,private-key.pem,public-cert.pem,tls.crt,tls.key
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane-routing
  name: routing-serving-certs
  namespace: istio-system
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: kubeflow.35.241.255.137.nip.io
    cert-manager.io/certificate-name: tls-kubeflow
    cert-manager.io/common-name: kubeflow.35.241.255.137.nip.io
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/uri-sans: ''
    aiot.platform/data-keys: tls.crt,tls.key
  labels:
    controller.cert-manager.io/fao: 'true'
  name: tls-kubeflow
  namespace: istio-system
type: kubernetes.io/tls
