apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: cluster-jwks-proxy
      name: cluster-jwks-proxy
      namespace: istio-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: istio-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: istio-ingressgateway
        install.operator.istio.io/owning-resource: installed-state-installed-state
        install.operator.istio.io/owning-resource-namespace: istio-system
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        operator.istio.io/managed: Reconcile
        operator.istio.io/version: 1.22.1
        release: istio
      name: istio-ingressgateway-service-account
      namespace: istio-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: istio-reader
        install.operator.istio.io/owning-resource: installed-state-installed-state
        install.operator.istio.io/owning-resource-namespace: istio-system
        istio.io/rev: default
        operator.istio.io/component: Base
        operator.istio.io/managed: Reconcile
        operator.istio.io/version: 1.22.1
        release: istio
      name: istio-reader-service-account
      namespace: istio-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: istiod
        install.operator.istio.io/owning-resource: installed-state-installed-state
        install.operator.istio.io/owning-resource-namespace: istio-system
        istio.io/rev: default
        operator.istio.io/component: Pilot
        operator.istio.io/managed: Reconcile
        operator.istio.io/version: 1.22.1
        release: istio
      name: istiod
      namespace: istio-system
kind: List
metadata:
  resourceVersion: ""
