puppetserver:
  global:
    postgresql:
      auth:
        username: puppetdb
        password: "unbreakablePassword"
        database: puppetdb
  puppetserver:
    name: puppetserver
    fqdns:
      alternateServerNames: "puppet.46.4.123.8.nip.io,puppet"
  puppetdb:
    extraEnv:
      PUPPETDB_POSTGRES_HOSTNAME: pg-cluster-rw.databases.svc.cluster.local
    credentials:
      puppetdb:
        postgres: "PuppetDb2026!"
        admin: "PuppetAdmin2026!"
  postgres:
    credentials:
      postgres:
        postgres: "PostgresRoot2026!"
        puppetdb: "PuppetDb2026!"
    storage:
      storageClass: local-path
      size: 5Gi
  r10k:
    codeStorage:
      storageClass: local-path
      size: 1Gi
  postgresql:
    enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 15.9.0-debian-12-r0
    primary:
      persistence:
        storageClass: local-path
        size: 10Gi
    networkPolicy:
      enabled: false
    volumePermissions:
      image:
        registry: docker.io
        repository: bitnamilegacy/os-shell
        tag: 12-debian-12-r19

