apiVersion: v1
kind: Secret
metadata:
  name: cnpg-ca-secret
  namespace: cnpg-system
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: cnpg-controller-manager
    uid: e1c5d8b5-760e-40b8-b228-5645bfdfee19
  annotations:
    aiot.platform/data-keys: ca.crt,ca.key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-webhook-cert
  namespace: cnpg-system
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: cnpg-controller-manager
    uid: e1c5d8b5-760e-40b8-b228-5645bfdfee19
  annotations:
    aiot.platform/data-keys: tls.crt,tls.key
type: kubernetes.io/tls
