pgadmin4:
  env:
    email: admin@example.com
    password: AdminPass123!
    variables:
      - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
        value: "['webserver', 'internal']"
      - name: PGADMIN_CONFIG_WEBSERVER_AUTO_CREATE_USER
        value: "True"
      - name: PGADMIN_CONFIG_WEBSERVER_REMOTE_USER
        value: "'HTTP_X_AUTHENTIK_EMAIL'"
      - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
        value: "False"
      - name: PGADMIN_CONFIG_PROXY_X_HOST_COUNT
        value: "1"
  persistentVolume:
    enabled: true
    storageClass: local-path
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx
      nginx.ingress.kubernetes.io/auth-signin: https://authentik.46.4.123.8.nip.io/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
      nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
    hosts:
      - host: pgadmin.46.4.123.8.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: [pgadmin.46.4.123.8.nip.io]
        secretName: pgadmin-tls
