apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      rancher.io/service-account.secret-ref: cattle-impersonation-system/cattle-impersonation-u-b4qkhsnliz-token-lz9n6
    labels:
      authz.cluster.cattle.io/impersonator: "true"
    name: cattle-impersonation-u-b4qkhsnliz
    namespace: cattle-impersonation-system
    ownerReferences:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: cattle-impersonation-u-b4qkhsnliz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      rancher.io/service-account.secret-ref: cattle-impersonation-system/cattle-impersonation-u-mo773yttt4-token-fb9pf
    labels:
      authz.cluster.cattle.io/impersonator: "true"
    name: cattle-impersonation-u-mo773yttt4
    namespace: cattle-impersonation-system
    ownerReferences:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: cattle-impersonation-u-mo773yttt4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: cattle-impersonation-system
kind: List
metadata:
