apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: k8sgpt
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"k8sgpt-enrichment","namespace":"k8sgpt"}}
    name: k8sgpt-enrichment
    namespace: k8sgpt
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: k8sgpt-k8sgpt
    namespace: k8sgpt
    ownerReferences:
    - apiVersion: core.k8sgpt.ai/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: K8sGPT
      name: k8sgpt
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"k8sgpt-mm-reporter","namespace":"k8sgpt"}}
    name: k8sgpt-mm-reporter
    namespace: k8sgpt
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rbac","app.kubernetes.io/created-by":"k8sgpt-operator","app.kubernetes.io/instance":"k8sgpt-operator","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"k8sgpt-operator","app.kubernetes.io/part-of":"k8sgpt-operator","app.kubernetes.io/version":"0.2.25","helm.sh/chart":"k8sgpt-operator-0.2.27"},"name":"k8sgpt-operator-controller-manager","namespace":"k8sgpt"}}
      meta.helm.sh/release-name: k8sgpt-operator
      meta.helm.sh/release-namespace: k8sgpt
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: k8sgpt-operator
      app.kubernetes.io/instance: k8sgpt-operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k8sgpt-operator
      app.kubernetes.io/part-of: k8sgpt-operator
      app.kubernetes.io/version: 0.2.25
      helm.sh/chart: k8sgpt-operator-0.2.27
    name: k8sgpt-operator-controller-manager
    namespace: k8sgpt
kind: List
metadata:
