apiVersion: v1
kind: Service
metadata:
  name: chef-automate
  namespace: chef
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pe-console
  namespace: chef
spec:
  clusterIP: 10.111.83.4
  clusterIPs:
  - 10.111.83.4
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 4443
    protocol: TCP
    targetPort: 4443
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: puppetserver
  namespace: chef
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: https
    port: 8140
    protocol: TCP
    targetPort: 8140
  sessionAffinity: None
  type: ClusterIP
