apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-0a5aa70f06
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-njd9p
          uid: 91ebe37f-e825-456e-8e6f-cc1d2dfbe283
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-88e91519-5e82-4de7-8ea4-cef21e83360a
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-35376c0cb0
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-push-fxzbt
          uid: edd4e18b-efe7-4deb-a4ee-fe2f0122c454
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-cd5409ec-c349-4d61-a233-c6de3fc972cc
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-4c5547734e
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-frontend-push-jwfgk
          uid: ac9ea678-88c8-4ffa-b3a5-66c1ef9a1e5e
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-473ba6f9-c2c4-4911-9bad-f81c22b8fac8
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-51dc950af2
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-xx7x7
          uid: 2755e11c-b672-4302-89e4-bd8ea9e9df6c
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-f482bc53-9ba7-4cdb-a738-cc104d95ca50
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-53588f3165
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-frontend-push-gqwgr
          uid: 2696b553-aedd-43c1-9f76-349cebb3970a
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-4a609dfd-f563-429f-a52b-cb09c833443f
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-5fa950c4e3
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-tft4s
          uid: fc751d0c-a44f-4caf-a810-8f73dde8ddea
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-7282b713-c32d-4985-b7b3-b1ea26945252
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node2
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-64f8bd87ab
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-backend-push-xtmbr
          uid: 48cd38a4-e03d-4f7d-ae88-8c4a45a54a68
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-4d63cb6c-72df-46e7-9ca7-94a898aac5f9
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-935b23e9c9
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-push-vpddp
          uid: 8455011b-3bcf-4e48-9016-4065e0c1e81e
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-a12e569c-7913-48e5-bb46-bd014bc7419a
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-94f874faba
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-sw885
          uid: a904869f-924e-4893-8882-ffa3ee13d56d
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-16db2863-d0b1-4ba9-88f5-fc74de503be4
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node2
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-96d85b625f
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-ts9hp
          uid: 9fa435e3-e7eb-4877-a30e-e6bc10fddf55
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-9dcf8904-b5af-4161-b80a-820721484be0
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-be1b58b3fa
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-frontend-push-b7swr
          uid: 39eee66a-a286-4e00-b51d-a79d72c95537
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-588f213a-629a-4466-801a-051b7d35f7b5
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-c87bb82deb
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-p4ww8
          uid: dfef5733-86d7-4315-9ed8-887e9479dc5a
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-d3a93834-31e4-4474-9a35-b297df7fb773
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-cb47027125
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: hello-aiot-frontend-push-hsfr9
          uid: 345628c4-7711-46f4-86e2-15cb8e94db0a
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-10b8a387-2d7d-44c3-ba51-670a0ca3cfa0
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
        volume.kubernetes.io/selected-node: oci-e5-node1
        volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      finalizers:
        - kubernetes.io/pvc-protection
      name: pvc-d5f4ef46f7
      namespace: default-tenant
      ownerReferences:
        - apiVersion: tekton.dev/v1
          blockOwnerDeletion: true
          controller: true
          kind: PipelineRun
          name: managed-299d7
          uid: bf5c7b12-891b-42de-9607-eb222e7bb8fc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem
      volumeName: pvc-2fd187bf-205f-4b10-81ae-fdeb15ba3a83
kind: List
metadata:
  resourceVersion: ""
