apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      labels:
        argocd.argoproj.io/instance: karpor-ingress
      name: karpor-tls
      namespace: karpor
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Ingress
          name: karpor
          uid: b65d6ac9-693e-4679-824d-64ef5db4b5fc
    spec:
      dnsNames:
        - karpor.35.241.255.137.nip.io
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: karpor-tls
      usages:
        - digital signature
        - key encipherment
kind: List
metadata:
  resourceVersion: ""
