apiVersion: v1
items:
  - apiVersion: v1
    data:
      root-cert.pem: |
        -----BEGIN CERTIFICATE-----
        MIIC/DCCAeSgAwIBAgIQRRabq+yMXyRafntlJeCv/jANBgkqhkiG9w0BAQsFADAY
        MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTI2MDQxNDAyMjQyMVoXDTM2MDQx
        MTAyMjQyMVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAJ/zEnuc8b/DvAWOjZMkKqHgP4Poo94NHrE7KVEu
        j9RQ00TmBUN1eMjFJbOUR3M/EHbjrjXO4asqC6B9X3zITZ1r1nGkjZBd2vm1b7cW
        H6cMKySq/ILkvmO+y7k/IunD8re+jDoXdvRnR1lLUHBwp9JISqm9EK6dt5Xc6BVZ
        v8cDSFCeON+RUVHhIh2p/AYLkNamHfRb/EbCWn5jXR43udBrjWd+5Ack4OgNK/QL
        UUIUbzsfcQz70ZXW0SIs/NGq7/AEFcFMo31E/IUpVHslROq/vINS9ARU28FndRsF
        ORTEFwZKtEFpoiYG3uLSlvUrl+n6obYw0t274HMn1wSJCJUCAwEAAaNCMEAwDgYD
        VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOw7AyQg+Bl3
        XZ0MvJUVjwL6OBrbMA0GCSqGSIb3DQEBCwUAA4IBAQCXFXruCYGPYjgUg0B2CAQR
        y1rzx+fiNZx5AuKoS/RFaKjhMkPtGD2Oi03RI8Rz0I+hiuOGrj4d0sfiYOfpZTb9
        nb0RN19QhFTXmcGrM1asFmTCEoIOktsE4S3xcMk5X6/rc+PxcBvBZsi54PC9gA+h
        P6j5OVgg8gkRyh646mtR9fDobGyZ12hOTHF4LJkGpOko/tG+/P8pmyLtOsBH6f7G
        y69tNOwXl5M6ujtK+oE09hGStwP0YW6dGLuqNFspcn8Nmf63PeHk+pFTI2RH5tG+
        H1YZsJ7+UfhcJ5PnzjHHBIHrIurvLcuiwDyBPW18bJAV6xLC0VgDrCAxEDOJD6T4
        -----END CERTIFICATE-----
    kind: ConfigMap
    metadata:
      labels:
        istio.io/config: "true"
      name: istio-ca-root-cert
      namespace: karpor
  - apiVersion: v1
    data:
      config: |-
        apiVersion: v1
        clusters:
        - cluster:
            insecure-skip-tls-verify: true
            server: https://karpor-server.karpor.svc:7443
          name: karpor
        contexts:
        - context:
            cluster: karpor
            user: karpor
          name: default
        current-context: default
        kind: Config
        users:
        - name: karpor
          user:
            client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lJQ3pnT084OUpuWXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWdGdzB5TmpBME1qWXhOelUwTURsYUdBOHlNVEkyTURRd01qRTNOVFF3T1ZvdwpOREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhHVEFYQmdOVkJBTVRFR3QxWW1WeWJtVjBaWE10CllXUnRhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3QwM0paMzFOMEYzcXgKdDZyTjV3TWtsaHY3dDVpakc3YnVudGtwVkF5QVo0Zjh2UGg0Nm4wWXVMenplSHQ4dDE4QXZNRFpjR0lhSlhrQgowaDRJaERJeWRRN05LR3pPUGdlMXhPUDFnbWJxbC9vMzJMT1JtUm5hcndwcE1KMUpzZ1VDL3RXQXFnNGpVVXM3CjFZdDRVbGdmbGZQYW5JMEhIN1VIMEFVVXhyemlBV0J2VHovOFBwOUFtVElwRjBsWFRhV3c4K3hlYmZYR28rTzQKLzRjY1ZnK25taGxmMHYwQUF2QXd2STF3VTlhSWxJbmRPamJoR2FSZGpkS1pNK2JUQ3Z4b2xXWU8yVG02SGd6eQpwWFJTWWc4L01RTjdZQWY4YmVoMjFFVFF6T1IxN1BUaEJ5OHBxQmlzK1RwbEkzSnZWTEhseEo0QzdDWHZoK0lWCk1UN3BrUlUxQWdNQkFBR2pTREJHTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQWZCZ05WSFNNRUdEQVdnQlE1aTE5K0xHUGdDaGFISC9aeW1VKy85T2ViZXpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFFV1ptZkJxMUFsbFlOTFg0UU9LRGhyWThmVThVdnA2VlJjUTcyMzU3cndrUEpJVkQ5bzZMClUyZ3FTVmZFdTFIcDJMV01wdm9DRzhtaG5SN0JBR1J2K2xiMnpQRjNNbGNKNUc5cTJ2UjZXSlBnOHRQSWFwd3YKQ3dwWm5Eb0h1ckk0ZmdjajFTOGtlaHFaNXdoYWR3MDdYaUl2M3RQZzIwYU5uQTVMRFVBclV0VUl4ZFhYNzdwYwpKdFZ5TzlRK0FmOTZSK1pQbjk0RldYRHRSSU41bW1rdEZ3VkwvR01KaTdEU1dmSFFWLzVCbDBxaDZpNVVQRFgzCjU3bUI5UHF0cmh2T3lHb3Rpb3V3SFNBVnFyWVNmK1dDa2dFUXZPMUY5ZDJ4R09NeEJKUXNtUXh2dDNzYlFSaUMKTDBVdU1xa3ZHUkNILzk5QnNsdXBHWW0rVGhtY05wZjFlQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcmROeVdkOVRkQmQ2c2JlcXplY0RKSlliKzdlWW94dTI3cDdaS1ZRTWdHZUgvTHo0CmVPcDlHTGk4ODNoN2ZMZGZBTHpBMlhCaUdpVjVBZEllQ0lReU1uVU96U2hzemo0SHRjVGo5WUptNnBmNk45aXoKa1prWjJxOEthVENkU2JJRkF2N1ZnS29PSTFGTE85V0xlRkpZSDVYejJweU5CeCsxQjlBRkZNYTg0Z0ZnYjA4LwovRDZmUUpreUtSZEpWMDJsc1BQc1htMzF4cVBqdVArSEhGWVBwNW9aWDlMOUFBTHdNTHlOY0ZQV2lKU0ozVG8yCjRSbWtYWTNTbVRQbTB3cjhhSlZtRHRrNXVoNE04cVYwVW1JUFB6RURlMkFIL0czb2R0UkUwTXprZGV6MDRRY3YKS2FnWXJQazZaU055YjFTeDVjU2VBdXdsNzRmaUZURSs2WkVWTlFJREFRQUJBb0lCQUhvd0RFM0lnbTAwby9hUQoyT3ZyMjNXNFh1dE9YMmtvYmlyR1ZuaUtzRThDZDhEZFJQd2FPTjFMM3VaMlpyZUFYck94K3czZHhkZ0RSMUJVClZ2QTluTnVERldoNVppS0R6LytoNjJ3RXdqdGRvWEhvVGpHbW9WbnJlVElBRGxCalpzcDRQN1ExMWNKVnZzRE0KbDBGNUFLRVRVMXIwZU4zdEY5L3FCZWhZMnlVeUVlTnFwbW5zcnVLRzVMRTY0ZlFpMmdyYjczRVptTXVkd3JsWQpQUTJyaHAxNWtPZk9GM2V5RGRUdkRudlQyaVE5L0ZwUlNYbzVMWTdFM3FBL0t4SHR3Q002UkVNdHpja0RxRFZwCmY2V1FHa1g1QjI2NEhGbS9hREhGa3BwYVBHVVljMGJVNDhXSENGN1BvZWN6RUsvZkJGaUNXbUdnVUJrUGlESmYKUm1nUHI0RUNnWUVBMkNOMktidFN4eC9DekdKa0Zsa2Z2RXd2NU1qMlQ1OUdwaDF2NUNGcjhzQVNVRmNiRzl4TwpaOUszbktMWUZKaHhlUjdSL1N2ZVJ6TDZKMlJzSmlSUU0zRUhscTcwMXpBR2NtVXYrbXQyOGtGbWNVcVllV29wCjhlUlRwbDNBcS9WYyttbzNsekhCUlp2VDYvb05UVmdNRmFIZEJCTTVqd3V5YUtZMnNsOXl0dzBDZ1lFQXplSkkKd0JLSlUwRHN3MlpkdksyN1VHN2tCbkhKSUZ0TUFEMjRYZ1NyWEpVRTN3M3MybFBveUVHVnNWTmZPbVFmUFNkVwpJZ211L3NsV2lMTzhtUmFlYVIxSW82cVJGMWsvenJHTU5hVWYrTzBPdHQ0LzNDNWxlT040SURIWks0Q2xpWmdoCk9QOHk5NVBOVFRsMzNCOVBRV0NuR2c4R0xldnkvSFVCWkJEbHpNa0NnWUE3MXBXQU9EeFNwSmhwdlZPNFhEUk4KRFVxMUxHNEUzVFBTQ1pSUXRIQU9aTjZ0SDNDQjVoeE80aWV6VmVJODBYZVk4TTl5S0JNQjR6c2ViTThFUUVsego5SGNGWUtxb2FNTmdLR09BRVFCOVVWM3JQNXUzQVkxYlNydGQ4OWJEeE1wWkNjOGFMTXcxV1U3eXBlZkk0ZmQyCmhibUt4MGZJTXBUU0pESkFiK3h5Z1FLQmdEOEpnOERiYkJTRGtucVpneVhjQTdneTI3cGxhSEZ4d3Fsb1BHVDkKQlFMSjFiMzk0NEZObzc1ODVqcHZEbjh3WEtnNnZSS2E2R3UyZGJwUlhmTjVpM01mdGpmMlo0cEFsMXJQM2VBbQorTTBjdUI2aG1lZnVoTDhvMW9UMC9rdGxqa204dko5WTg5Lzk3eVF2N2xVRmVSekpYU0NMYlJidVlXMk8zYWduCnpGU1JBb0dBYURYa2hRb0pJMzJINndFVCs1Z3NQeXlaMjN0ZFJRbklTL1Qza2VqWkdPZmg0S1dLejhRNktCdU8KMXFOb05kS0Y2Y0FDU3VVa3dLWGFJSDdBdlFYOGpodjJrQzZveDhrV1VXQ1RzQ3NIZHcwUUFCUDZJOW1KcUY2QwpPMW1OaGt3cmJjMUJhQWNzdk5SU09OVnd0TUlCZ3BNUHhhZlVraDhBM0R4QVY5aGhkYVU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
    kind: ConfigMap
    metadata:
      name: karpor-kubeconfig
      namespace: karpor
  - apiVersion: v1
    data:
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDBTCCAe2gAwIBAgIICFZ7LDONfKkwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
        AxMKa3ViZXJuZXRlczAeFw0yNjA0MTQwMTEyMjlaFw0zNjA0MTEwMTE3MjlaMBUx
        EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQCgWEcelObEPb57j3B7s7K16UNHMXZZETdrPKjbPYQ2u88dvocDWXgX+S9G
        HzJ/81TqbJCft0kT4QiYqU32mKQSy/ncsA6UQGSBVlTAfzpDfM/PSL8DIyA59U6C
        0OgPMcK3ot99ZBiv/LTkDfIyw5y1uc201DYVQ9kAyNAcqCjubtbYHiHOa/IJbVZh
        CK8PlpvHj7JBncsnb08EUEHvI5vVYE+hKJKIArqWyPEfG0oB/ZilmR3B3gVF2ev8
        k/G1FZ2Jx8ln5ZDdbGYB+VxZ7Bio4PAS0TUplA/xp9qJUXBJjhIZbAy1Xfpv3PLB
        1NFd7xlpAa8UErTFxGXMTydi6mTvAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
        BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTY9OiYpct4GkXOdcDgjJsBhNmGxjAV
        BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAYdZl446N4
        4VF0kezqF8wSivD07V9WdWi+SMLiOHCeMm1p1S0gEK3S9H3wsDrF7cKnomFqBwAg
        46Sv0iu3hel8w+qg5F1UOoy4PUFUkwx3pNBaA+s4IjkR5yERwpwDGqNDUmlkL3PJ
        qDkvCDBgU9sEeY2V+2GBwkEaUiwKt7xqiw6t60NkFIpEvm8HQNDU6nXarceAfYOJ
        fUNowmy6m8xS/FivcYs+Wqvv5yu+mwtvkxy9t026y+XCT+R8VQLG/QabiQRolzH6
        PSjYAW4HZYcjaXqAmQk7N8kElJ1hkymxppUQWvfpN1LhYs/3YCULS+fmzLR/w6ZO
        szTc1uZpUffa
        -----END CERTIFICATE-----
    kind: ConfigMap
    metadata:
      annotations:
        kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
      name: kube-root-ca.crt
      namespace: karpor
kind: List
metadata:
  resourceVersion: ""
