apiVersion: v1
items:
  - apiVersion: v1
    data:
      apiServerCA: REDACTED
      apiServerURL: REDACTED
      token: REDACTED
      value: REDACTED
    kind: Secret
    metadata:
      annotations:
        field.cattle.io/projectId: local:p-565hx
      labels:
        cluster.x-k8s.io/cluster-name: local
      name: local-kubeconfig
      namespace: fleet-local
      ownerReferences:
        - apiVersion: provisioning.cattle.io/v1
          kind: Cluster
          name: local
          uid: 209da594-dc51-4fad-b323-b3d90b8b445d
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
