apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: {{ .Values.awx.adminUser | quote }}
  admin_password_secret: awx-admin-password
  secret_key_secret: awx-secret-key
  postgres_configuration_secret: awx-postgres-configuration
  postgres_keepalives: true
  service_type: ClusterIP
  ingress_type: ingress
  ingress_class_name: nginx
  hostname: {{ .Values.awx.hostname | quote }}
  ingress_tls_secret: awx-tls
  ingress_annotations: |
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $awx_sso 0;
      if ($http_cookie !~* "awx_sessionid=") { set $awx_sso 1; }
      if ($request_uri ~ "^/sso/") { set $awx_sso 0; }
      if ($request_uri ~ "^/static/") { set $awx_sso 0; }
      if ($request_uri ~ "^/api/") { set $awx_sso 0; }
      if ($request_uri ~ "^/websocket/") { set $awx_sso 0; }
      if ($arg_local_login = "1") { set $awx_sso 0; }
      if ($awx_sso = 1) { return 302 /sso/login/saml/?idp=authentik; }
  no_log: false
  replicas: 1
  web_resource_requirements:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 2Gi
  task_resource_requirements:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 1Gi
  redis_resource_requirements:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 128Mi
  init_container_resource_requirements:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 512Mi
  extra_settings:
    - setting: SOCIAL_AUTH_OIDC_KEY
      value: '"{{ .Values.oidc.clientId }}"'
    - setting: SOCIAL_AUTH_OIDC_SECRET
      value: '"{{ .Values.oidc.clientSecret }}"'
    - setting: SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
      value: '"{{ .Values.oidc.issuer }}"'
    - setting: SOCIAL_AUTH_OIDC_VERIFY_SSL
      value: 'True'
{{- with .Values.nodeSelector }}
  node_selector: |
{{ toYaml . | indent 4 }}
{{- end }}
