apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-0a5aa70f06
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-njd9p
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-88e91519-5e82-4de7-8ea4-cef21e83360a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-35376c0cb0
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-push-fxzbt
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-cd5409ec-c349-4d61-a233-c6de3fc972cc
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-47831c8db5
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-push-pfs4p
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-c6ac5a07-cf66-47a4-8612-b17c97912799
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-4c5547734e
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-frontend-push-jwfgk
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-473ba6f9-c2c4-4911-9bad-f81c22b8fac8
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-51dc950af2
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-xx7x7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-f482bc53-9ba7-4cdb-a738-cc104d95ca50
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-53588f3165
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-frontend-push-gqwgr
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-4a609dfd-f563-429f-a52b-cb09c833443f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-5fa950c4e3
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-tft4s
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-7282b713-c32d-4985-b7b3-b1ea26945252
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-64f8bd87ab
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-backend-push-xtmbr
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-4d63cb6c-72df-46e7-9ca7-94a898aac5f9
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-7b127f963b
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-push-w9b6d
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-64a227a5-0177-4fff-bb88-7de96f461f8a
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-be1b58b3fa
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: hello-aiot-frontend-push-b7swr
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-588f213a-629a-4466-801a-051b7d35f7b5
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-c87bb82deb
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-p4ww8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-d3a93834-31e4-4474-9a35-b297df7fb773
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-cdb3ea13e0
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-8bhtz
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-b70cf1e2-61f5-4c65-8171-1b9a1352ea88
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-d3848b25bd
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-dw4j8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-63d2b839-032a-404e-888d-20dcc6b271ad
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: oci-e5-node1
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    finalizers:
    - kubernetes.io/pvc-protection
    name: pvc-d5f4ef46f7
    namespace: default-tenant
    ownerReferences:
    - apiVersion: tekton.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: managed-299d7
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-2fd187bf-205f-4b10-81ae-fdeb15ba3a83
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
