apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca-cert.pem,ca.crt,private-key.pem,public-cert.pem,tls.crt,tls.key
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane
  name: knative-serving-certs
  namespace: knative-serving
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca-cert.pem,server-cert.pem,server-key.pem
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.12.3
    networking.knative.dev/ingress-provider: istio
  name: net-istio-webhook-certs
  namespace: knative-serving
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca-cert.pem,ca.crt,private-key.pem,public-cert.pem,tls.crt,tls.key
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane-routing
  name: routing-serving-certs
  namespace: knative-serving
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: private-key.pem,public-cert.pem,tls.crt,tls.key
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane
  name: serving-certs-ctrl-ca
  namespace: knative-serving
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca-cert.pem,server-cert.pem,server-key.pem
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.12.4
  name: webhook-certs
  namespace: knative-serving
type: Opaque
