apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      ca.crt: REDACTED
      private-key.pem: REDACTED
      public-cert.pem: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"networking.internal.knative.dev/certificate-uid":"serving-certs","serving-certs-ctrl":"data-plane"},"name":"knative-serving-certs","namespace":"knative-serving"}}
      labels:
        networking.internal.knative.dev/certificate-uid: serving-certs
        serving-certs-ctrl: data-plane
      name: knative-serving-certs
      namespace: knative-serving
    type: Opaque
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"net-istio","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.12.3","networking.knative.dev/ingress-provider":"istio"},"name":"net-istio-webhook-certs","namespace":"knative-serving"}}
      labels:
        app.kubernetes.io/component: net-istio
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.12.3
        networking.knative.dev/ingress-provider: istio
      name: net-istio-webhook-certs
      namespace: knative-serving
    type: Opaque
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      ca.crt: REDACTED
      private-key.pem: REDACTED
      public-cert.pem: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"networking.internal.knative.dev/certificate-uid":"serving-certs","serving-certs-ctrl":"data-plane-routing"},"name":"routing-serving-certs","namespace":"knative-serving"}}
      labels:
        networking.internal.knative.dev/certificate-uid: serving-certs
        serving-certs-ctrl: data-plane-routing
      name: routing-serving-certs
      namespace: knative-serving
    type: Opaque
  - apiVersion: v1
    data:
      private-key.pem: REDACTED
      public-cert.pem: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"networking.internal.knative.dev/certificate-uid":"serving-certs","serving-certs-ctrl":"data-plane"},"name":"serving-certs-ctrl-ca","namespace":"knative-serving"}}
      labels:
        networking.internal.knative.dev/certificate-uid: serving-certs
        serving-certs-ctrl: data-plane
      name: serving-certs-ctrl-ca
      namespace: knative-serving
    type: Opaque
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.12.4"},"name":"webhook-certs","namespace":"knative-serving"}}
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.12.4
      name: webhook-certs
      namespace: knative-serving
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
