apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-5.9.14"},"name":"jenkins-casc-reload","namespace":"jenkins"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","watch","list"]}]}
      meta.helm.sh/release-name: jenkins
      meta.helm.sh/release-namespace: jenkins
    labels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jenkins
      helm.sh/chart: jenkins-5.9.18
    name: jenkins-casc-reload
    namespace: jenkins
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - watch
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-5.9.14"},"name":"jenkins-schedule-agents","namespace":"jenkins"},"rules":[{"apiGroups":[""],"resources":["pods","pods/exec","pods/log","persistentvolumeclaims","events"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods","pods/exec","persistentvolumeclaims"],"verbs":["create","delete","deletecollection","patch","update"]}]}
      meta.helm.sh/release-name: jenkins
      meta.helm.sh/release-namespace: jenkins
    labels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: jenkins
      helm.sh/chart: jenkins-5.9.18
    name: jenkins-schedule-agents
    namespace: jenkins
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    - pods/log
    - persistentvolumeclaims
    - events
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    - persistentvolumeclaims
    verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
kind: List
metadata:
