apiVersion: v1
kind: Service
metadata:
  name: aiot-pipeline-demo
  namespace: aiot-demo
spec:
  clusterIP: 10.101.50.48
  clusterIPs:
  - 10.101.50.48
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: aiot-pipeline-demo
  sessionAffinity: None
  type: ClusterIP
