apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-event-bridge
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: monitoring
  source:
    repoURL: https://github.com/ondrejnr/aiot-platform.git
    targetRevision: main
    path: apps/prometheus-event-bridge
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-event-bridge
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff: { duration: 30s, factor: 2, maxDuration: 5m }
