apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776446944'
    name: vui
    owner: helm
    status: superseded
    version: '1'
  name: sh.helm.release.v1.vui.v1
  namespace: vui
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    modifiedAt: '1776446944'
    name: vui
    owner: helm
    status: deployed
    version: '2'
  name: sh.helm.release.v1.vui.v2
  namespace: vui
  annotations:
    aiot.platform/data-keys: release
type: helm.sh/release.v1
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: vui
    meta.helm.sh/release-namespace: vui
    aiot.platform/data-keys: DEFAULT_ADMIN_PASSWORD,DEFAULT_ADMIN_USERNAME,RESTIC_PASSWORD
  labels:
    app.kubernetes.io/instance: vui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vui
    app.kubernetes.io/version: 0.4.1
    helm.sh/chart: vui-1.0.6
  name: vui-api-secret
  namespace: vui
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: auth
  name: vui-basic-auth
  namespace: vui
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: vui.35.241.255.137.nip.io
    cert-manager.io/certificate-name: vui-tls
    cert-manager.io/common-name: vui.35.241.255.137.nip.io
    cert-manager.io/ip-sans: ''
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/uri-sans: ''
    aiot.platform/data-keys: tls.crt,tls.key
  labels:
    controller.cert-manager.io/fao: 'true'
  name: vui-tls
  namespace: vui
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: vui
    meta.helm.sh/release-namespace: vui
    aiot.platform/data-keys: APPRISE
  labels:
    app.kubernetes.io/instance: vui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vui
    app.kubernetes.io/version: 0.4.1
    helm.sh/chart: vui-1.0.6
  name: vui-watchdog-secret
  namespace: vui
type: Opaque
