apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: vui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: vui
    meta.helm.sh/release-namespace: vui
  labels:
    app.kubernetes.io/instance: vui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vui
    app.kubernetes.io/version: 0.4.1
    helm.sh/chart: vui-1.0.6
  name: vui-admin-sa
  namespace: vui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: vui
    meta.helm.sh/release-namespace: vui
  labels:
    app.kubernetes.io/instance: vui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vui
    app.kubernetes.io/version: 0.4.1
    helm.sh/chart: vui-1.0.6
  name: vui-readonly-sa
  namespace: vui
