apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      cattle.io/creator: norman
    name: local-fleet-local-owner-cluster-owner
    namespace: local
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      kind: ClusterRoleTemplateBinding
      name: local-fleet-local-owner
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cluster-owner
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: u-mo773yttt4
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      cattle.io/creator: norman
    name: u-b4qkhsnliz-admin-cluster-owner
    namespace: local
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      kind: ClusterRoleTemplateBinding
      name: u-b4qkhsnliz-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cluster-owner
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: u-b4qkhsnliz
kind: List
metadata:
