apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      cattle.io/creator: norman
    name: cluster-owner
    namespace: local
  rules:
  - apiGroups:
    - management.cattle.io
    resources:
    - clusterscans
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - clusterregistrationtokens
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - clusterroletemplatebindings
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - etcdbackups
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - nodes
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - nodepools
    verbs:
    - '*'
  - apiGroups:
    - management.cattle.io
    resources:
    - projects
    verbs:
    - '*'
    - updatepsa
  - apiGroups:
    - rke.cattle.io
    resources:
    - etcdsnapshots
    verbs:
    - '*'
    - get
    - list
    - watch
kind: List
metadata:
