apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"otel-agent","app.kubernetes.io/instance":"k8s-infra","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"k8s-infra","app.kubernetes.io/version":"0.139.0","helm.sh/chart":"k8s-infra-0.15.0"},"name":"k8s-infra-otel-agent","namespace":"signoz"}}
      meta.helm.sh/release-name: k8s-infra
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: otel-agent
      app.kubernetes.io/instance: k8s-infra
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k8s-infra
      app.kubernetes.io/version: 0.139.0
      helm.sh/chart: k8s-infra-0.15.0
    name: k8s-infra-otel-agent
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"otel-deployment","app.kubernetes.io/instance":"k8s-infra","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"k8s-infra","app.kubernetes.io/version":"0.139.0","helm.sh/chart":"k8s-infra-0.15.0"},"name":"k8s-infra-otel-deployment","namespace":"signoz"}}
      meta.helm.sh/release-name: k8s-infra
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: otel-deployment
      app.kubernetes.io/instance: k8s-infra
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: k8s-infra
      app.kubernetes.io/version: 0.139.0
      helm.sh/chart: k8s-infra-0.15.0
    name: k8s-infra-otel-deployment
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pod-executor
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"signoz","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"signoz","app.kubernetes.io/version":"v0.117.1","helm.sh/chart":"signoz-0.117.1"},"name":"signoz","namespace":"signoz"}}
      meta.helm.sh/release-name: signoz
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: signoz
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: signoz
      app.kubernetes.io/version: v0.117.1
      helm.sh/chart: signoz-0.117.1
    name: signoz
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"clickhouse","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"clickhouse","app.kubernetes.io/version":"24.1.2","helm.sh/chart":"clickhouse-24.1.18"},"name":"signoz-clickhouse","namespace":"signoz"}}
      meta.helm.sh/release-name: signoz
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: clickhouse
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.1.2
      helm.sh/chart: clickhouse-24.1.18
    name: signoz-clickhouse
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"operator","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"clickhouse","app.kubernetes.io/version":"24.1.2","clickhouse.altinity.com/chop":"0.21.2","helm.sh/chart":"clickhouse-24.1.18"},"name":"signoz-clickhouse-operator","namespace":"signoz"}}
      meta.helm.sh/release-name: signoz
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.1.2
      clickhouse.altinity.com/chop: 0.21.2
      helm.sh/chart: clickhouse-24.1.18
    name: signoz-clickhouse-operator
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"otel-collector","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"signoz","app.kubernetes.io/version":"v0.117.1","helm.sh/chart":"signoz-0.117.1"},"name":"signoz-otel-collector","namespace":"signoz"}}
      meta.helm.sh/release-name: signoz
      meta.helm.sh/release-namespace: signoz
    labels:
      app.kubernetes.io/component: otel-collector
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: signoz
      app.kubernetes.io/version: v0.117.1
      helm.sh/chart: signoz-0.117.1
    name: signoz-otel-collector
    namespace: signoz
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Force=true,Replace=true
      helm.sh/hook: pre-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
    labels:
      app.kubernetes.io/component: signoz-telemetrystore-migrator
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: signoz
      app.kubernetes.io/version: v0.117.1
      helm.sh/chart: signoz-0.117.1
    name: signoz-telemetrystore-migrator
    namespace: signoz
kind: List
metadata:
