apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ca.crt,token
  name: automate-event-stream
  namespace: habitat-demo
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: leaf.crt
  name: automate-leaf-cert
  namespace: habitat-demo
type: Opaque
