apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/allow-direct-injection: "true"
        field.cattle.io/projectId: local:p-wpbsz
      labels:
        app.kubernetes.io/managed-by: cert-manager
      name: cert-manager-webhook-ca
      namespace: cert-manager
    type: Opaque
  - apiVersion: v1
    data:
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        field.cattle.io/projectId: local:p-wpbsz
      name: letsencrypt-prod-key
      namespace: cert-manager
    type: Opaque
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: ""
        cert-manager.io/certificate-name: selfsigned-ca
        cert-manager.io/common-name: selfsigned-ca
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: self-signed-cluster-issuer
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: root-secret
      namespace: cert-manager
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: trust-manager.cert-manager.svc
        cert-manager.io/certificate-name: trust-manager
        cert-manager.io/common-name: trust-manager.cert-manager.svc
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: Issuer
        cert-manager.io/issuer-name: trust-manager
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: trust-manager-tls
      namespace: cert-manager
    type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
