apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/allow-direct-injection: 'true'
    field.cattle.io/projectId: local:p-wpbsz
    aiot.platform/data-keys: ca.crt,tls.crt,tls.key
  labels:
    app.kubernetes.io/managed-by: cert-manager
  name: cert-manager-webhook-ca
  namespace: cert-manager
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-wpbsz
    aiot.platform/data-keys: tls.key
  name: letsencrypt-prod-key
  namespace: cert-manager
type: Opaque
