apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"pipelines-as-code","app.kubernetes.io/version":"v0.42.0"},"name":"pipelines-as-code-webhook-certs","namespace":"pipelines-as-code"}}
      labels:
        app.kubernetes.io/part-of: pipelines-as-code
        app.kubernetes.io/version: v0.42.0
      name: pipelines-as-code-webhook-certs
      namespace: pipelines-as-code
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
