mattermost-team-edition:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - mattermost.46.4.123.8.nip.io
    tls:
      - hosts: [mattermost.46.4.123.8.nip.io]
        secretName: mattermost-tls
