mattermost-team-edition:
  externalDB:
    enabled: true
    externalDriverType: postgres
    externalConnectionString: "mattermost:MattermostPg2026!@pg-cluster-rw.databases.svc.cluster.local:5432/mattermost?sslmode=disable&connect_timeout=10"
  mysql:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - mattermost.46.4.123.8.nip.io
    tls:
      - hosts: [mattermost.46.4.123.8.nip.io]
        secretName: mattermost-tls
