apiVersion: v2
name: zabbix-overlay
description: aiot-platform overlay for zabbix
type: application
version: 1.0.0
appVersion: "7.2.0"
dependencies:
  - name: zabbix
    version: "7.2.0"
    repository: https://zabbix-community.github.io/helm-zabbix
