zabbix:
  zabbixImageTag: alpine-7.0.29
  postgresAccess:
    host: pg-cluster-rw.databases.svc.cluster.local
    port: "5432"
    user: zabbix
    password: "e982317cfac9d8d8208183a8fd037e56"
    database: zabbix
    schema: public
  postgresql:
    enabled: false
  zabbixServer:
    extraEnv:
      - name: ZBX_CACHESIZE
        value: "256M"
      - name: ZBX_VALUECACHESIZE
        value: "256M"
      - name: ZBX_HISTORYCACHESIZE
        value: "64M"
      - name: ZBX_TRENDCACHESIZE
        value: "32M"
      - name: ZBX_HISTORYINDEXCACHESIZE
        value: "32M"
  zabbixWeb:
    samlCertsSecretName: zabbix-saml-certs
    extraEnv:
      - name: ZBX_SERVER_HOST
        value: zabbix-zabbix-server
      - name: ZBX_SERVER_PORT
        value: "10051"
      - name: ZBX_SSO_SETTINGS
        value: >-
          {"strict":true,"baseurl":"https://zabbix.46.4.123.8.nip.io/","use_proxy_headers":true,"sp":{"entityId":"zabbix","assertionConsumerService":{"url":"https://zabbix.46.4.123.8.nip.io/index_sso.php?acs","binding":"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"}},"idp":{"entityId":"zabbix","singleSignOnService":{"url":"https://authentik.46.4.123.8.nip.io/application/saml/zabbix/sso/binding/post/","binding":"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"}}}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: zabbix.46.4.123.8.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: [zabbix.46.4.123.8.nip.io]
        secretName: zabbix-tls
