apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    name: default
    namespace: cattle-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"rancher","chart":"rancher-2.13.3","heritage":"Helm","release":"rancher"},"name":"rancher","namespace":"cattle-system"}}
      meta.helm.sh/release-name: rancher
      meta.helm.sh/release-namespace: cattle-system
      rancher.io/service-account.secret-ref: cattle-system/rancher-token-tg7nw
    labels:
      app: rancher
      app.kubernetes.io/managed-by: Helm
      chart: rancher-2.13.3
      heritage: Helm
      release: rancher
    name: rancher
    namespace: cattle-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"rancher-webhook","namespace":"cattle-system"}}
      meta.helm.sh/release-name: rancher-webhook
      meta.helm.sh/release-namespace: cattle-system
    labels:
      app.kubernetes.io/managed-by: Helm
    name: rancher-webhook
    namespace: cattle-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      cattle.io/description: SA which can be impersonated to bypass rancher-webhook
        validation
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"cattle.io/description":"SA which can be impersonated to bypass rancher-webhook validation"},"name":"rancher-webhook-sudo","namespace":"cattle-system"}}
      meta.helm.sh/release-name: rancher-webhook
      meta.helm.sh/release-namespace: cattle-system
    labels:
      app.kubernetes.io/managed-by: Helm
    name: rancher-webhook-sudo
    namespace: cattle-system
kind: List
metadata:
