apiVersion: v1
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-wpbsz
    aiot.platform/data-keys: application_default_credentials.json
  name: gc-secret
  namespace: kube-system
type: Opaque
