apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      field.cattle.io/publicEndpoints: '[{"addresses":["35.241.255.137"],"port":443,"protocol":"HTTPS","serviceName":"karpor:karpor-server","ingressName":"karpor:karpor","hostname":"karpor.35.241.255.137.nip.io","path":"/","allNodes":false}]'
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        proxy_set_header Accept-Encoding "";
        sub_filter "isUnsafeMode:void 0" "isUnsafeMode:!0";
        sub_filter "isLogin:!1" "isLogin:!0";
        sub_filter_once off;
        sub_filter_types text/javascript application/javascript;
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
    labels:
      argocd.argoproj.io/instance: karpor-ingress
    name: karpor
    namespace: karpor
  spec:
    ingressClassName: nginx
    rules:
    - host: karpor.35.241.255.137.nip.io
      http:
        paths:
        - backend:
            service:
              name: karpor-server
              port:
                number: 7443
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - karpor.35.241.255.137.nip.io
      secretName: karpor-tls
  status:
    loadBalancer:
      ingress:
      - ip: 35.241.255.137
kind: List
metadata:
