apiVersion: v1
items:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: tls-webhook
      namespace: chef-webhook
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Ingress
          name: webhook-ingress
          uid: d8155750-b340-474f-87df-aae72ba83c1f
    spec:
      dnsNames:
        - webhook.35.241.255.137.nip.io
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt-prod
      secretName: tls-webhook
      usages:
        - digital signature
        - key encipherment
kind: List
metadata:
  resourceVersion: ""
