---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ai-sre-agent
  namespace: ai-agent
spec:
  suspend: false
  interval: 30m
  releaseName: ai-sre-agent
  chart:
    spec:
      chart: ./apps/ai-sre-agent
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
