---
apiVersion: v1
kind: Namespace
metadata:
  name: aiot
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiot-pipeline
  namespace: aiot
spec:
  suspend: false
  interval: 30m
  releaseName: aiot-pipeline
  chart:
    spec:
      chart: ./apps/aiot-pipeline
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  timeout: 45m
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
