---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-theater
  labels:
    app.kubernetes.io/name: aiot-chaos-theater
    app.kubernetes.io/part-of: aiot-platform
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiot-chaos-theater
  namespace: chaos-theater
spec:
  suspend: false
  interval: 30m
  releaseName: aiot-chaos-theater
  chart:
    spec:
      chart: ./apps/aiot-chaos-theater
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
