---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  suspend: false
  interval: 30m
  releaseName: am
  chart:
    spec:
      chart: ./apps/alertmanager
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
