apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability-logs
spec:
  suspend: false
  interval: 30m
  releaseName: alloy
  dependsOn:
  - name: loki
    namespace: observability-logs
  chart:
    spec:
      chart: ./apps/alloy
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  postRenderers:
  - kustomize:
      patches:
      - target:
          version: v1
          kind: DaemonSet
          name: alloy
          namespace: observability-logs
        patch: "apiVersion: apps/v1\nkind: DaemonSet\nmetadata:\n  name: alloy\n \
          \ namespace: observability-logs\nspec:\n  template:\n    spec:\n      containers:\n\
          \        - name: alloy\n          resources:\n            requests:\n  \
          \            cpu: 50m\n            limits:\n              cpu: 250m\n"
