---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: awx
  namespace: flux-system
spec:
  image: quay.io/ansible/awx
  interval: 5m0s
  exclusionList:
    - '.*-rc.*$'
    - '.*-beta.*$'
    - '.*-alpha.*$'
    - '^latest$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: awx-stable
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: awx
  policy:
    semver:
      range: '>=24.0.0-0 <25.0.0-0'
  filterTags:
    pattern: '^24\.\d+\.\d+$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: awx-auto-update
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@local.domain
        name: flux-bot
      messageTemplate: 'chore(awx): update image'
    push:
      branch: main
  update:
    path: ./apps/awx/values.yaml
    strategy: Setters