---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  suspend: false
  interval: 30m
  releaseName: awx-operator
  chart:
    spec:
      chart: ./apps/awx-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
