---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: awx
spec:
  suspend: false
  interval: 30m
  releaseName: awx-operator
  chart:
    spec:
      chart: ./apps/awx-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  postRenderers:
  - kustomize:
      patches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: awx-operator-controller-manager
          namespace: awx
        patch: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: awx-operator-controller-manager\n  namespace: awx\nspec:\n  template:\n    spec:\n      containers:\n        - name: awx-manager\n          resources:\n            requests:\n              cpu: 50m\n            limits:\n              cpu: 500m\n"
