---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  suspend: false
  interval: 30m
  releaseName: gitea
  chart:
    spec:
      chart: ./apps/gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    gitea:
      admin:
        username: "gitea-admin"
