---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  suspend: false
  interval: 30m
  releaseName: gitea
  chart:
    spec:
      chart: ./apps/gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    gitea:
      gitea:
        admin:
          username: "gitea-admin"
          password: "r8sA8CPHD9!bt6d"
          email: "gitea@local.domain"
          passwordMode: "keepUpdated"
