---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  suspend: false
  interval: 30m
  releaseName: grafana
  chart:
    spec:
      chart: ./apps/grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
