---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up-system
spec:
  suspend: false
  interval: 30m
  releaseName: k8up
  chart:
    spec:
      chart: ./apps/k8up
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
