---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeflow-pipelines
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubeflow/pipelines.git
  ref:
    tag: 2.15.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines-crds
  namespace: flux-system
spec:
  interval: 30m
  path: ./manifests/kustomize/cluster-scoped-resources
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-pipelines
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines
  namespace: flux-system
spec:
  interval: 30m
  path: ./manifests/kustomize/env/platform-agnostic
  prune: true
  wait: true
  patches:
    - target:
        kind: ConfigMap
        name: kfp-launcher
        namespace: kubeflow
      patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kfp-launcher
          namespace: kubeflow
        data:
          defaultPipelineRoot: minio://mlpipeline/v2/artifacts
  dependsOn:
    - name: kubeflow-pipelines-crds
  sourceRef:
    kind: GitRepository
    name: kubeflow-pipelines
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kserve
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kserve/kserve.git
  ref:
    tag: v0.15.2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kserve
  namespace: flux-system
spec:
  interval: 30m
  path: ./config/default
  prune: true
  wait: false
  patches:
    - target:
        kind: Deployment
        name: kserve-localmodel-controller-manager
      patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: kserve-localmodel-controller-manager
          namespace: kserve
        spec:
          replicas: 0
  sourceRef:
    kind: GitRepository
    name: kserve
