---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  image: grafana/loki
  interval: 5m0s
  exclusionList:
    - '.*-rc.*$'
    - '.*-beta.*$'
    - '.*-alpha.*$'
    - '^latest$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: loki-stable
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: loki
  policy:
    semver:
      range: '>=3.6.0-0 <4.0.0-0'
  filterTags:
    pattern: '^3\.\d+\.\d+$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: loki-auto-update
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@local.domain
        name: flux-bot
      messageTemplate: 'chore(loki): update image'
    push:
      branch: main
  update:
    path: ./apps/loki/values.yaml
    strategy: Setters