---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-event-bridge
  namespace: prometheus-event-bridge
spec:
  suspend: true
  interval: 30m
  releaseName: prometheus-event-bridge
  chart:
    spec:
      chart: ./apps/prometheus-event-bridge
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
