apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  suspend: false
  interval: 30m
  releaseName: qdrant
  chart:
    spec:
      chart: ./apps/qdrant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: "if ($request_uri = \"\
          /\") {\n  return 302 https://$host/dashboard;\n}"
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
