---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  image: docker.io/bitnami/sealed-secrets-controller
  interval: 5m0s
  exclusionList:
    - '.*-rc.*$'
    - '.*-beta.*$'
    - '.*-alpha.*$'
    - '^latest$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: sealed-secrets-controller-stable
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sealed-secrets-controller
  policy:
    semver:
      range: '>=0.27.0-0 <1.0.0-0'
  filterTags:
    pattern: '^0\.\d+\.\d+$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: sealed-secrets-controller-auto-update
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@local.domain
        name: flux-bot
      messageTemplate: 'chore(sealed-secrets): update controller image'
    push:
      branch: main
  update:
    path: ./apps/sealed-secrets/values.yaml
    strategy: Setters