---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: terrakube
  namespace: terrakube
spec:
  suspend: false
  interval: 30m
  releaseName: terrakube
  chart:
    spec:
      chart: ./apps/terrakube
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    timeout: 5m
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 5m
    disableWait: true
    remediation:
      retries: 3
