---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: victoriametrics
  namespace: flux-system
spec:
  image: victoriametrics/victoria-metrics
  interval: 5m0s
  exclusionList:
    - '.*-rc.*$'
    - '.*-beta.*$'
    - '.*-alpha.*$'
    - '^latest$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: victoriametrics-stable
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: victoriametrics
  policy:
    semver:
      range: '>=1.100.0-0 <2.0.0-0'
  filterTags:
    pattern: '^v1\.\d+\.\d+$'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: victoriametrics-auto-update
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@local.domain
        name: flux-bot
      messageTemplate: 'chore(victoriametrics): update image'
    push:
      branch: main
  update:
    path: ./apps/victoriametrics/values.yaml
    strategy: Setters