---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-ui
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-ui
spec:
  interval: 30m
  releaseName: weave-gitops
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  install:
    createNamespace: true
  values:
    adminUser:
      create: true
      createClusterRole: true
      createSecret: true
      username: admin
      passwordHash: "$2y$05$0Ia3U/0zd/Ptvhd2hpFll.ZqRPJ2hm/ACdTJycp1TQrUiHJ8k6FQ2"
    additionalArgs:
      - --auth-methods=oidc,user-account
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: flux.46.4.123.8.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts: [flux.46.4.123.8.nip.io]
          secretName: weave-gitops-tls
