apiVersion: v1
items:
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"2a:4a:65:62:7e:2d"}'
        flannel.alpha.coreos.com/backend-type: vxlan
        flannel.alpha.coreos.com/kube-subnet-manager: "true"
        flannel.alpha.coreos.com/public-ip: 10.132.0.2
        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
        management.cattle.io/pod-limits: '{"cpu":"6500m","memory":"4736Mi"}'
        management.cattle.io/pod-requests: '{"cpu":"1605m","memory":"2290Mi","pods":"17"}'
        node.alpha.kubernetes.io/ttl: "0"
        volumes.kubernetes.io/controller-managed-attach-detach: "true"
      labels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        io.cilium.migration/cilium-default: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: aiot-master
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ""
        node.kubernetes.io/exclude-from-external-load-balancers: ""
        workload-zone: control
      name: aiot-master
    spec:
      podCIDR: 10.244.0.0/24
      podCIDRs:
        - 10.244.0.0/24
      taints:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        csi.volume.kubernetes.io/nodeid: '{"linstor.csi.linbit.com":"aiot-worker-01"}'
        flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"c2:d5:10:6d:8d:c7"}'
        flannel.alpha.coreos.com/backend-type: vxlan
        flannel.alpha.coreos.com/kube-subnet-manager: "true"
        flannel.alpha.coreos.com/public-ip: 10.132.0.3
        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
        management.cattle.io/pod-limits: '{"cpu":"8660m","ephemeral-storage":"10Gi","memory":"9418Mi"}'
        management.cattle.io/pod-requests: '{"cpu":"1906m","ephemeral-storage":"2Gi","memory":"3635Mi","pods":"43"}'
        node.alpha.kubernetes.io/ttl: "0"
        volumes.kubernetes.io/controller-managed-attach-detach: "true"
      labels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        io.cilium.migration/cilium-default: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: aiot-worker-01
        kubernetes.io/os: linux
        linbit.com/hostname: aiot-worker-01
        node-role.kubernetes.io/worker: ""
        piraeus.io/storage: "yes"
        workload-zone: data
      name: aiot-worker-01
    spec:
      podCIDR: 10.244.6.0/24
      podCIDRs:
        - 10.244.6.0/24
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        csi.volume.kubernetes.io/nodeid: '{"linstor.csi.linbit.com":"aiot-worker-02"}'
        flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"86:3b:9d:76:60:f8"}'
        flannel.alpha.coreos.com/backend-type: vxlan
        flannel.alpha.coreos.com/kube-subnet-manager: "true"
        flannel.alpha.coreos.com/public-ip: 10.132.0.4
        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
        management.cattle.io/pod-limits: '{"cpu":"13150m","memory":"15596Mi"}'
        management.cattle.io/pod-requests: '{"cpu":"2405m","memory":"4854Mi","pods":"41"}'
        node.alpha.kubernetes.io/ttl: "0"
        volumes.kubernetes.io/controller-managed-attach-detach: "true"
      labels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        io.cilium.migration/cilium-default: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: aiot-worker-02
        kubernetes.io/os: linux
        linbit.com/hostname: aiot-worker-02
        node-role.kubernetes.io/worker: ""
        piraeus.io/storage: "yes"
        workload-zone: data
      name: aiot-worker-02
    spec:
      podCIDR: 10.244.2.0/24
      podCIDRs:
        - 10.244.2.0/24
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"42:d6:1c:3f:58:78"}'
        flannel.alpha.coreos.com/backend-type: vxlan
        flannel.alpha.coreos.com/kube-subnet-manager: "true"
        flannel.alpha.coreos.com/public-ip: 172.16.200.10
        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
        management.cattle.io/pod-limits: '{"cpu":"4100m","ephemeral-storage":"15Gi","memory":"6388Mi"}'
        management.cattle.io/pod-requests: '{"cpu":"1385m","ephemeral-storage":"7Gi","memory":"3160Mi","pods":"24"}'
        node.alpha.kubernetes.io/ttl: "0"
        volumes.kubernetes.io/controller-managed-attach-detach: "true"
      labels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        cloud: oci
        io.cilium.migration/cilium-default: "true"
        konflux.ci/role: build
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: oci-e5-node1
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""
        topology.kubernetes.io/zone: oci-frankfurt
        workload-zone: build
      name: oci-e5-node1
    spec:
      podCIDR: 10.244.3.0/24
      podCIDRs:
        - 10.244.3.0/24
  - apiVersion: v1
    kind: Node
    metadata:
      annotations:
        flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"16:54:0e:22:4b:41"}'
        flannel.alpha.coreos.com/backend-type: vxlan
        flannel.alpha.coreos.com/kube-subnet-manager: "true"
        flannel.alpha.coreos.com/public-ip: 172.16.200.11
        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
        management.cattle.io/pod-limits: '{"cpu":"10400m","memory":"19804Mi"}'
        management.cattle.io/pod-requests: '{"cpu":"2675m","memory":"3882Mi","pods":"44"}'
        node.alpha.kubernetes.io/ttl: "0"
        volumes.kubernetes.io/controller-managed-attach-detach: "true"
      labels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        cloud: oci
        io.cilium.migration/cilium-default: "true"
        konflux.ci/role: build
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: oci-e5-node2
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""
        topology.kubernetes.io/zone: oci-frankfurt
        workload-zone: build
      name: oci-e5-node2
    spec:
      podCIDR: 10.244.4.0/24
      podCIDRs:
        - 10.244.4.0/24
kind: List
metadata:
  resourceVersion: ""
