apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      namespace: REDACTED
      token: REDACTED
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"kubernetes.io/service-account.name":"headlamp-admin"},"name":"headlamp-admin-token","namespace":"headlamp"},"type":"kubernetes.io/service-account-token"}
        kubernetes.io/service-account.name: headlamp-admin
        kubernetes.io/service-account.uid: b6eddffe-e21a-44a6-94f0-121f689e5433
      labels:
        kubernetes.io/legacy-token-last-used: "2026-04-27"
      name: headlamp-admin-token
      namespace: headlamp
    type: kubernetes.io/service-account-token
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: headlamp.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-headlamp
        cert-manager.io/common-name: headlamp.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-headlamp
      namespace: headlamp
    type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
