apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: headlamp
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: headlamp
      namespace: headlamp
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: headlamp-admin
      namespace: headlamp
kind: List
metadata:
  resourceVersion: ""
