apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: build-service
      konflux.konflux-ci.dev/component: build-service
      konflux.konflux-ci.dev/owner: konflux-build-service
    name: build-service-controller-manager
    namespace: build-service
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxBuildService
      name: konflux-build-service
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: build-service
kind: List
metadata:
