apiVersion: v1
items:
  - apiVersion: v1
    data:
      profile-name: kubeflow-user-example-com
      user: user@example.com
    kind: ConfigMap
    metadata:
      annotations: {}
      name: default-install-config-9h2h2b6hbk
      namespace: default
  - apiVersion: v1
    data:
      config: "{\n  \"systemDefaultRegistry\": \"\",\n  \"agentImage\": \"rancher/fleet-agent:v0.14.3\",\n  \"agentImagePullPolicy\": \"IfNotPresent\",\n  \"apiServerURL\": \"https://rancher.35.241.255.137.nip.io\",\n  \"apiServerCA\": \"\",\n  \"agentCheckinInterval\": \"15m\",\n  \"agentTLSMode\": \"strict\",\n  \"agentWorkers\": {\n        \"bundledeployment\": \"50\",\n        \"drift\": \"50\"\n  },\n  \n  \"garbageCollectionInterval\": \"15m\",\n  \n  \"ignoreClusterRegistrationLabels\": false,\n  \"bootstrap\": {\n    \"paths\": \"\",\n    \"repo\": \"\",\n    \"secret\": \"\",\n    \"branch\":  \"master\",\n    \"namespace\": \"fleet-local\",\n    \"agentNamespace\": \"cattle-fleet-local-system\"\n  },\n  \"webhookReceiverURL\": \"\",\n  \"githubURLPrefix\": \"\",\n  \"gitClientTimeout\": \"30s\"\n}\n"
    kind: ConfigMap
    metadata:
      annotations: {}
      name: fleet-controller
      namespace: default
  - apiVersion: v1
    data:
      allow-snippet-annotations: "true"
      annotations-risk-level: Critical
      proxy-body-size: "0"
      proxy-headers-hash-bucket-size: "128"
      proxy-headers-hash-max-size: "1024"
      proxy-read-timeout: "3600"
      proxy-send-timeout: "3600"
    kind: ConfigMap
    metadata:
      annotations: {}
      name: ingress-nginx-ingress-nginx-controller
      namespace: default
  - apiVersion: v1
    data:
      root-cert.pem: |
        -----BEGIN CERTIFICATE-----
        MIIC/DCCAeSgAwIBAgIQRRabq+yMXyRafntlJeCv/jANBgkqhkiG9w0BAQsFADAY
        MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTI2MDQxNDAyMjQyMVoXDTM2MDQx
        MTAyMjQyMVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAJ/zEnuc8b/DvAWOjZMkKqHgP4Poo94NHrE7KVEu
        j9RQ00TmBUN1eMjFJbOUR3M/EHbjrjXO4asqC6B9X3zITZ1r1nGkjZBd2vm1b7cW
        H6cMKySq/ILkvmO+y7k/IunD8re+jDoXdvRnR1lLUHBwp9JISqm9EK6dt5Xc6BVZ
        v8cDSFCeON+RUVHhIh2p/AYLkNamHfRb/EbCWn5jXR43udBrjWd+5Ack4OgNK/QL
        UUIUbzsfcQz70ZXW0SIs/NGq7/AEFcFMo31E/IUpVHslROq/vINS9ARU28FndRsF
        ORTEFwZKtEFpoiYG3uLSlvUrl+n6obYw0t274HMn1wSJCJUCAwEAAaNCMEAwDgYD
        VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOw7AyQg+Bl3
        XZ0MvJUVjwL6OBrbMA0GCSqGSIb3DQEBCwUAA4IBAQCXFXruCYGPYjgUg0B2CAQR
        y1rzx+fiNZx5AuKoS/RFaKjhMkPtGD2Oi03RI8Rz0I+hiuOGrj4d0sfiYOfpZTb9
        nb0RN19QhFTXmcGrM1asFmTCEoIOktsE4S3xcMk5X6/rc+PxcBvBZsi54PC9gA+h
        P6j5OVgg8gkRyh646mtR9fDobGyZ12hOTHF4LJkGpOko/tG+/P8pmyLtOsBH6f7G
        y69tNOwXl5M6ujtK+oE09hGStwP0YW6dGLuqNFspcn8Nmf63PeHk+pFTI2RH5tG+
        H1YZsJ7+UfhcJ5PnzjHHBIHrIurvLcuiwDyBPW18bJAV6xLC0VgDrCAxEDOJD6T4
        -----END CERTIFICATE-----
    kind: ConfigMap
    metadata:
      labels:
        istio.io/config: "true"
      name: istio-ca-root-cert
      namespace: default
  - apiVersion: v1
    data:
      known_hosts: |
        bitbucket.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPIQmuzMBuKdWeF4+a2sjSSpBK0iqitSQ+5BM9KhpexuGt20JpTVM7u5BDZngncgrqDMbWdxMWWOGtZ9UgbqgZE=
        bitbucket.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO
        bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQeJzhupRu0u0cdegZIa8e86EG2qOCsIsD1Xw0xSeiPDlCr7kq97NLmMbpKTX6Esc30NuoqEEHCuc7yWtwp8dI76EEEB1VqY9QJq6vk+aySyboD5QF61I/1WeTwu+deCbgKMGbUijeXhtfbxSxm6JwGrXrhBdofTsbKRUsrN1WoNgUa8uqN1Vx6WAJw1JHPhglEGGHea6QICwJOAr/6mrui/oB7pkaWKHj3z7d1IC4KWLtY47elvjbaTlkN04Kc/5LFEirorGYVbt15kAUlqGM65pk6ZBxtaO3+30LVlORZkxOh+LKL/BvbZ/iRNhItLqNyieoQj/uh/7Iv4uyH/cV/0b4WDSd3DptigWq84lJubb9t/DnZlrJazxyDCulTmKdOR7vs9gMTo+uoIrPSb8ScTtvw65+odKAlBj59dhnVp9zd7QUojOpXlL62Aw56U4oO+FALuevvMjiWeavKhJqlR7i5n9srYcrNV7ttmDw7kf/97P5zauIhxcjX+xHv4M=
        github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
        gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
        gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
        ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
        vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    kind: ConfigMap
    metadata:
      annotations: {}
      name: known-hosts
      namespace: default
  - apiVersion: v1
    data:
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDBTCCAe2gAwIBAgIICFZ7LDONfKkwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
        AxMKa3ViZXJuZXRlczAeFw0yNjA0MTQwMTEyMjlaFw0zNjA0MTEwMTE3MjlaMBUx
        EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
        AoIBAQCgWEcelObEPb57j3B7s7K16UNHMXZZETdrPKjbPYQ2u88dvocDWXgX+S9G
        HzJ/81TqbJCft0kT4QiYqU32mKQSy/ncsA6UQGSBVlTAfzpDfM/PSL8DIyA59U6C
        0OgPMcK3ot99ZBiv/LTkDfIyw5y1uc201DYVQ9kAyNAcqCjubtbYHiHOa/IJbVZh
        CK8PlpvHj7JBncsnb08EUEHvI5vVYE+hKJKIArqWyPEfG0oB/ZilmR3B3gVF2ev8
        k/G1FZ2Jx8ln5ZDdbGYB+VxZ7Bio4PAS0TUplA/xp9qJUXBJjhIZbAy1Xfpv3PLB
        1NFd7xlpAa8UErTFxGXMTydi6mTvAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
        BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTY9OiYpct4GkXOdcDgjJsBhNmGxjAV
        BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAYdZl446N4
        4VF0kezqF8wSivD07V9WdWi+SMLiOHCeMm1p1S0gEK3S9H3wsDrF7cKnomFqBwAg
        46Sv0iu3hel8w+qg5F1UOoy4PUFUkwx3pNBaA+s4IjkR5yERwpwDGqNDUmlkL3PJ
        qDkvCDBgU9sEeY2V+2GBwkEaUiwKt7xqiw6t60NkFIpEvm8HQNDU6nXarceAfYOJ
        fUNowmy6m8xS/FivcYs+Wqvv5yu+mwtvkxy9t026y+XCT+R8VQLG/QabiQRolzH6
        PSjYAW4HZYcjaXqAmQk7N8kElJ1hkymxppUQWvfpN1LhYs/3YCULS+fmzLR/w6ZO
        szTc1uZpUffa
        -----END CERTIFICATE-----
    kind: ConfigMap
    metadata:
      annotations:
        kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
      name: kube-root-ca.crt
      namespace: default
  - apiVersion: v1
    data:
      priorityClassName: rancher-critical
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app: rancher
        app.kubernetes.io/part-of: rancher
        chart: rancher-2.13.3
        heritage: Helm
        release: rancher
      name: rancher-config
      namespace: default
  - apiVersion: v1
    data:
      otel-collector-config.yaml: '""'
      otel-collector-opamp-config.yaml: 'server_endpoint: "ws://signoz:4320/v1/opamp"'
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: otel-collector
        app.kubernetes.io/instance: signoz
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: signoz
        app.kubernetes.io/version: v0.117.1
        helm.sh/chart: signoz-0.117.1
      name: signoz-otel-collector
      namespace: default
  - apiVersion: v1
    data:
      "1883": emqx/emqx:1883
      "8083": emqx/emqx:8083
    kind: ConfigMap
    metadata:
      annotations: {}
      name: tcp-services
      namespace: default
  - apiVersion: v1
    data:
      API_ENABLE_DOCUMENTATION: "false"
      API_ENDPOINT_PORT: "8001"
      API_ENDPOINT_URL: 0.0.0.0
      API_RATE_LIMITER_CUSTOM_1: Security:xxx:60:100
      API_RATE_LIMITER_L1: 60:100
      API_TOKEN_EXPIRATION_MIN: "525600"
      API_TOKEN_REFRESH_EXPIRATION_DAYS: "365"
      AUTH_ENABLED: "false"
      AUTH_TYPE: BUILT-IN
      CLUSTER_ID: aiot-cluster
      DEBUG_LEVEL: info
      DOWNLOAD_INSPECT_FOLDER: /tmp/velero-inspect-backups
      K8S_IN_CLUSTER_MODE: "true"
      K8S_VELERO_NAMESPACE: velero
      K8S_VELERO_UI_NAMESPACE: vui
      ORIGINS_1: '*'
      SECURITY_DISABLE_USERS_PWD_RATE: "1"
      SECURITY_PATH_DATABASE: ./data
      WATCHDOG_PORT: "8001"
      WATCHDOG_REPORT_CRONJOB_NAME: vui-report-cronjob
      WATCHDOG_URL: vui-watchdog-clusterip-svc
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: vui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vui
        app.kubernetes.io/version: 0.4.1
        helm.sh/chart: vui-1.0.6
      name: vui-api-config
      namespace: default
  - apiVersion: v1
    data:
      AGENT_MODE: "false"
      CORE: "false"
      HELM_API: 0.3.1
      HELM_APP_VERSION: 0.4.1
      HELM_RELEASE_NAME: vui
      HELM_UI: 0.3.1
      HELM_VERSION: 1.0.6
      HELM_WATCHDOG: 0.1.8
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: vui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vui
        app.kubernetes.io/version: 0.4.1
        helm.sh/chart: vui-1.0.6
      name: vui-helm-config
      namespace: default
  - apiVersion: v1
    data:
      NEXT_PUBLIC_AUTH_ENABLED: "false"
      NEXT_PUBLIC_CACHE_TTL: "180"
      NEXT_PUBLIC_INSPECT_BACKUP_ENABLED: "false"
      NEXT_PUBLIC_LOGGER_ENABLED: "false"
      NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: "1500"
      NEXT_PUBLIC_REFRESH_RECENT: "5000"
      NEXT_PUBLIC_VELERO_API_NAME_1: aiot-cluster
      NEXT_PUBLIC_VELERO_API_URL_1: https://vui.35.241.255.137.nip.io/api
      NEXT_PUBLIC_VELERO_API_WS_1: wss://vui.35.241.255.137.nip.io
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: vui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vui
        app.kubernetes.io/version: 0.4.1
        helm.sh/chart: vui-1.0.6
      name: vui-ui-config
      namespace: default
  - apiVersion: v1
    data:
      API_ENDPOINT_PORT: "8001"
      API_ENDPOINT_URL: 0.0.0.0
      BACKUP_ENABLED: "true"
      CLUSTER_ID: aiot-cluster
      DEBUG: info
      DEBUG_LEVEL: info
      EXPIRES_DAYS_WARNING: "29"
      K8S_IN_CLUSTER_MODE: "true"
      K8S_VELERO_NAMESPACE: velero
      K8S_VELERO_UI_NAMESPACE: vui
      NOTIFICATION_SKIP_COMPLETED: "true"
      NOTIFICATION_SKIP_DELETING: "true"
      NOTIFICATION_SKIP_INPROGRESS: "true"
      NOTIFICATION_SKIP_REMOVED: "true"
      PROCESS_CYCLE_SEC: "300"
      REPORT_BACKUP_ITEM_PREFIX: ""
      REPORT_SCHEDULE_ITEM_PREFIX: ""
      SCHEDULE_ENABLED: "true"
      SEND_REPORT_AT_STARTUP: "false"
      SEND_START_MESSAGE: "true"
    kind: ConfigMap
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/instance: vui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vui
        app.kubernetes.io/version: 0.4.1
        helm.sh/chart: vui-1.0.6
      name: vui-watchdog-config
      namespace: default
kind: List
metadata:
  resourceVersion: ""
