apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.localAI.namespace }}
  labels:
    app.kubernetes.io/part-of: aiot-ml-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.mlflow.namespace }}
  labels:
    app.kubernetes.io/part-of: aiot-ml-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    app.kubernetes.io/part-of: aiot-ml-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    app.kubernetes.io/part-of: aiot-ml-platform
