kyverno:
  admissionController:
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      httpGet:
        path: /health/liveness
        port: 9443
        scheme: HTTPS
    readinessProbe:
      failureThreshold: 12
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
      httpGet:
        path: /health/readiness
        port: 9443
        scheme: HTTPS
    rbac:
      coreClusterRole:
        extraResources:
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingadmissionpolicies
          - validatingadmissionpolicybindings
          - mutatingadmissionpolicies
          - mutatingadmissionpolicybindings
          verbs:
          - get
          - list
          - watch
    container:
      extraArgs:
        leaderElectionRetryPeriod: 10s
        clientRateLimitQPS: 300
        clientRateLimitBurst: 600
  backgroundController:
    enabled: false
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      httpGet:
        path: /liveness
        port: 9443
        scheme: HTTPS
    readinessProbe:
      failureThreshold: 12
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
      httpGet:
        path: /readiness
        port: 9443
        scheme: HTTPS
  cleanupController:
    enabled: false
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      httpGet:
        path: /health/liveness
        port: 9443
        scheme: HTTPS
    readinessProbe:
      failureThreshold: 12
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
      httpGet:
        path: /health/readiness
        port: 9443
        scheme: HTTPS
  reportsController:
    enabled: false
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      httpGet:
        path: /liveness
        port: 9443
        scheme: HTTPS
    readinessProbe:
      failureThreshold: 12
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
      httpGet:
        path: /readiness
        port: 9443
        scheme: HTTPS
