apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: config.json
  name: semaphore-config
  namespace: semaphore
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: ''
  name: semaphore-ssh-keys
  namespace: semaphore
type: Opaque
