apiVersion: v1
items:
  - apiVersion: v1
    data:
      password: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: k8up-repo
      namespace: semaphore
    type: Opaque
  - apiVersion: v1
    data:
      access_key: REDACTED
      secret_key: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: r2-creds
      namespace: semaphore
    type: Opaque
  - apiVersion: v1
    data:
      config.json: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: semaphore-config
      namespace: semaphore
    type: Opaque
  - apiVersion: v1
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"semaphore-ssh-keys","namespace":"semaphore"},"type":"Opaque"}
      name: semaphore-ssh-keys
      namespace: semaphore
    type: Opaque
    data: null
kind: List
metadata:
  resourceVersion: ""
