apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        field.cattle.io/publicEndpoints: '[{"addresses":["35.241.255.137"],"port":443,"protocol":"HTTPS","serviceName":"zabbix:zabbix-zabbix-web","ingressName":"zabbix:zabbix-web","hostname":"zabbix.35.241.255.137.nip.io","path":"/","allNodes":false}]'
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
      name: zabbix-web
      namespace: zabbix
    spec:
      ingressClassName: nginx
      rules:
        - host: zabbix.35.241.255.137.nip.io
          http:
            paths:
              - backend:
                  service:
                    name: zabbix-zabbix-web
                    port:
                      number: 80
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - zabbix.35.241.255.137.nip.io
          secretName: zabbix-tls
kind: List
metadata:
  resourceVersion: ""
