grafana:
  assertNoLeakedSecrets: false
  persistence:
    enabled: true
    storageClassName: nfs
    size: 5Gi
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
    - grafana.46.4.123.8.nip.io
    tls:
    - hosts:
      - grafana.46.4.123.8.nip.io
      secretName: grafana-tls
  grafana.ini:
    server:
      root_url: https://grafana.46.4.123.8.nip.io
      domain: grafana.46.4.123.8.nip.io
    auth.generic_oauth:
      enabled: true
      name: Authentik
      client_id: grafana
      client_secret: d4abe87e66a406f23cea1beeb9b4713e40ecb1a46b952b0f30eec77aff21aba8
      scopes: openid profile email
      auth_url: https://authentik.46.4.123.8.nip.io/application/o/authorize/
      token_url: https://authentik.46.4.123.8.nip.io/application/o/token/
      api_url: https://authentik.46.4.123.8.nip.io/application/o/userinfo/
      allow_sign_up: true
      auto_login: false
      role_attribute_path: contains(groups[*], 'authentik Admins') && 'GrafanaAdmin'
        || contains(groups[*], 'admin') && 'Admin' || 'Editor'
      role_attribute_strict: false
      allow_assign_grafana_admin: true
      use_pkce: true
    users:
      auto_assign_org_role: Editor
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://vmsingle-victoriametrics-victoria-metrics-k8s-stack.victoriametrics.svc:8429
        isDefault: true
        editable: true
