apiVersion: v1
kind: Secret
metadata:
  labels:
    component: velero
  name: cloud-credentials
  namespace: velero
  annotations:
    aiot.platform/data-keys: cloud
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: velero-repo-credentials
  namespace: velero
  annotations:
    aiot.platform/data-keys: repository-password
type: Opaque
