apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: AWS_ACCESS_KEY_ID,AWS_BUCKET,AWS_ENDPOINT,AWS_SECRET_ACCESS_KEY
  name: r2-credentials
  namespace: etcd-backup
type: Opaque
