apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: localhost,dex.konflux-ui,dex.konflux-ui.svc.cluster.local
        cert-manager.io/certificate-name: dex-cert
        cert-manager.io/common-name: ""
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: ""
        cert-manager.io/issuer-kind: Issuer
        cert-manager.io/issuer-name: ui-ca-issuer
        cert-manager.io/subject-organizations: konflux
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: dex-cert
      namespace: konflux-ui
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: konflux.35.241.255.137.nip.io
        cert-manager.io/certificate-name: konflux-ingress-tls
        cert-manager.io/common-name: konflux.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: konflux-ingress-tls
      namespace: konflux-ui
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: localhost
        cert-manager.io/certificate-name: oauth2-proxy-cert
        cert-manager.io/common-name: ""
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: ""
        cert-manager.io/issuer-kind: Issuer
        cert-manager.io/issuer-name: ui-ca-issuer
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: oauth2-proxy-cert
      namespace: konflux-ui
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      client-secret: REDACTED
    kind: Secret
    metadata:
      labels:
        konflux.konflux-ci.dev/component: ui
        konflux.konflux-ci.dev/owner: konflux-ui
      name: oauth2-proxy-client-secret
      namespace: konflux-ui
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxUI
          name: konflux-ui
          uid: 4100e984-9ed5-4a39-a25b-169927bdac04
    type: Opaque
  - apiVersion: v1
    data:
      cookie-secret: REDACTED
    kind: Secret
    metadata:
      labels:
        konflux.konflux-ci.dev/component: ui
        konflux.konflux-ci.dev/owner: konflux-ui
      name: oauth2-proxy-cookie-secret
      namespace: konflux-ui
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxUI
          name: konflux-ui
          uid: 4100e984-9ed5-4a39-a25b-169927bdac04
    type: Opaque
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      namespace: REDACTED
      token: REDACTED
    kind: Secret
    metadata:
      annotations:
        kubernetes.io/service-account.name: proxy
        kubernetes.io/service-account.uid: aaf1c377-9af0-42c2-bf40-60531d37c0c5
      labels:
        konflux.konflux-ci.dev/component: ui
        konflux.konflux-ci.dev/owner: konflux-ui
        kubernetes.io/legacy-token-last-used: "2026-04-25"
      name: proxy
      namespace: konflux-ui
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxUI
          name: konflux-ui
          uid: 4100e984-9ed5-4a39-a25b-169927bdac04
    type: kubernetes.io/service-account-token
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: localhost,proxy.konflux-ui.svc,proxy.konflux-ui.svc.cluster.local
        cert-manager.io/certificate-name: serving-cert
        cert-manager.io/common-name: ""
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: ""
        cert-manager.io/issuer-kind: Issuer
        cert-manager.io/issuer-name: ui-ca-issuer
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: serving-cert
      namespace: konflux-ui
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: ""
        cert-manager.io/certificate-name: ui-ca
        cert-manager.io/common-name: ui-ca
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: self-signed-cluster-issuer
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: ui-ca
      namespace: konflux-ui
    type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
