apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: konflux-ui
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: dex
        konflux.konflux-ci.dev/component: ui
        konflux.konflux-ci.dev/owner: konflux-ui
      name: dex
      namespace: konflux-ui
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxUI
          name: konflux-ui
          uid: 4100e984-9ed5-4a39-a25b-169927bdac04
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        konflux.konflux-ci.dev/component: ui
        konflux.konflux-ci.dev/owner: konflux-ui
      name: proxy
      namespace: konflux-ui
      ownerReferences:
        - apiVersion: konflux.konflux-ci.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: KonfluxUI
          name: konflux-ui
          uid: 4100e984-9ed5-4a39-a25b-169927bdac04
kind: List
metadata:
  resourceVersion: ""
