apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"victoriametrics","namespace":"victoriametrics"},"spec":{"ports":[{"port":8428,"targetPort":8428}],"selector":{"app":"victoriametrics"}}}
    name: victoriametrics
    namespace: victoriametrics
  spec:
    clusterIP: 10.100.227.226
    clusterIPs:
    - 10.100.227.226
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8428
      protocol: TCP
      targetPort: 8428
    selector:
      app: victoriametrics
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
