apiVersion: v1
items:
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
        operator.tekton.dev/last-applied-hash: REDACTED
      labels:
        operator.tekton.dev/operand-name: tektoncd-pipelines
      name: proxy-webhook-certs
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: pipeline-main-static-4h464
          uid: 108c3d6b-0365-43b4-b40a-f3acea03765f
    type: Opaque
  - apiVersion: v1
    data:
      cosign.pub: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: public-key
      namespace: tekton-pipelines
    type: Opaque
  - apiVersion: v1
    data:
      cosign.key: REDACTED
      cosign.password: REDACTED
      cosign.pub: REDACTED
    immutable: true
    kind: Secret
    metadata:
      annotations:
          {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"operator.tekton.dev/last-applied-hash":"REDACTED"},"labels":{"app.kubernetes.io/instance":"default","app.kubernetes.io/part-of":"tekton-chains","operator.tekton.dev/operand-name":"tektoncd-chains"},"name":"signing-secrets","namespace":"tekton-pipelines","ownerReferences":[{"apiVersion":"operator.tekton.dev/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"TektonInstallerSet","name":"chain-secret-krs7w","uid":"7ff32f25-5784-4c7e-8f93-fd2ebf33428e"}]}}
        operator.tekton.dev/last-applied-hash: REDACTED
      labels:
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-chains
        operator.tekton.dev/operand-name: tektoncd-chains
      name: signing-secrets
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: chain-secret-krs7w
          uid: 7ff32f25-5784-4c7e-8f93-fd2ebf33428e
    type: Opaque
  - apiVersion: v1
    data:
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: REDACTED
    kind: Secret
    metadata:
      name: tekton-results-postgres
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonResult
          name: result
          uid: 4510785d-6391-4a4f-be6a-d80847c7a01c
    type: Opaque
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      name: tekton-results-tls
      namespace: tekton-pipelines
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
        operator.tekton.dev/last-applied-hash: REDACTED
      labels:
        app.kubernetes.io/component: interceptors
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: core-interceptors
        app.kubernetes.io/part-of: tekton-triggers
        operator.tekton.dev/operand-name: tektoncd-triggers
        triggers.tekton.dev/release: v0.35.0
      name: tekton-triggers-core-interceptors-certs
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: trigger-main-static-65hpn
          uid: b5f7f32a-0588-4a9a-ade6-31648757cdf9
    type: Opaque
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
        operator.tekton.dev/last-applied-hash: REDACTED
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-triggers
        operator.tekton.dev/operand-name: tektoncd-triggers
        triggers.tekton.dev/release: v0.35.0
      name: triggers-webhook-certs
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: trigger-main-static-65hpn
          uid: b5f7f32a-0588-4a9a-ade6-31648757cdf9
    type: Opaque
  - apiVersion: v1
    data:
      ca-cert.pem: REDACTED
      server-cert.pem: REDACTED
      server-key.pem: REDACTED
    kind: Secret
    metadata:
      annotations:
        operator.tekton.dev/last-applied-hash: REDACTED
      labels:
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
        operator.tekton.dev/operand-name: tektoncd-pipelines
        pipeline.tekton.dev/release: v1.10.0
      name: webhook-certs
      namespace: tekton-pipelines
      ownerReferences:
        - apiVersion: operator.tekton.dev/v1alpha1
          blockOwnerDeletion: true
          controller: true
          kind: TektonInstallerSet
          name: pipeline-main-static-4h464
          uid: 108c3d6b-0365-43b4-b40a-f3acea03765f
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
