apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      konflux.konflux-ci.dev/component: namespace-lister
      konflux.konflux-ci.dev/owner: konflux-namespace-lister
    name: namespace-lister-allow-from-konfluxui
    namespace: namespace-lister
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxNamespaceLister
      name: konflux-namespace-lister
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: konflux-ui
      - podSelector:
          matchLabels:
            app: proxy
      ports:
      - port: 8080
        protocol: TCP
    podSelector:
      matchLabels:
        apps: namespace-lister
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      konflux.konflux-ci.dev/component: namespace-lister
      konflux.konflux-ci.dev/owner: konflux-namespace-lister
    name: namespace-lister-allow-to-apiserver
    namespace: namespace-lister
    ownerReferences:
    - apiVersion: konflux.konflux-ci.dev/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: KonfluxNamespaceLister
      name: konflux-namespace-lister
  spec:
    egress:
    - ports:
      - port: 6443
        protocol: TCP
      - port: 443
        protocol: TCP
    podSelector:
      matchLabels:
        apps: namespace-lister
    policyTypes:
    - Egress
kind: List
metadata:
