apiVersion: v2
name: event-exporter-overlay
description: aiot-platform overlay for kubernetes-event-exporter
type: application
version: 1.0.0
appVersion: "3.2.13"
dependencies:
  - name: kubernetes-event-exporter
    version: "3.2.13"
    repository: https://charts.bitnami.com/bitnami
