apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: backrest
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pod-executor
      namespace: backrest
kind: List
metadata:
  resourceVersion: ""
