apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      cnpg.io/operatorVersion: 1.25.1
    creationTimestamp: "2026-04-14T01:26:18Z"
    generation: 1
    labels:
      cnpg.io/cluster: pg-ha
    name: pg-ha-primary
    namespace: aiot
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: pg-ha
      uid: 3abe23df-5af5-4d3b-890f-ca2a22fa147f
    resourceVersion: "2837567"
    uid: dbfa15fe-ec6b-4156-9568-9b732d7b3512
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        cnpg.io/cluster: pg-ha
        cnpg.io/instanceRole: primary
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T01:26:18Z"
      message: ""
      observedGeneration: 1
      reason: InsufficientPods
      status: "False"
      type: DisruptionAllowed
    currentHealthy: 1
    desiredHealthy: 1
    disruptionsAllowed: 0
    expectedPods: 1
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
