apiVersion: v1
items:
  - apiVersion: v1
    data:
      GROQ_API_KEY: REDACTED
    kind: Secret
    metadata:
      name: groq-api-key
      namespace: aiot
    type: Opaque
  - apiVersion: v1
    data:
      password: REDACTED
    kind: Secret
    metadata:
      name: k8up-repo
      namespace: aiot
    type: Opaque
  - apiVersion: v1
    data:
      PG_PASS: REDACTED
      PG_USER: REDACTED
      PGPASSWORD: REDACTED
    kind: Secret
    metadata:
      annotations: {"apiVersion": "v1", "data": {"PGPASSWORD": "cG9zdGdyZXMxMjM=", "PG_PASS": "cG9zdGdyZXMxMjM=", "PG_USER": "cG9zdGdyZXM="}, "kind": "Secret", "metadata": {"annotations": {}, "creationTimestamp": null, "name": "pg-credentials", "namespace": "aiot"}}
      name: pg-credentials
      namespace: aiot
    type: Opaque
  - apiVersion: v1
    data:
      password: REDACTED
      username: REDACTED
    kind: Secret
    metadata:
      name: pg-ha-app
      namespace: aiot
    type: kubernetes.io/basic-auth
  - apiVersion: v1
    data:
      ca.crt: REDACTED
      ca.key: REDACTED
    kind: Secret
    metadata:
      labels:
        app.kubernetes.io/managed-by: cloudnative-pg
      name: pg-ha-ca
      namespace: aiot
      ownerReferences:
        - apiVersion: postgresql.cnpg.io/v1
          controller: true
          kind: Cluster
          name: pg-ha
          uid: 98d362e4-90ce-428f-aa6a-31475bcbf415
    type: Opaque
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      labels:
        app.kubernetes.io/managed-by: cloudnative-pg
      name: pg-ha-replication
      namespace: aiot
      ownerReferences:
        - apiVersion: postgresql.cnpg.io/v1
          controller: true
          kind: Cluster
          name: pg-ha
          uid: 98d362e4-90ce-428f-aa6a-31475bcbf415
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      labels:
        app.kubernetes.io/managed-by: cloudnative-pg
      name: pg-ha-server
      namespace: aiot
      ownerReferences:
        - apiVersion: postgresql.cnpg.io/v1
          controller: true
          kind: Cluster
          name: pg-ha
          uid: 98d362e4-90ce-428f-aa6a-31475bcbf415
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      password: REDACTED
      username: REDACTED
    kind: Secret
    metadata:
      name: pg-ha-superuser
      namespace: aiot
    type: kubernetes.io/basic-auth
  - apiVersion: v1
    data:
      access_key: REDACTED
      secret_key: REDACTED
    kind: Secret
    metadata:
      name: r2-creds
      namespace: aiot
    type: Opaque
  - apiVersion: v1
    data:
      SAMBANOVA_API_KEY: REDACTED
    kind: Secret
    metadata:
      annotations: {"apiVersion": "v1", "data": {"SAMBANOVA_API_KEY": "ZHVtbXkta2V5"}, "kind": "Secret", "metadata": {"annotations": {}, "creationTimestamp": null, "name": "sambanova-api-key", "namespace": "aiot"}}
      name: sambanova-api-key
      namespace: aiot
    type: Opaque
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: api.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-api-gateway
        cert-manager.io/common-name: api.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-api-gateway
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: cloudbeaver.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-cloudbeaver
        cert-manager.io/common-name: cloudbeaver.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-cloudbeaver
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: twin.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-digital-twin
        cert-manager.io/common-name: twin.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-digital-twin
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: ngrok.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-ngrok-proxy
        cert-manager.io/common-name: ngrok.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-ngrok-proxy
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: chat.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-open-webui
        cert-manager.io/common-name: chat.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-open-webui
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: pgadmin.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-pgadmin
        cert-manager.io/common-name: pgadmin.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-pgadmin
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: qdrant.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-qdrant
        cert-manager.io/common-name: qdrant.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-qdrant
      namespace: aiot
    type: kubernetes.io/tls
  - apiVersion: v1
    data:
      tls.crt: REDACTED
      tls.key: REDACTED
    kind: Secret
    metadata:
      annotations:
        cert-manager.io/alt-names: rag.35.241.255.137.nip.io
        cert-manager.io/certificate-name: tls-rag
        cert-manager.io/common-name: rag.35.241.255.137.nip.io
        cert-manager.io/ip-sans: ""
        cert-manager.io/issuer-group: cert-manager.io
        cert-manager.io/issuer-kind: ClusterIssuer
        cert-manager.io/issuer-name: letsencrypt-prod
        cert-manager.io/uri-sans: ""
      labels:
        controller.cert-manager.io/fao: "true"
      name: tls-rag
      namespace: aiot
    type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
