apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: aiot
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        cnpg.io/managedSecrets: '[]'
        cnpg.io/operatorVersion: 1.28.0
      labels:
        app.kubernetes.io/managed-by: cloudnative-pg
        cnpg.io/cluster: pg-ha
      name: pg-ha
      namespace: aiot
      ownerReferences:
        - apiVersion: postgresql.cnpg.io/v1
          controller: true
          kind: Cluster
          name: pg-ha
          uid: 98d362e4-90ce-428f-aa6a-31475bcbf415
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pod-executor
      namespace: aiot
kind: List
metadata:
  resourceVersion: ""
