apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: token
  name: automate-token
  namespace: inspec-scans
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    aiot.platform/data-keys: key
  name: ssh-key
  namespace: inspec-scans
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
  namespace: inspec-scans
  annotations:
    aiot.platform/data-keys: aiot-gcp.pem,aiot-master.pem,oci-e5-node1.pem,oci-e5-node2.pem,oci-test-node1.pem
type: Opaque
