apiVersion: v1
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        k8up.io/owned-by: prune_aiot-prune-58lqd
        k8up.io/repository-hash: 7f9696c5c10bc4c5c36b1770cf5354c4c6400cf079e9c8a22840ff32a5c2e42
        k8up.io/type: prune
        k8upjob: "true"
        k8upjob/exclusive: "true"
      name: prune-aiot-prune-58lqd
      namespace: victoriametrics
      ownerReferences:
        - apiVersion: k8up.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Prune
          name: aiot-prune-58lqd
          uid: 947f9b8e-91a8-474d-a1f6-a1571a54e231
    spec:
      backoffLimit: 6
      completionMode: NonIndexed
      completions: 1
      manualSelector: false
      parallelism: 1
      podReplacementPolicy: TerminatingOrFailed
      selector:
        matchLabels:
          batch.kubernetes.io/controller-uid: 29aa0b1b-c87b-4deb-8611-d7a293e7550e
      suspend: false
      template:
        metadata:
          creationTimestamp: null
          labels:
            batch.kubernetes.io/controller-uid: 29aa0b1b-c87b-4deb-8611-d7a293e7550e
            batch.kubernetes.io/job-name: prune-aiot-prune-58lqd
            controller-uid: 29aa0b1b-c87b-4deb-8611-d7a293e7550e
            job-name: prune-aiot-prune-58lqd
            k8upjob: "true"
        spec:
          containers:
            - args:
                - -varDir
                - /k8up
                - -prune
              command:
                - /usr/local/bin/k8up
                - restic
              env:
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: secret_key
                      name: r2-creds
                - name: PROM_URL
                  value: http://127.0.0.1/
                - name: HOSTNAME
                  value: victoriametrics
                - name: STATS_URL
                - name: KEEP_DAILY
                  value: "2"
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: k8up-repo
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: access_key
                      name: r2-creds
                - name: RESTIC_REPOSITORY
                  value: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
              image: ghcr.io/k8up-io/k8up:v2.15.0
              imagePullPolicy: IfNotPresent
              name: prune
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /k8up
                  name: k8up-dir
                - mountPath: /tmp
                  name: restic-tmp-dir
                - mountPath: /.cache
                  name: restic-cache-dir
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: pod-executor
          serviceAccountName: pod-executor
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: k8up-dir
            - emptyDir: {}
              name: restic-tmp-dir
            - emptyDir: {}
              name: restic-cache-dir
  - apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        k8up.io/owned-by: prune_aiot-prune-cfg95
        k8up.io/repository-hash: 7f9696c5c10bc4c5c36b1770cf5354c4c6400cf079e9c8a22840ff32a5c2e42
        k8up.io/type: prune
        k8upjob: "true"
        k8upjob/exclusive: "true"
      name: prune-aiot-prune-cfg95
      namespace: victoriametrics
      ownerReferences:
        - apiVersion: k8up.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Prune
          name: aiot-prune-cfg95
          uid: 3cb64765-3d3a-4399-8e73-ccc73558dd0c
    spec:
      backoffLimit: 6
      completionMode: NonIndexed
      completions: 1
      manualSelector: false
      parallelism: 1
      podReplacementPolicy: TerminatingOrFailed
      selector:
        matchLabels:
          batch.kubernetes.io/controller-uid: 841e50ce-a2c2-43f5-90c6-a6a3e50d21b0
      suspend: false
      template:
        metadata:
          creationTimestamp: null
          labels:
            batch.kubernetes.io/controller-uid: 841e50ce-a2c2-43f5-90c6-a6a3e50d21b0
            batch.kubernetes.io/job-name: prune-aiot-prune-cfg95
            controller-uid: 841e50ce-a2c2-43f5-90c6-a6a3e50d21b0
            job-name: prune-aiot-prune-cfg95
            k8upjob: "true"
        spec:
          containers:
            - args:
                - -varDir
                - /k8up
                - -prune
              command:
                - /usr/local/bin/k8up
                - restic
              env:
                - name: STATS_URL
                - name: KEEP_DAILY
                  value: "2"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: access_key
                      name: r2-creds
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: secret_key
                      name: r2-creds
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: k8up-repo
                - name: PROM_URL
                  value: http://127.0.0.1/
                - name: HOSTNAME
                  value: victoriametrics
                - name: RESTIC_REPOSITORY
                  value: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
              image: ghcr.io/k8up-io/k8up:v2.15.0
              imagePullPolicy: IfNotPresent
              name: prune
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /k8up
                  name: k8up-dir
                - mountPath: /tmp
                  name: restic-tmp-dir
                - mountPath: /.cache
                  name: restic-cache-dir
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: pod-executor
          serviceAccountName: pod-executor
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: k8up-dir
            - emptyDir: {}
              name: restic-tmp-dir
            - emptyDir: {}
              name: restic-cache-dir
  - apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        k8up.io/owned-by: prune_aiot-prune-n6mjk
        k8up.io/repository-hash: 7f9696c5c10bc4c5c36b1770cf5354c4c6400cf079e9c8a22840ff32a5c2e42
        k8up.io/type: prune
        k8upjob: "true"
        k8upjob/exclusive: "true"
      name: prune-aiot-prune-n6mjk
      namespace: victoriametrics
      ownerReferences:
        - apiVersion: k8up.io/v1
          blockOwnerDeletion: true
          controller: true
          kind: Prune
          name: aiot-prune-n6mjk
          uid: ef1aa4d8-ee1a-4477-a340-805fe55232c0
    spec:
      backoffLimit: 6
      completionMode: NonIndexed
      completions: 1
      manualSelector: false
      parallelism: 1
      podReplacementPolicy: TerminatingOrFailed
      selector:
        matchLabels:
          batch.kubernetes.io/controller-uid: 051d5def-6d12-4a1d-8a88-dc590049c141
      suspend: false
      template:
        metadata:
          creationTimestamp: null
          labels:
            batch.kubernetes.io/controller-uid: 051d5def-6d12-4a1d-8a88-dc590049c141
            batch.kubernetes.io/job-name: prune-aiot-prune-n6mjk
            controller-uid: 051d5def-6d12-4a1d-8a88-dc590049c141
            job-name: prune-aiot-prune-n6mjk
            k8upjob: "true"
        spec:
          containers:
            - args:
                - -varDir
                - /k8up
                - -prune
              command:
                - /usr/local/bin/k8up
                - restic
              env:
                - name: STATS_URL
                - name: HOSTNAME
                  value: victoriametrics
                - name: KEEP_DAILY
                  value: "2"
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: k8up-repo
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: access_key
                      name: r2-creds
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: secret_key
                      name: r2-creds
                - name: PROM_URL
                  value: http://127.0.0.1/
                - name: RESTIC_REPOSITORY
                  value: s3:https://ca6c7e99d62811119041b9334c646aaf.r2.cloudflarestorage.com/aiot-velero
              image: ghcr.io/k8up-io/k8up:v2.15.0
              imagePullPolicy: IfNotPresent
              name: prune
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /k8up
                  name: k8up-dir
                - mountPath: /tmp
                  name: restic-tmp-dir
                - mountPath: /.cache
                  name: restic-cache-dir
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: pod-executor
          serviceAccountName: pod-executor
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: k8up-dir
            - emptyDir: {}
              name: restic-tmp-dir
            - emptyDir: {}
              name: restic-cache-dir
kind: List
metadata:
  resourceVersion: ""
