apiVersion: v1
items:
  - apiVersion: v1
    data:
      password: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: k8up-repo
      namespace: victoriametrics
    type: Opaque
  - apiVersion: v1
    data:
      access_key: REDACTED
      secret_key: REDACTED
    kind: Secret
    metadata:
      annotations:
      name: r2-creds
      namespace: victoriametrics
    type: Opaque
kind: List
metadata:
  resourceVersion: ""
