apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"labels":{"app":"poddefaults","app.kubernetes.io/component":"poddefaults","app.kubernetes.io/name":"poddefaults","kustomize.component":"poddefaults"},"name":"admission-webhook-cert","namespace":"kubeflow"},"spec":{"commonName":"admission-webhook-service.kubeflow.svc","dnsNames":["admission-webhook-service.kubeflow.svc","admission-webhook-service.kubeflow.svc.cluster.local"],"isCA":true,"issuerRef":{"kind":"Issuer","name":"admission-webhook-selfsigned-issuer"},"secretName":"webhook-certs"}}
    creationTimestamp: "2026-04-14T02:30:29Z"
    generation: 1
    labels:
      app: poddefaults
      app.kubernetes.io/component: poddefaults
      app.kubernetes.io/name: poddefaults
      kustomize.component: poddefaults
    name: admission-webhook-cert
    namespace: kubeflow
    resourceVersion: "17353"
    uid: 39b56730-4fb8-4d90-9171-b6b51fa70128
  spec:
    commonName: admission-webhook-service.kubeflow.svc
    dnsNames:
    - admission-webhook-service.kubeflow.svc
    - admission-webhook-service.kubeflow.svc.cluster.local
    isCA: true
    issuerRef:
      kind: Issuer
      name: admission-webhook-selfsigned-issuer
    secretName: webhook-certs
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:30:30Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T02:30:30Z"
    notBefore: "2026-04-14T02:30:30Z"
    renewalTime: "2026-06-13T02:30:30Z"
    revision: 1
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"katib-webhook-cert","namespace":"kubeflow"},"spec":{"commonName":"katib-controller.kubeflow.svc","dnsNames":["katib-controller.kubeflow.svc","katib-controller.kubeflow.svc.cluster.local"],"isCA":true,"issuerRef":{"kind":"Issuer","name":"katib-selfsigned-issuer"},"secretName":"katib-webhook-cert"}}
    creationTimestamp: "2026-04-14T02:30:28Z"
    generation: 1
    name: katib-webhook-cert
    namespace: kubeflow
    resourceVersion: "17234"
    uid: 4c46a1f8-5bf8-4955-975f-dc7176e07ecf
  spec:
    commonName: katib-controller.kubeflow.svc
    dnsNames:
    - katib-controller.kubeflow.svc
    - katib-controller.kubeflow.svc.cluster.local
    isCA: true
    issuerRef:
      kind: Issuer
      name: katib-selfsigned-issuer
    secretName: katib-webhook-cert
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:30:28Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T02:30:28Z"
    notBefore: "2026-04-14T02:30:28Z"
    renewalTime: "2026-06-13T02:30:28Z"
    revision: 1
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"labels":{"app":"cache-server-cert-manager"},"name":"kfp-cache-cert","namespace":"kubeflow"},"spec":{"commonName":"kfp-cache-cert","dnsNames":["cache-server","cache-server.kubeflow","cache-server.kubeflow.svc"],"isCA":true,"issuerRef":{"kind":"Issuer","name":"kfp-cache-selfsigned-issuer"},"secretName":"webhook-server-tls"}}
    creationTimestamp: "2026-04-14T02:26:42Z"
    generation: 1
    labels:
      app: cache-server-cert-manager
    name: kfp-cache-cert
    namespace: kubeflow
    resourceVersion: "15262"
    uid: a6f66634-5330-423b-98f2-b7dd097908c7
  spec:
    commonName: kfp-cache-cert
    dnsNames:
    - cache-server
    - cache-server.kubeflow
    - cache-server.kubeflow.svc
    isCA: true
    issuerRef:
      kind: Issuer
      name: kfp-cache-selfsigned-issuer
    secretName: webhook-server-tls
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:26:43Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T02:26:43Z"
    notBefore: "2026-04-14T02:26:43Z"
    renewalTime: "2026-06-13T02:26:43Z"
    revision: 1
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"labels":{"app":"kserve","app.kubernetes.io/name":"kserve"},"name":"serving-cert","namespace":"kubeflow"},"spec":{"commonName":"kserve-webhook-server-service.kubeflow.svc","dnsNames":["kserve-webhook-server-service.kubeflow.svc"],"issuerRef":{"kind":"Issuer","name":"selfsigned-issuer"},"secretName":"kserve-webhook-server-cert"}}
    creationTimestamp: "2026-04-14T02:27:24Z"
    generation: 1
    labels:
      app: kserve
      app.kubernetes.io/name: kserve
    name: serving-cert
    namespace: kubeflow
    resourceVersion: "15733"
    uid: bdf8ba07-3c8b-48f7-bbc0-3d04055056cf
  spec:
    commonName: kserve-webhook-server-service.kubeflow.svc
    dnsNames:
    - kserve-webhook-server-service.kubeflow.svc
    issuerRef:
      kind: Issuer
      name: selfsigned-issuer
    secretName: kserve-webhook-server-cert
  status:
    conditions:
    - lastTransitionTime: "2026-04-14T02:27:24Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-13T02:27:24Z"
    notBefore: "2026-04-14T02:27:24Z"
    renewalTime: "2026-06-13T02:27:24Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""
