apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"cluster-twin","namespace":"cluster-twin"}}
    name: cluster-twin
    namespace: cluster-twin
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: cluster-twin
kind: List
metadata:
