# aiot-platform overlay for gitea
gitea:
  persistence:
    size: 20Gi
  postgresql-ha:
    pgpool:
      image:
        registry: docker.io
        repository: bitnamilegacy/pgpool
    postgresql:
      image:
        registry: docker.io
        repository: bitnamilegacy/postgresql-repmgr
      extraEnvVars:
      - name: POSTGRESQL_INIT_MAX_TIMEOUT
        value: '600'
      repmgrConnectTimeout: 120
      repmgrReconnectAttempts: 5
      startupProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 60
        successThreshold: 1
      livenessProbe:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 20
        successThreshold: 1
      readinessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 20
        successThreshold: 1
  redis-cluster:
    enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/redis-cluster
  config:
    server:
      DOMAIN: gitea.142.132.207.168.nip.io
      SSH_DOMAIN: gitea.142.132.207.168.nip.io
      ROOT_URL: https://gitea.142.132.207.168.nip.io/
      PROTOCOL: http
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      SHOW_REGISTRATION_BUTTON: false
      DISABLE_REGISTRATION: false
    oauth2_client:
      ENABLE_AUTO_REGISTRATION: true
      ACCOUNT_LINKING: auto
      USERNAME: nickname
      UPDATE_AVATAR: true
